// Code generated by Pickle. DO NOT EDIT.
package models

import (
	"github.com/google/uuid"
	"time"
)

// PostQuery provides typed query methods for Post.
type PostQuery struct {
	*QueryBuilder[Post]
}

// QueryPost starts a new query for Post.
func QueryPost() *PostQuery {
	return &PostQuery{QueryBuilder: Query[Post]("posts")}
}

func (q *PostQuery) WithUser() *PostQuery {
	q.EagerLoad("users")
	return q
}

// WhereOwnedBy filters records by the ownership column.
func (q *PostQuery) WhereOwnedBy(ownerID uuid.UUID) *PostQuery {
	q.Where("user_id", ownerID)
	return q
}

// FetchResource fetches a single Post and serializes it based on ownership.
func (q *PostQuery) FetchResource(ownerID string) (any, error) {
	record, err := q.First()
	if err != nil {
		return nil, err
	}
	return SerializePost(record, ownerID), nil
}

// FetchResources fetches all matching Post records and serializes them based on ownership.
func (q *PostQuery) FetchResources(ownerID string) (any, error) {
	records, err := q.All()
	if err != nil {
		return nil, err
	}
	return SerializePosts(records, ownerID), nil
}

func (q *PostQuery) WhereID(val uuid.UUID) *PostQuery {
	q.Where("id", val)
	return q
}

func (q *PostQuery) WhereIDNot(val uuid.UUID) *PostQuery {
	q.WhereOp("id", "!=", val)
	return q
}

func (q *PostQuery) WhereIDIn(vals []uuid.UUID) *PostQuery {
	q.WhereIn("id", vals)
	return q
}

func (q *PostQuery) WhereIDNotIn(vals []uuid.UUID) *PostQuery {
	q.WhereNotIn("id", vals)
	return q
}

func (q *PostQuery) WhereUserID(val uuid.UUID) *PostQuery {
	q.Where("user_id", val)
	return q
}

func (q *PostQuery) WhereUserIDNot(val uuid.UUID) *PostQuery {
	q.WhereOp("user_id", "!=", val)
	return q
}

func (q *PostQuery) WhereUserIDIn(vals []uuid.UUID) *PostQuery {
	q.WhereIn("user_id", vals)
	return q
}

func (q *PostQuery) WhereUserIDNotIn(vals []uuid.UUID) *PostQuery {
	q.WhereNotIn("user_id", vals)
	return q
}

func (q *PostQuery) WhereTitle(val string) *PostQuery {
	q.Where("title", val)
	return q
}

func (q *PostQuery) WhereTitleNot(val string) *PostQuery {
	q.WhereOp("title", "!=", val)
	return q
}

func (q *PostQuery) WhereTitleIn(vals []string) *PostQuery {
	q.WhereIn("title", vals)
	return q
}

func (q *PostQuery) WhereTitleNotIn(vals []string) *PostQuery {
	q.WhereNotIn("title", vals)
	return q
}

func (q *PostQuery) WhereTitleLike(val string) *PostQuery {
	q.WhereOp("title", "LIKE", val)
	return q
}

func (q *PostQuery) WhereTitleNotLike(val string) *PostQuery {
	q.WhereOp("title", "NOT LIKE", val)
	return q
}

func (q *PostQuery) WhereBody(val string) *PostQuery {
	q.Where("body", val)
	return q
}

func (q *PostQuery) WhereBodyNot(val string) *PostQuery {
	q.WhereOp("body", "!=", val)
	return q
}

func (q *PostQuery) WhereBodyIn(vals []string) *PostQuery {
	q.WhereIn("body", vals)
	return q
}

func (q *PostQuery) WhereBodyNotIn(vals []string) *PostQuery {
	q.WhereNotIn("body", vals)
	return q
}

func (q *PostQuery) WhereBodyLike(val string) *PostQuery {
	q.WhereOp("body", "LIKE", val)
	return q
}

func (q *PostQuery) WhereBodyNotLike(val string) *PostQuery {
	q.WhereOp("body", "NOT LIKE", val)
	return q
}

func (q *PostQuery) WhereStatus(val string) *PostQuery {
	q.Where("status", val)
	return q
}

func (q *PostQuery) WhereStatusNot(val string) *PostQuery {
	q.WhereOp("status", "!=", val)
	return q
}

func (q *PostQuery) WhereStatusIn(vals []string) *PostQuery {
	q.WhereIn("status", vals)
	return q
}

func (q *PostQuery) WhereStatusNotIn(vals []string) *PostQuery {
	q.WhereNotIn("status", vals)
	return q
}

func (q *PostQuery) WhereStatusLike(val string) *PostQuery {
	q.WhereOp("status", "LIKE", val)
	return q
}

func (q *PostQuery) WhereStatusNotLike(val string) *PostQuery {
	q.WhereOp("status", "NOT LIKE", val)
	return q
}

func (q *PostQuery) WhereCreatedAt(val time.Time) *PostQuery {
	q.Where("created_at", val)
	return q
}

func (q *PostQuery) WhereCreatedAtNot(val time.Time) *PostQuery {
	q.WhereOp("created_at", "!=", val)
	return q
}

func (q *PostQuery) WhereCreatedAtIn(vals []time.Time) *PostQuery {
	q.WhereIn("created_at", vals)
	return q
}

func (q *PostQuery) WhereCreatedAtNotIn(vals []time.Time) *PostQuery {
	q.WhereNotIn("created_at", vals)
	return q
}

func (q *PostQuery) WhereCreatedAtBefore(val time.Time) *PostQuery {
	q.WhereOp("created_at", "<", val)
	return q
}

func (q *PostQuery) WhereCreatedAtAfter(val time.Time) *PostQuery {
	q.WhereOp("created_at", ">", val)
	return q
}

func (q *PostQuery) WhereCreatedAtBetween(start, end time.Time) *PostQuery {
	q.WhereOp("created_at", ">=", start)
	q.WhereOp("created_at", "<=", end)
	return q
}

func (q *PostQuery) WhereUpdatedAt(val time.Time) *PostQuery {
	q.Where("updated_at", val)
	return q
}

func (q *PostQuery) WhereUpdatedAtNot(val time.Time) *PostQuery {
	q.WhereOp("updated_at", "!=", val)
	return q
}

func (q *PostQuery) WhereUpdatedAtIn(vals []time.Time) *PostQuery {
	q.WhereIn("updated_at", vals)
	return q
}

func (q *PostQuery) WhereUpdatedAtNotIn(vals []time.Time) *PostQuery {
	q.WhereNotIn("updated_at", vals)
	return q
}

func (q *PostQuery) WhereUpdatedAtBefore(val time.Time) *PostQuery {
	q.WhereOp("updated_at", "<", val)
	return q
}

func (q *PostQuery) WhereUpdatedAtAfter(val time.Time) *PostQuery {
	q.WhereOp("updated_at", ">", val)
	return q
}

func (q *PostQuery) WhereUpdatedAtBetween(start, end time.Time) *PostQuery {
	q.WhereOp("updated_at", ">=", start)
	q.WhereOp("updated_at", "<=", end)
	return q
}
