// Code generated by Pickle. DO NOT EDIT.
package models

import (
	"github.com/google/uuid"
)

// PostPublicResponse contains fields visible to anyone.
type PostPublicResponse struct {
	ID     uuid.UUID `json:"id"`
	Title  string    `json:"title"`
	Status string    `json:"status"`
}

// PostOwnerResponse contains fields visible to the resource owner.
type PostOwnerResponse struct {
	ID     uuid.UUID `json:"id"`
	Title  string    `json:"title"`
	Body   string    `json:"body"`
	Status string    `json:"status"`
}

// SerializePost picks the appropriate response struct based on ownership.
// If ownerID matches the row's owner column, returns PostOwnerResponse.
// Otherwise returns PostPublicResponse.
func SerializePost(record *Post, ownerID string) any {
	if ownerID != "" && record.UserID.String() == ownerID {
		return PostOwnerResponse{
			ID:     record.ID,
			Title:  record.Title,
			Body:   record.Body,
			Status: record.Status,
		}
	}
	return PostPublicResponse{
		ID:     record.ID,
		Title:  record.Title,
		Status: record.Status,
	}
}

// SerializePosts serializes a slice of Post records.
func SerializePosts(records []Post, ownerID string) []any {
	result := make([]any, len(records))
	for i := range records {
		result[i] = SerializePost(&records[i], ownerID)
	}
	return result
}
