// Code generated by Pickle. DO NOT EDIT.
package models

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
)

type Session struct {
	ID        string           `json:"id" db:"id"`
	UserID    uuid.UUID        `json:"user_id" db:"user_id"`
	Role      string           `json:"role" db:"role"`
	Payload   *json.RawMessage `json:"payload,omitempty" db:"payload"`
	ExpiresAt time.Time        `json:"expires_at" db:"expires_at"`
	CreatedAt time.Time        `json:"created_at" db:"created_at"`
	UpdatedAt time.Time        `json:"updated_at" db:"updated_at"`
}
