// Code generated by Pickle. DO NOT EDIT.
package models

import (
	"github.com/google/uuid"
	"time"
)

// UserQuery provides typed query methods for User.
type UserQuery struct {
	*QueryBuilder[User]
}

// QueryUser starts a new query for User.
func QueryUser() *UserQuery {
	return &UserQuery{QueryBuilder: Query[User]("users")}
}

func (q *UserQuery) WhereID(val uuid.UUID) *UserQuery {
	q.Where("id", val)
	return q
}

func (q *UserQuery) WhereIDNot(val uuid.UUID) *UserQuery {
	q.WhereOp("id", "!=", val)
	return q
}

func (q *UserQuery) WhereIDIn(vals []uuid.UUID) *UserQuery {
	q.WhereIn("id", vals)
	return q
}

func (q *UserQuery) WhereIDNotIn(vals []uuid.UUID) *UserQuery {
	q.WhereNotIn("id", vals)
	return q
}

func (q *UserQuery) WhereName(val string) *UserQuery {
	q.Where("name", val)
	return q
}

func (q *UserQuery) WhereNameNot(val string) *UserQuery {
	q.WhereOp("name", "!=", val)
	return q
}

func (q *UserQuery) WhereNameIn(vals []string) *UserQuery {
	q.WhereIn("name", vals)
	return q
}

func (q *UserQuery) WhereNameNotIn(vals []string) *UserQuery {
	q.WhereNotIn("name", vals)
	return q
}

func (q *UserQuery) WhereNameLike(val string) *UserQuery {
	q.WhereOp("name", "LIKE", val)
	return q
}

func (q *UserQuery) WhereNameNotLike(val string) *UserQuery {
	q.WhereOp("name", "NOT LIKE", val)
	return q
}

func (q *UserQuery) WhereEmail(val string) *UserQuery {
	q.Where("email", val)
	return q
}

func (q *UserQuery) WhereEmailNot(val string) *UserQuery {
	q.WhereOp("email", "!=", val)
	return q
}

func (q *UserQuery) WhereEmailIn(vals []string) *UserQuery {
	q.WhereIn("email", vals)
	return q
}

func (q *UserQuery) WhereEmailNotIn(vals []string) *UserQuery {
	q.WhereNotIn("email", vals)
	return q
}

func (q *UserQuery) WhereEmailLike(val string) *UserQuery {
	q.WhereOp("email", "LIKE", val)
	return q
}

func (q *UserQuery) WhereEmailNotLike(val string) *UserQuery {
	q.WhereOp("email", "NOT LIKE", val)
	return q
}

func (q *UserQuery) WherePassword(val string) *UserQuery {
	q.Where("password", val)
	return q
}

func (q *UserQuery) WherePasswordNot(val string) *UserQuery {
	q.WhereOp("password", "!=", val)
	return q
}

func (q *UserQuery) WherePasswordIn(vals []string) *UserQuery {
	q.WhereIn("password", vals)
	return q
}

func (q *UserQuery) WherePasswordNotIn(vals []string) *UserQuery {
	q.WhereNotIn("password", vals)
	return q
}

func (q *UserQuery) WherePasswordLike(val string) *UserQuery {
	q.WhereOp("password", "LIKE", val)
	return q
}

func (q *UserQuery) WherePasswordNotLike(val string) *UserQuery {
	q.WhereOp("password", "NOT LIKE", val)
	return q
}

func (q *UserQuery) WhereCreatedAt(val time.Time) *UserQuery {
	q.Where("created_at", val)
	return q
}

func (q *UserQuery) WhereCreatedAtNot(val time.Time) *UserQuery {
	q.WhereOp("created_at", "!=", val)
	return q
}

func (q *UserQuery) WhereCreatedAtIn(vals []time.Time) *UserQuery {
	q.WhereIn("created_at", vals)
	return q
}

func (q *UserQuery) WhereCreatedAtNotIn(vals []time.Time) *UserQuery {
	q.WhereNotIn("created_at", vals)
	return q
}

func (q *UserQuery) WhereCreatedAtBefore(val time.Time) *UserQuery {
	q.WhereOp("created_at", "<", val)
	return q
}

func (q *UserQuery) WhereCreatedAtAfter(val time.Time) *UserQuery {
	q.WhereOp("created_at", ">", val)
	return q
}

func (q *UserQuery) WhereCreatedAtBetween(start, end time.Time) *UserQuery {
	q.WhereOp("created_at", ">=", start)
	q.WhereOp("created_at", "<=", end)
	return q
}

func (q *UserQuery) WhereUpdatedAt(val time.Time) *UserQuery {
	q.Where("updated_at", val)
	return q
}

func (q *UserQuery) WhereUpdatedAtNot(val time.Time) *UserQuery {
	q.WhereOp("updated_at", "!=", val)
	return q
}

func (q *UserQuery) WhereUpdatedAtIn(vals []time.Time) *UserQuery {
	q.WhereIn("updated_at", vals)
	return q
}

func (q *UserQuery) WhereUpdatedAtNotIn(vals []time.Time) *UserQuery {
	q.WhereNotIn("updated_at", vals)
	return q
}

func (q *UserQuery) WhereUpdatedAtBefore(val time.Time) *UserQuery {
	q.WhereOp("updated_at", "<", val)
	return q
}

func (q *UserQuery) WhereUpdatedAtAfter(val time.Time) *UserQuery {
	q.WhereOp("updated_at", ">", val)
	return q
}

func (q *UserQuery) WhereUpdatedAtBetween(start, end time.Time) *UserQuery {
	q.WhereOp("updated_at", ">=", start)
	q.WhereOp("updated_at", "<=", end)
	return q
}
