// Code generated by Pickle. DO NOT EDIT.
package models

import (
	"github.com/google/uuid"
	"time"
)

// UserPostStat is a read-only model generated from the user_post_stats database view.
type UserPostStat struct {
	ID           uuid.UUID `json:"id" db:"id"`
	Name         string    `json:"name" db:"name"`
	Email        string    `json:"email" db:"email"`
	PostCount    int64     `json:"post_count" db:"post_count"`
	LatestPostAt time.Time `json:"latest_post_at" db:"latest_post_at"`
}
