// Code generated by Pickle. DO NOT EDIT.
package models

import (
	"github.com/google/uuid"
	"time"
)

// UserPostStatQuery provides read-only typed query methods for the user_post_stats view.
type UserPostStatQuery struct {
	*QueryBuilder[UserPostStat]
}

// QueryUserPostStat starts a new read-only query for UserPostStat.
func QueryUserPostStat() *UserPostStatQuery {
	return &UserPostStatQuery{QueryBuilder: Query[UserPostStat]("user_post_stats")}
}

func (q *UserPostStatQuery) WhereID(val uuid.UUID) *UserPostStatQuery {
	q.Where("id", val)
	return q
}

func (q *UserPostStatQuery) WhereIDNot(val uuid.UUID) *UserPostStatQuery {
	q.WhereOp("id", "!=", val)
	return q
}

func (q *UserPostStatQuery) WhereIDIn(vals []uuid.UUID) *UserPostStatQuery {
	q.WhereIn("id", vals)
	return q
}

func (q *UserPostStatQuery) WhereIDNotIn(vals []uuid.UUID) *UserPostStatQuery {
	q.WhereNotIn("id", vals)
	return q
}

func (q *UserPostStatQuery) WhereName(val string) *UserPostStatQuery {
	q.Where("name", val)
	return q
}

func (q *UserPostStatQuery) WhereNameNot(val string) *UserPostStatQuery {
	q.WhereOp("name", "!=", val)
	return q
}

func (q *UserPostStatQuery) WhereNameIn(vals []string) *UserPostStatQuery {
	q.WhereIn("name", vals)
	return q
}

func (q *UserPostStatQuery) WhereNameNotIn(vals []string) *UserPostStatQuery {
	q.WhereNotIn("name", vals)
	return q
}

func (q *UserPostStatQuery) WhereNameLike(val string) *UserPostStatQuery {
	q.WhereOp("name", "LIKE", val)
	return q
}

func (q *UserPostStatQuery) WhereNameNotLike(val string) *UserPostStatQuery {
	q.WhereOp("name", "NOT LIKE", val)
	return q
}

func (q *UserPostStatQuery) WhereEmail(val string) *UserPostStatQuery {
	q.Where("email", val)
	return q
}

func (q *UserPostStatQuery) WhereEmailNot(val string) *UserPostStatQuery {
	q.WhereOp("email", "!=", val)
	return q
}

func (q *UserPostStatQuery) WhereEmailIn(vals []string) *UserPostStatQuery {
	q.WhereIn("email", vals)
	return q
}

func (q *UserPostStatQuery) WhereEmailNotIn(vals []string) *UserPostStatQuery {
	q.WhereNotIn("email", vals)
	return q
}

func (q *UserPostStatQuery) WhereEmailLike(val string) *UserPostStatQuery {
	q.WhereOp("email", "LIKE", val)
	return q
}

func (q *UserPostStatQuery) WhereEmailNotLike(val string) *UserPostStatQuery {
	q.WhereOp("email", "NOT LIKE", val)
	return q
}

func (q *UserPostStatQuery) WherePostCount(val int64) *UserPostStatQuery {
	q.Where("post_count", val)
	return q
}

func (q *UserPostStatQuery) WherePostCountNot(val int64) *UserPostStatQuery {
	q.WhereOp("post_count", "!=", val)
	return q
}

func (q *UserPostStatQuery) WherePostCountIn(vals []int64) *UserPostStatQuery {
	q.WhereIn("post_count", vals)
	return q
}

func (q *UserPostStatQuery) WherePostCountNotIn(vals []int64) *UserPostStatQuery {
	q.WhereNotIn("post_count", vals)
	return q
}

func (q *UserPostStatQuery) WherePostCountGT(val int64) *UserPostStatQuery {
	q.WhereOp("post_count", ">", val)
	return q
}

func (q *UserPostStatQuery) WherePostCountGTE(val int64) *UserPostStatQuery {
	q.WhereOp("post_count", ">=", val)
	return q
}

func (q *UserPostStatQuery) WherePostCountLT(val int64) *UserPostStatQuery {
	q.WhereOp("post_count", "<", val)
	return q
}

func (q *UserPostStatQuery) WherePostCountLTE(val int64) *UserPostStatQuery {
	q.WhereOp("post_count", "<=", val)
	return q
}

func (q *UserPostStatQuery) WhereLatestPostAt(val time.Time) *UserPostStatQuery {
	q.Where("latest_post_at", val)
	return q
}

func (q *UserPostStatQuery) WhereLatestPostAtNot(val time.Time) *UserPostStatQuery {
	q.WhereOp("latest_post_at", "!=", val)
	return q
}

func (q *UserPostStatQuery) WhereLatestPostAtIn(vals []time.Time) *UserPostStatQuery {
	q.WhereIn("latest_post_at", vals)
	return q
}

func (q *UserPostStatQuery) WhereLatestPostAtNotIn(vals []time.Time) *UserPostStatQuery {
	q.WhereNotIn("latest_post_at", vals)
	return q
}

func (q *UserPostStatQuery) WhereLatestPostAtBefore(val time.Time) *UserPostStatQuery {
	q.WhereOp("latest_post_at", "<", val)
	return q
}

func (q *UserPostStatQuery) WhereLatestPostAtAfter(val time.Time) *UserPostStatQuery {
	q.WhereOp("latest_post_at", ">", val)
	return q
}

func (q *UserPostStatQuery) WhereLatestPostAtBetween(start, end time.Time) *UserPostStatQuery {
	q.WhereOp("latest_post_at", ">=", start)
	q.WhereOp("latest_post_at", "<=", end)
	return q
}
