// Code generated by Pickle. DO NOT EDIT.
package commands

import (
	"database/sql"
	"fmt"
	"log"

	pickle "github.com/shortontech/pickle/testdata/basic-crud/app/http"
	"github.com/shortontech/pickle/testdata/basic-crud/app/models"
	"github.com/shortontech/pickle/testdata/basic-crud/config"
	"github.com/shortontech/pickle/testdata/basic-crud/database/migrations"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = log.Fatal
	_ *sql.DB
)

// migrateCommand runs pending migrations.
type migrateCommand struct{}

func (c migrateCommand) Name() string        { return "migrate" }
func (c migrateCommand) Description() string { return "Run pending migrations" }
func (c migrateCommand) Run(args []string) error {
	runner := migrations.NewRunner(models.DB, config.Database.Connection().Driver)
	return runner.Migrate(migrations.Registry)
}

// migrateRollbackCommand rolls back the last batch.
type migrateRollbackCommand struct{}

func (c migrateRollbackCommand) Name() string        { return "migrate:rollback" }
func (c migrateRollbackCommand) Description() string { return "Roll back the last migration batch" }
func (c migrateRollbackCommand) Run(args []string) error {
	runner := migrations.NewRunner(models.DB, config.Database.Connection().Driver)
	return runner.Rollback(migrations.Registry)
}

// migrateFreshCommand drops all tables and re-runs migrations.
type migrateFreshCommand struct{}

func (c migrateFreshCommand) Name() string        { return "migrate:fresh" }
func (c migrateFreshCommand) Description() string { return "Drop all tables and re-run all migrations" }
func (c migrateFreshCommand) Run(args []string) error {
	runner := migrations.NewRunner(models.DB, config.Database.Connection().Driver)
	return runner.Fresh(migrations.Registry)
}

// migrateStatusCommand shows migration status.
type migrateStatusCommand struct{}

func (c migrateStatusCommand) Name() string        { return "migrate:status" }
func (c migrateStatusCommand) Description() string { return "Show migration status" }
func (c migrateStatusCommand) Run(args []string) error {
	runner := migrations.NewRunner(models.DB, config.Database.Connection().Driver)
	statuses, err := runner.Status(migrations.Registry)
	if err != nil {
		return err
	}
	migrations.PrintStatus(statuses)
	return nil
}

// BuiltinCommands returns the built-in Pickle commands.
func BuiltinCommands() []pickle.Command {
	return []pickle.Command{
		migrateCommand{},
		migrateRollbackCommand{},
		migrateFreshCommand{},
		migrateStatusCommand{},
	}
}

// UserCommands returns user-defined commands.
func UserCommands() []pickle.Command {
	return []pickle.Command{}
}

// Commands returns all commands (built-in + user-defined).
func Commands() []pickle.Command {
	return append(BuiltinCommands(), UserCommands()...)
}
