package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/shortontech/pickle/pkg/tickle"
)

const placeholder = "__PACKAGE__"

var templates = []struct {
	srcDir string // relative to repo root
	output string // relative to repo root
	skip   map[string]bool
	only   map[string]bool
}{
	{
		srcDir: "pkg/cooked",
		output: "pkg/generator/embed_http.go",
		skip:   map[string]bool{"query.go": true, "scopes.go": true, "config.go": true},
	},
	{
		srcDir: "pkg/cooked",
		output: "pkg/generator/embed_query.go",
		only:   map[string]bool{"query.go": true},
	},
	{
		srcDir: "pkg/cooked",
		output: "pkg/generator/embed_config.go",
		only:   map[string]bool{"config.go": true},
	},
	{
		srcDir: "pkg/schema",
		output: "pkg/generator/embed_schema.go",
	},
	{
		srcDir: "pkg/migration",
		output: "pkg/generator/embed_migration.go",
	},
	{
		srcDir: "pkg/cooked/auth/jwt",
		output: "pkg/generator/embed_auth_jwt.go",
	},
	{
		srcDir: "pkg/cooked/auth/session",
		output: "pkg/generator/embed_auth_session.go",
	},
	{
		srcDir: "pkg/cooked/auth/session/migrations",
		output: "pkg/generator/embed_auth_session_migrations.go",
	},
}

func main() {
	root, err := findRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "tickle: %v\n", err)
		os.Exit(1)
	}

	for _, t := range templates {
		srcDir := filepath.Join(root, t.srcDir)

		// If filtering, copy to a temp dir with only the wanted files
		dir := srcDir
		if t.skip != nil || t.only != nil {
			dir, err = filterDir(srcDir, t.skip, t.only)
			if err != nil {
				fmt.Fprintf(os.Stderr, "tickle: %v\n", err)
				os.Exit(1)
			}
			defer os.RemoveAll(dir)
		}

		merged, err := tickle.Merge(dir, placeholder)
		if err != nil {
			fmt.Fprintf(os.Stderr, "tickle: %v\n", err)
			os.Exit(1)
		}

		varName := varNameFromPath(t.output)
		outputPath := filepath.Join(root, t.output)
		if err := writeEmbedFile(outputPath, varName, merged); err != nil {
			fmt.Fprintf(os.Stderr, "tickle: %v\n", err)
			os.Exit(1)
		}

		fmt.Printf("  %s → %s\n", t.srcDir, t.output)
	}

	// Extract docs from pkg/cooked/ and write embed_docs.go
	cookedDir := filepath.Join(root, "pkg", "cooked")
	docs, err := tickle.ExtractDocs(cookedDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "tickle: extracting docs: %v\n", err)
		os.Exit(1)
	}

	docsJSON, err := json.MarshalIndent(docs, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "tickle: marshaling docs: %v\n", err)
		os.Exit(1)
	}

	docsOutput := filepath.Join(root, "pkg", "generator", "embed_docs.go")
	if err := writeDocsFile(docsOutput, string(docsJSON)); err != nil {
		fmt.Fprintf(os.Stderr, "tickle: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("  pkg/cooked/ → pkg/generator/embed_docs.go (%d types)\n", len(docs))

	fmt.Println("tickle: done")
}

func filterDir(srcDir string, skip, only map[string]bool) (string, error) {
	tmp, err := os.MkdirTemp("", "tickle-*")
	if err != nil {
		return "", err
	}

	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return "", err
	}

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		if only != nil && !only[e.Name()] {
			continue
		}
		if skip != nil && skip[e.Name()] {
			continue
		}
		data, err := os.ReadFile(filepath.Join(srcDir, e.Name()))
		if err != nil {
			return "", err
		}
		if err := os.WriteFile(filepath.Join(tmp, e.Name()), data, 0o644); err != nil {
			return "", err
		}
	}

	return tmp, nil
}

func writeEmbedFile(path, varName, content string) error {
	var b strings.Builder
	b.WriteString("// Code generated by tickle. DO NOT EDIT.\n")
	b.WriteString("package generator\n\n")
	b.WriteString(fmt.Sprintf("const %s = %s\n", varName, quote(content)))

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func quote(s string) string {
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	return fmt.Sprintf("%q", s)
}

func varNameFromPath(path string) string {
	base := filepath.Base(path)
	base = strings.TrimSuffix(base, ".go")
	parts := strings.Split(base, "_")
	for i := 1; i < len(parts); i++ {
		parts[i] = strings.ToUpper(parts[i])
	}
	return strings.Join(parts, "")
}

func writeDocsFile(path, jsonContent string) error {
	var b strings.Builder
	b.WriteString("// Code generated by tickle. DO NOT EDIT.\n")
	b.WriteString("package generator\n\n")
	b.WriteString("const embedDOCS = " + quote(jsonContent) + "\n")

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find go.mod")
		}
		dir = parent
	}
}
