package tickle

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var packageLine = regexp.MustCompile(`(?m)^package \w+\s*\n`)
var importBlock = regexp.MustCompile(`(?ms)^import\s*\(.*?\)\s*\n`)
var singleImport = regexp.MustCompile(`(?m)^import\s+"[^"]+"\s*\n`)
var buildConstraint = regexp.MustCompile(`(?m)^//go:build\s+.*\n`)

// Tickle reads Go source files from srcDir and returns their contents
// with the package declaration replaced to targetPackage.
// Each file's content is returned as a map of filename → source.
func Tickle(srcDir, targetPackage string) (map[string]string, error) {
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", srcDir, err)
	}

	result := make(map[string]string)

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		// Skip test files
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		content, err := os.ReadFile(filepath.Join(srcDir, entry.Name()))
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", entry.Name(), err)
		}

		result[entry.Name()] = string(content)
	}

	return result, nil
}

// Merge reads Go source files from srcDir, merges them into a single valid
// Go file with one package declaration and one consolidated import block,
// using targetPackage as the package name.
func Merge(srcDir, targetPackage string) (string, error) {
	files, err := Tickle(srcDir, targetPackage)
	if err != nil {
		return "", err
	}

	names := sortedKeys(files)

	var imports []string
	var bodies []string

	for _, name := range names {
		src := files[name]
		imports = append(imports, extractImports(src)...)
		bodies = append(bodies, stripHeaderFull(src))
	}

	// Deduplicate imports
	seen := map[string]bool{}
	var uniqueImports []string
	for _, imp := range imports {
		if !seen[imp] {
			seen[imp] = true
			uniqueImports = append(uniqueImports, imp)
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString("package " + targetPackage + "\n\n")

	if len(uniqueImports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range uniqueImports {
			b.WriteString("\t" + imp + "\n")
		}
		b.WriteString(")\n\n")
	}

	for _, body := range bodies {
		body = strings.TrimSpace(body)
		if body != "" {
			b.WriteString(body)
			b.WriteString("\n\n")
		}
	}

	return b.String(), nil
}

// extractImports pulls import paths from Go source.
func extractImports(src string) []string {
	var imports []string

	// Grouped imports: import ( ... )
	for _, match := range importBlock.FindAllString(src, -1) {
		// Extract lines between ( and )
		inner := match[strings.Index(match, "(")+1 : strings.LastIndex(match, ")")]
		for _, line := range strings.Split(inner, "\n") {
			line = strings.TrimSpace(line)
			if line != "" {
				imports = append(imports, line)
			}
		}
	}

	// Single imports: import "foo"
	for _, match := range singleImport.FindAllString(src, -1) {
		path := strings.TrimPrefix(strings.TrimSpace(match), "import ")
		path = strings.TrimSpace(path)
		if path != "" {
			imports = append(imports, path)
		}
	}

	return imports
}

// stripHeaderFull removes package declaration, build constraints, and all
// import blocks from Go source.
func stripHeaderFull(src string) string {
	src = buildConstraint.ReplaceAllString(src, "")
	src = packageLine.ReplaceAllString(src, "")
	src = importBlock.ReplaceAllString(src, "")
	src = singleImport.ReplaceAllString(src, "")
	return src
}

func sortedKeys(m map[string]string) []string {
	var keys []string
	for k := range m {
		keys = append(keys, k)
	}
	for i := 0; i < len(keys); i++ {
		for j := i + 1; j < len(keys); j++ {
			if keys[i] > keys[j] {
				keys[i], keys[j] = keys[j], keys[i]
			}
		}
	}
	return keys
}
