package tickle

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestTickle(t *testing.T) {
	dir := t.TempDir()
	src := `package cooked

import "database/sql"

var DB *sql.DB

func Query[T any]() *QueryBuilder[T] {
	return &QueryBuilder[T]{}
}
`
	os.WriteFile(filepath.Join(dir, "query.go"), []byte(src), 0o644)
	os.WriteFile(filepath.Join(dir, "query_test.go"), []byte("package cooked\n"), 0o644)

	files, err := Tickle(dir, "generated")
	if err != nil {
		t.Fatalf("Tickle: %v", err)
	}

	if len(files) != 1 {
		t.Fatalf("expected 1 file, got %d", len(files))
	}

	if _, ok := files["query_test.go"]; ok {
		t.Error("test file should be skipped")
	}

	if !strings.Contains(files["query.go"], "func Query[T any]()") {
		t.Error("function body missing")
	}
}

func TestMerge(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "query.go"), []byte("package cooked\n\nimport \"database/sql\"\n\nvar X = 1\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "context.go"), []byte("package cooked\n\nimport \"net/http\"\n\nvar Y = 2\n"), 0o644)

	out, err := Merge(dir, "myapp")
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	// Single package declaration
	if strings.Count(out, "package myapp") != 1 {
		t.Errorf("expected exactly 1 package declaration, got %d", strings.Count(out, "package myapp"))
	}

	if !strings.Contains(out, "// Code generated by Pickle. DO NOT EDIT.") {
		t.Error("missing generated header")
	}

	// Both bodies present
	if !strings.Contains(out, "var X = 1") {
		t.Error("missing content from query.go")
	}
	if !strings.Contains(out, "var Y = 2") {
		t.Error("missing content from context.go")
	}

	// Imports merged
	if !strings.Contains(out, `"database/sql"`) {
		t.Error("missing database/sql import")
	}
	if !strings.Contains(out, `"net/http"`) {
		t.Error("missing net/http import")
	}

	// context.go body should come before query.go body (alphabetical)
	yIdx := strings.Index(out, "var Y = 2")
	xIdx := strings.Index(out, "var X = 1")
	if yIdx > xIdx {
		t.Error("files should be merged alphabetically")
	}
}
