// Code generated by Pickle. DO NOT EDIT.
package basiccrud

import (
	"net/http"
)

// RegisterRoutes wires all route handlers onto the given ServeMux.
func RegisterRoutes(mux *http.ServeMux) {
	// GET /api/posts/
	mux.HandleFunc("GET /api/posts/", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		resp := RunMiddleware(ctx, []MiddlewareFunc{Auth}, func() Response {
			return (&PostController{}).Index(ctx)
		})
		resp.Write(w)
	})

	// POST /api/posts/
	mux.HandleFunc("POST /api/posts/", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		resp := RunMiddleware(ctx, []MiddlewareFunc{Auth}, func() Response {
			req, bindErr := BindCreatePostRequest(r)
			if bindErr != nil {
				return ctx.JSON(bindErr.Status, bindErr)
			}
			return (&PostController{}).Store(req, ctx)
		})
		resp.Write(w)
	})

	// DELETE /api/posts/{id}
	mux.HandleFunc("DELETE /api/posts/{id}", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		ctx.SetParam("id", r.PathValue("id"))
		resp := RunMiddleware(ctx, []MiddlewareFunc{Auth}, func() Response {
			return (&PostController{}).Destroy(ctx)
		})
		resp.Write(w)
	})

	// GET /api/posts/{id}
	mux.HandleFunc("GET /api/posts/{id}", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		ctx.SetParam("id", r.PathValue("id"))
		resp := RunMiddleware(ctx, []MiddlewareFunc{Auth}, func() Response {
			return (&PostController{}).Show(ctx)
		})
		resp.Write(w)
	})

	// PUT /api/posts/{id}
	mux.HandleFunc("PUT /api/posts/{id}", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		ctx.SetParam("id", r.PathValue("id"))
		resp := RunMiddleware(ctx, []MiddlewareFunc{Auth}, func() Response {
			req, bindErr := BindUpdatePostRequest(r)
			if bindErr != nil {
				return ctx.JSON(bindErr.Status, bindErr)
			}
			return (&PostController{}).Update(req, ctx)
		})
		resp.Write(w)
	})

	// GET /api/users
	mux.HandleFunc("GET /api/users", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		resp := RunMiddleware(ctx, nil, func() Response {
			return (&UserController{}).Index(ctx)
		})
		resp.Write(w)
	})

	// POST /api/users
	mux.HandleFunc("POST /api/users", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		resp := RunMiddleware(ctx, nil, func() Response {
			req, bindErr := BindCreateUserRequest(r)
			if bindErr != nil {
				return ctx.JSON(bindErr.Status, bindErr)
			}
			return (&UserController{}).Store(req, ctx)
		})
		resp.Write(w)
	})

	// DELETE /api/users/{id}
	mux.HandleFunc("DELETE /api/users/{id}", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		ctx.SetParam("id", r.PathValue("id"))
		resp := RunMiddleware(ctx, nil, func() Response {
			return (&UserController{}).Destroy(ctx)
		})
		resp.Write(w)
	})

	// GET /api/users/{id}
	mux.HandleFunc("GET /api/users/{id}", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		ctx.SetParam("id", r.PathValue("id"))
		resp := RunMiddleware(ctx, nil, func() Response {
			return (&UserController{}).Show(ctx)
		})
		resp.Write(w)
	})

	// PUT /api/users/{id}
	mux.HandleFunc("PUT /api/users/{id}", func(w http.ResponseWriter, r *http.Request) {
		ctx := NewContext(w, r)
		ctx.SetParam("id", r.PathValue("id"))
		resp := RunMiddleware(ctx, nil, func() Response {
			req, bindErr := BindUpdateUserRequest(r)
			if bindErr != nil {
				return ctx.JSON(bindErr.Status, bindErr)
			}
			return (&UserController{}).Update(req, ctx)
		})
		resp.Write(w)
	})
}
