package generator

import (
	"bytes"
	"fmt"
	"go/format"
)

// GenerateActionWiringWithAudit produces gated action methods that include
// transactional audit trail writes. The action and its audit row are written
// in the same database transaction — both succeed or both roll back.
// This implements specs 040 and 045.
func GenerateActionWiringWithAudit(set *ActionSet, packageName, actionImportPath, httpImportPath, auditImportPath string) ([]byte, error) {
	if len(set.Actions) == 0 && len(set.Gates) == 0 {
		return nil, nil
	}

	structName := tableToStructName(set.Model)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	needsImport := len(set.Actions) > 0
	if needsImport {
		buf.WriteString("import (\n")
		buf.WriteString(fmt.Sprintf("\tpickle %q\n", httpImportPath))
		buf.WriteString(fmt.Sprintf("\tactions %q\n", actionImportPath))
		if auditImportPath != "" {
			buf.WriteString(fmt.Sprintf("\taudit %q\n", auditImportPath))
		}
		buf.WriteString(")\n\n")
	}

	// Build gate lookup for source comments
	gateFiles := map[string]string{}
	for _, g := range set.Gates {
		gateFiles[g.ActionName] = g.SourceFile
	}

	versionExpr := "nil"
	if set.IsImmutable {
		versionExpr = "&m.VersionID"
	}

	for _, action := range set.Actions {
		gateFile := gateFiles[action.Name]

		buf.WriteString(fmt.Sprintf("// %s — action source: %s\n", action.Name, action.SourceFile))
		if gateFile != "" {
			buf.WriteString(fmt.Sprintf("//         gate source:   %s\n", gateFile))
		}

		constName := "audit.ActionType" + structName + action.Name

		if action.HasResult {
			buf.WriteString(fmt.Sprintf("func (m *%s) %s(ctx *pickle.Context, action actions.%s) (%s, error) {\n",
				structName, action.Name, action.StructName, action.ResultType))
			buf.WriteString(fmt.Sprintf("\troleID := actions.Can%s(ctx, m)\n", action.Name))
			buf.WriteString("\tif roleID == nil {\n")
			buf.WriteString(fmt.Sprintf("\t\tpickle.AuditDenied(ctx, %q, %q, m.ID, \"gate_check_failed\")\n", action.Name, structName))
			buf.WriteString("\t\treturn nil, ErrUnauthorized\n")
			buf.WriteString("\t}\n")
			buf.WriteString(fmt.Sprintf("\tvar result %s\n", action.ResultType))
			buf.WriteString("\terr := pickle.WithTransaction(func(tx *pickle.Tx) error {\n")
			buf.WriteString("\t\tvar execErr error\n")
			buf.WriteString(fmt.Sprintf("\t\tresult, execErr = action.%s(ctx, m, tx.Conn())\n", toLowerFirst(action.Name)))
			buf.WriteString("\t\tif execErr != nil {\n")
			buf.WriteString("\t\t\treturn execErr\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString(fmt.Sprintf("\t\treturn audit.Performed(ctx, %s, m.ID, %s, roleID, tx.Conn())\n", constName, versionExpr))
			buf.WriteString("\t})\n")
			buf.WriteString("\tif err != nil {\n")
			buf.WriteString(fmt.Sprintf("\t\tpickle.AuditFailed(ctx, %q, %q, m.ID, err)\n", action.Name, structName))
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn result, nil\n")
		} else {
			buf.WriteString(fmt.Sprintf("func (m *%s) %s(ctx *pickle.Context, action actions.%s) error {\n",
				structName, action.Name, action.StructName))
			buf.WriteString(fmt.Sprintf("\troleID := actions.Can%s(ctx, m)\n", action.Name))
			buf.WriteString("\tif roleID == nil {\n")
			buf.WriteString(fmt.Sprintf("\t\tpickle.AuditDenied(ctx, %q, %q, m.ID, \"gate_check_failed\")\n", action.Name, structName))
			buf.WriteString("\t\treturn ErrUnauthorized\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\terr := pickle.WithTransaction(func(tx *pickle.Tx) error {\n")
			buf.WriteString(fmt.Sprintf("\t\tif execErr := action.%s(ctx, m, tx.Conn()); execErr != nil {\n", toLowerFirst(action.Name)))
			buf.WriteString("\t\t\treturn execErr\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString(fmt.Sprintf("\t\treturn audit.Performed(ctx, %s, m.ID, %s, roleID, tx.Conn())\n", constName, versionExpr))
			buf.WriteString("\t})\n")
			buf.WriteString("\tif err != nil {\n")
			buf.WriteString(fmt.Sprintf("\t\tpickle.AuditFailed(ctx, %q, %q, m.ID, err)\n", action.Name, structName))
			buf.WriteString("\t\treturn err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn nil\n")
		}
		buf.WriteString("}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("formatting action audit wiring for %s: %w\n%s", set.Model, err, buf.String())
	}
	return formatted, nil
}
