package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// cookedImportPath is the import path used in cooked source files for the pickle HTTP types.
// The generator replaces this with the user's project-specific import path.
const cookedImportPath = "github.com/shortontech/pickle/pkg/cooked"

// AuthDriverInfo describes a discovered auth driver.
type AuthDriverInfo struct {
	Name      string // directory name, e.g. "jwt", "session", "my_custom"
	IsBuiltin bool   // true if Pickle provides a built-in template for this driver
	NeedsGen  bool   // true if driver_gen.go should be written (no driver.go override)
	Dir       string // absolute path to the driver subdirectory
}

// builtinAuthDrivers maps driver names to their embed constants.
var builtinAuthDrivers = map[string]string{
	"jwt":     embedAUTHJWT,
	"session": embedAUTHSESSION,
}

// builtinAuthMigrations maps driver names to a list of (filename, embed content) pairs.
// Filenames follow the standard migration naming convention with timestamps.
var builtinAuthMigrations = map[string][]struct {
	Filename string
	Embed    string
}{
	"session": {
		{
			Filename: "2026_02_27_011700_create_sessions_table_gen.go",
			Embed:    embedAUTHSESSIONMIGRATIONS,
		},
	},
}

// ScanAuthDrivers scans subdirectories of authDir for auth drivers.
// Each subdirectory is a driver. If driver.go exists, the user owns it.
// If not, and a built-in template exists, driver_gen.go will be generated.
func ScanAuthDrivers(authDir string) ([]AuthDriverInfo, error) {
	entries, err := os.ReadDir(authDir)
	if err != nil {
		return nil, err
	}

	var drivers []AuthDriverInfo
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}

		name := e.Name()
		dir := filepath.Join(authDir, name)

		// Check if user has a driver.go override
		_, hasDriverGo := statFile(filepath.Join(dir, "driver.go"))
		_, builtin := builtinAuthDrivers[name]

		drivers = append(drivers, AuthDriverInfo{
			Name:      name,
			IsBuiltin: builtin,
			NeedsGen:  builtin && !hasDriverGo,
			Dir:       dir,
		})
	}

	return drivers, nil
}

// GenerateBuiltinDriver writes driver_gen.go for a built-in auth driver.
// Replaces __PACKAGE__ and __HTTP_IMPORT__ placeholders.
func GenerateBuiltinDriver(driver AuthDriverInfo, httpImport string) ([]byte, error) {
	embed, ok := builtinAuthDrivers[driver.Name]
	if !ok {
		return nil, fmt.Errorf("no built-in template for driver %q", driver.Name)
	}

	src := strings.ReplaceAll(embed, packagePlaceholder, driver.Name)
	src = strings.ReplaceAll(src, cookedImportPath, httpImport)
	return []byte(src), nil
}

// GenerateAuthRegistry produces auth/pickle_gen.go with the AuthDriver interface,
// driver registry, and default middleware.
func GenerateAuthRegistry(drivers []AuthDriverInfo, modulePath, httpImport, configImport string) ([]byte, error) {
	data := struct {
		HTTPImport   string
		ConfigImport string
		Drivers      []AuthDriverInfo
		DriverImports []struct {
			Alias string
			Path  string
		}
	}{
		HTTPImport:   httpImport,
		ConfigImport: configImport,
		Drivers:      drivers,
	}

	for _, d := range drivers {
		alias := d.Name
		// Avoid Go keyword collisions
		if alias == "type" || alias == "func" || alias == "var" {
			alias = alias + "Driver"
		}
		data.DriverImports = append(data.DriverImports, struct {
			Alias string
			Path  string
		}{
			Alias: alias,
			Path:  modulePath + "/app/http/auth/" + d.Name,
		})
	}

	var buf bytes.Buffer
	if err := authRegistryTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("auth registry template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("formatting auth registry: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

// WriteDriverMigrations writes migration files for a built-in auth driver
// into the project's database/migrations/ directory. Files use _gen.go suffix
// so they're recognized as Pickle-owned.
func WriteDriverMigrations(driverName, migrationsDir, migrationsPkg string) error {
	migrations, ok := builtinAuthMigrations[driverName]
	if !ok {
		return nil // no migrations for this driver
	}

	for _, m := range migrations {
		src := strings.ReplaceAll(m.Embed, packagePlaceholder, migrationsPkg)
		path := filepath.Join(migrationsDir, m.Filename)
		if err := os.MkdirAll(migrationsDir, 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
			return err
		}
	}

	return nil
}

func statFile(path string) (os.FileInfo, bool) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, false
	}
	return info, true
}

var authRegistryTemplate = template.Must(template.New("auth").Parse(`// Code generated by Pickle. DO NOT EDIT.
package auth

import (
	"fmt"
	"net/http"
	"os"

	pickle "{{ .HTTPImport }}"
	"{{ .ConfigImport }}"
{{ range .DriverImports }}	{{ .Alias }} "{{ .Path }}"
{{ end }})

// AuthDriver is the interface every auth driver implements.
type AuthDriver interface {
	// Authenticate validates the request and returns auth info.
	// Returns nil, err if authentication fails.
	Authenticate(r *http.Request) (*pickle.AuthInfo, error)
}

var registry = map[string]AuthDriver{}

func init() {
{{ range .Drivers }}	registry["{{ .Name }}"] = {{ .Name }}.NewDriver(config.Env)
{{ end }}}

// Driver returns the named auth driver, or panics if not found.
func Driver(name string) AuthDriver {
	d, ok := registry[name]
	if !ok {
		available := make([]string, 0, len(registry))
		for k := range registry {
			available = append(available, k)
		}
		panic(fmt.Sprintf("auth: unknown driver %q (available: %v)", name, available))
	}
	return d
}

// ActiveDriver returns the driver selected by AUTH_DRIVER env var.
func ActiveDriver() AuthDriver {
	name := config.Env("AUTH_DRIVER", "")
	if name == "" {
		// Default to first available
		for k := range registry {
			name = k
			break
		}
	}
	return Driver(name)
}

// ActiveDriverName returns the name of the currently active auth driver.
func ActiveDriverName() string {
	name := config.Env("AUTH_DRIVER", "")
	if name == "" {
		for k := range registry {
			return k
		}
	}
	return name
}

// Authenticate is a convenience function that calls Authenticate on the active driver.
func Authenticate(r *http.Request) (*pickle.AuthInfo, error) {
	return ActiveDriver().Authenticate(r)
}

// DefaultAuthMiddleware validates requests using the active auth driver
// and sets auth info on the context.
func DefaultAuthMiddleware(ctx *pickle.Context, next func() pickle.Response) pickle.Response {
	info, err := Authenticate(ctx.Request())
	if err != nil {
		return ctx.Unauthorized(err.Error())
	}
	ctx.SetAuth(info)
	return next()
}

// Env reads the AUTH_DRIVER environment variable.
// Useful for logging or diagnostics.
func Env() string {
	return os.Getenv("AUTH_DRIVER")
}
`))
