package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// RoleAnnotation describes a role that should generate a column annotation method.
type RoleAnnotation struct {
	Slug       string // e.g. "compliance", "support_lead"
	PascalName string // e.g. "Compliance", "SupportLead"
}

// GenerateColumnAnnotations produces Go source with XxxSees() methods on Column
// for each non-manages role. The methods call RoleSees(slug) under the hood.
func GenerateColumnAnnotations(packageName string, roles []RoleAnnotation) ([]byte, error) {
	if len(roles) == 0 {
		return nil, nil
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	for _, role := range roles {
		fmt.Fprintf(&buf, "// %sSees marks this column as visible to the %q role.\n", role.PascalName, role.Slug)
		fmt.Fprintf(&buf, "func (c *Column) %sSees() *Column {\n", role.PascalName)
		fmt.Fprintf(&buf, "\treturn c.RoleSees(%q)\n", role.Slug)
		fmt.Fprintf(&buf, "}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("formatting column annotations: %w", err)
	}
	return formatted, nil
}

// SlugToPascal converts a role slug to PascalCase.
// Examples: "compliance" → "Compliance", "support_lead" → "SupportLead"
func SlugToPascal(slug string) string {
	parts := strings.FieldsFunc(slug, func(r rune) bool {
		return r == '_' || r == '-'
	})
	var result strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			result.WriteString(part[1:])
		}
	}
	return result.String()
}
