package generator

import (
	"strings"
	"testing"
)

func TestGenerateCore(t *testing.T) {
	cookedDir := "../../pkg/cooked"
	out, err := GenerateCore(cookedDir, "generated")
	if err != nil {
		t.Fatalf("GenerateCore: %v", err)
	}

	src := string(out)

	// Header
	if !strings.Contains(src, "// Code generated by Pickle. DO NOT EDIT.") {
		t.Error("missing generated header")
	}
	if !strings.Contains(src, "package generated") {
		t.Error("wrong package declaration")
	}

	// Core types should be present
	for _, want := range []string{
		"type Context struct",
		"type Response struct",
		"type Router struct",
		"type Route struct",
		"type MiddlewareFunc func",
		"type Controller struct",
		"type AuthInfo struct",
		"func RunMiddleware(",
		"func Routes(",
		"func NewContext(",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("missing %q in output", want)
		}
	}

	// Should NOT contain query builder or scope templates
	for _, bad := range []string{
		"type QueryBuilder[",
		"pickle:scope",
		"pickle_template",
	} {
		if strings.Contains(src, bad) {
			t.Errorf("output should not contain %q", bad)
		}
	}

	// Should NOT contain test code
	if strings.Contains(src, "func Test") {
		t.Error("output should not contain test functions")
	}

	// Imports should include net/http and encoding/json (used by context/response)
	if !strings.Contains(src, `"net/http"`) {
		t.Error("missing net/http import")
	}
	if !strings.Contains(src, `"encoding/json"`) {
		t.Error("missing encoding/json import")
	}
}

func TestGenerateCoreInvalidDir(t *testing.T) {
	_, err := GenerateCore("/nonexistent/path", "generated")
	if err == nil {
		t.Error("expected error for nonexistent dir")
	}
}
