package generator

import (
	"strings"
	"testing"
)

func TestGenerateCoreHTTP(t *testing.T) {
	src := string(GenerateCoreHTTP("myapp"))

	if !strings.Contains(src, "// Code generated by Pickle. DO NOT EDIT.") {
		t.Error("missing generated header")
	}
	if !strings.Contains(src, "package myapp") {
		t.Error("wrong package declaration")
	}

	for _, want := range []string{
		"type Context struct",
		"type ResourceID struct",
		"type ResourceIDParts struct",
		"type Response struct",
		"type Router struct",
		"type Route struct",
		"type MiddlewareFunc func",
		"type Controller struct",
		"type AuthInfo struct",
		"func RunMiddleware(",
		"func Routes(",
		"func NewContext(",
		"func ParseResourceID(",
		"func (c *Context) ParamResourceID(",
		"func (c *Context) ParamResourceIDParts(",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("missing %q in output", want)
		}
	}

	for _, bad := range []string{
		"type QueryBuilder[",
		"pickle:scope",
		"pickle_template",
	} {
		if strings.Contains(src, bad) {
			t.Errorf("output should not contain %q", bad)
		}
	}
}

func TestGenerateCoreQuery(t *testing.T) {
	src := string(GenerateCoreQuery("models"))

	if !strings.Contains(src, "package models") {
		t.Error("wrong package declaration")
	}
	if !strings.Contains(src, "type QueryBuilder[") {
		t.Error("missing QueryBuilder")
	}
}

func TestGenerateCoreGraphQLIncludesResourceIDScalarRuntime(t *testing.T) {
	src := string(GenerateCoreGraphQL("graphql"))
	for _, want := range []string{
		"type ResourceID struct",
		"func ParseResourceID(",
		"func CoerceResourceIDInput(",
		"func MarshalGraphQLResourceID(",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated GraphQL runtime missing %q", want)
		}
	}
}

func TestGenerateCoreSchema(t *testing.T) {
	src := string(GenerateCoreSchema("migrations"))

	if !strings.Contains(src, "package migrations") {
		t.Error("wrong package declaration")
	}
	if !strings.Contains(src, "type Migration struct") {
		t.Error("missing Migration type")
	}
	if !strings.Contains(src, "type Table struct") {
		t.Error("missing Table type")
	}
	for _, want := range []string{"type ForeignKey struct", "ForeignKeys", "func (t *Table) ForeignKey(", "func (f *ForeignKey) OnUpdate("} {
		if !strings.Contains(src, want) {
			t.Errorf("missing composite foreign-key API %q", want)
		}
	}
	for _, want := range []string{"type SeedSpec struct", "func (c *Column) SeedFirstName(", "func (c *Column) SeedPassword(", "func (t *Table) AlterColumn(", "OpAlterColumnMetadata"} {
		if !strings.Contains(src, want) {
			t.Errorf("missing field-seeder API %q", want)
		}
	}
}

func TestGenerateCoreMigrationCompositeForeignKeysAcrossDrivers(t *testing.T) {
	src := string(GenerateCoreMigration("migrations"))
	for _, want := range []string{
		`FOREIGN KEY (`,
		`ON DELETE `,
		`ON UPDATE `,
		`mysqlQI(fk.Columns[i])`,
		`qi(fk.Columns[i])`,
		`sqliteQI(fk.Columns[i])`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated migration runtime missing %q", want)
		}
	}
}
