package generator

import (
	"strings"
	"testing"
)

func TestGenerateCoreHTTP(t *testing.T) {
	src := string(GenerateCoreHTTP("myapp"))

	if !strings.Contains(src, "// Code generated by Pickle. DO NOT EDIT.") {
		t.Error("missing generated header")
	}
	if !strings.Contains(src, "package myapp") {
		t.Error("wrong package declaration")
	}

	for _, want := range []string{
		"type Context struct",
		"type Response struct",
		"type Router struct",
		"type Route struct",
		"type MiddlewareFunc func",
		"type Controller struct",
		"type AuthInfo struct",
		"func RunMiddleware(",
		"func Routes(",
		"func NewContext(",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("missing %q in output", want)
		}
	}

	for _, bad := range []string{
		"type QueryBuilder[",
		"pickle:scope",
		"pickle_template",
	} {
		if strings.Contains(src, bad) {
			t.Errorf("output should not contain %q", bad)
		}
	}
}

func TestGenerateCoreQuery(t *testing.T) {
	src := string(GenerateCoreQuery("models"))

	if !strings.Contains(src, "package models") {
		t.Error("wrong package declaration")
	}
	if !strings.Contains(src, "type QueryBuilder[") {
		t.Error("missing QueryBuilder")
	}
}

func TestGenerateCoreSchema(t *testing.T) {
	src := string(GenerateCoreSchema("migrations"))

	if !strings.Contains(src, "package migrations") {
		t.Error("wrong package declaration")
	}
	if !strings.Contains(src, "type Migration struct") {
		t.Error("missing Migration type")
	}
	if !strings.Contains(src, "type Table struct") {
		t.Error("missing Table type")
	}
}
