// Code generated by tickle. DO NOT EDIT.
package generator

const embedSCHEMA = `// Code generated by Pickle. DO NOT EDIT.
package __PACKAGE__

// Column represents a database column definition.
type Column struct {
	Name             string
	Type             ColumnType
	Length           int
	Precision        int
	Scale            int
	IsPrimaryKey     bool
	IsNullable       bool
	IsUnique         bool
	DefaultValue     any
	HasDefault       bool
	ForeignKeyTable  string
	ForeignKeyColumn string
}

func (c *Column) PrimaryKey() *Column {
	c.IsPrimaryKey = true
	return c
}

func (c *Column) NotNull() *Column {
	c.IsNullable = false
	return c
}

func (c *Column) Nullable() *Column {
	c.IsNullable = true
	return c
}

func (c *Column) Unique() *Column {
	c.IsUnique = true
	return c
}

func (c *Column) Default(value any) *Column {
	c.DefaultValue = value
	c.HasDefault = true
	return c
}

func (c *Column) ForeignKey(table, column string) *Column {
	c.ForeignKeyTable = table
	c.ForeignKeyColumn = column
	return c
}

// Index represents a database index.
type Index struct {
	Table   string
	Columns []string
	Unique  bool
}

// TableOperation represents a schema change recorded by a migration.
type TableOperation int

const (
	OpCreateTable TableOperation = iota
	OpDropTableIfExists
	OpRenameTable
	OpAddColumn
	OpDropColumn
	OpRenameColumn
	OpAddIndex
	OpAddUniqueIndex
)

// Operation records a single schema change.
type Operation struct {
	Type         TableOperation
	Table        string
	TableDef     *Table
	Index        *Index
	NewName      string // for rename operations
	OldName      string // for rename operations
	ColumnName   string // for drop/rename column
	ColumnDef    func(*Table)
}

// Migration is the base type embedded by all migration structs.
// It records schema operations for later execution or inspection.
type Migration struct {
	Operations []Operation
}

func (m *Migration) CreateTable(name string, fn func(*Table)) {
	t := &Table{Name: name}
	fn(t)
	m.Operations = append(m.Operations, Operation{
		Type:     OpCreateTable,
		Table:    name,
		TableDef: t,
	})
}

func (m *Migration) DropTableIfExists(name string) {
	m.Operations = append(m.Operations, Operation{
		Type:  OpDropTableIfExists,
		Table: name,
	})
}

func (m *Migration) RenameTable(oldName, newName string) {
	m.Operations = append(m.Operations, Operation{
		Type:    OpRenameTable,
		Table:   oldName,
		OldName: oldName,
		NewName: newName,
	})
}

func (m *Migration) AddColumn(table string, fn func(*Table)) {
	m.Operations = append(m.Operations, Operation{
		Type:      OpAddColumn,
		Table:     table,
		ColumnDef: fn,
	})
}

func (m *Migration) DropColumn(table, column string) {
	m.Operations = append(m.Operations, Operation{
		Type:       OpDropColumn,
		Table:      table,
		ColumnName: column,
	})
}

func (m *Migration) RenameColumn(table, oldName, newName string) {
	m.Operations = append(m.Operations, Operation{
		Type:       OpRenameColumn,
		Table:      table,
		ColumnName: oldName,
		OldName:    oldName,
		NewName:    newName,
	})
}

func (m *Migration) AddIndex(table string, columns ...string) {
	m.Operations = append(m.Operations, Operation{
		Type:  OpAddIndex,
		Table: table,
		Index: &Index{
			Table:   table,
			Columns: columns,
			Unique:  false,
		},
	})
}

func (m *Migration) AddUniqueIndex(table string, columns ...string) {
	m.Operations = append(m.Operations, Operation{
		Type:  OpAddUniqueIndex,
		Table: table,
		Index: &Index{
			Table:   table,
			Columns: columns,
			Unique:  true,
		},
	})
}

// Table collects column definitions for a database table.
type Table struct {
	Name    string
	Columns []*Column
}

func (t *Table) addColumn(name string, colType ColumnType) *Column {
	c := &Column{
		Name: name,
		Type: colType,
	}
	t.Columns = append(t.Columns, c)
	return c
}

func (t *Table) UUID(name string) *Column {
	return t.addColumn(name, UUID)
}

func (t *Table) String(name string, length ...int) *Column {
	c := t.addColumn(name, String)
	if len(length) > 0 {
		c.Length = length[0]
	} else {
		c.Length = 255
	}
	return c
}

func (t *Table) Text(name string) *Column {
	return t.addColumn(name, Text)
}

func (t *Table) Integer(name string) *Column {
	return t.addColumn(name, Integer)
}

func (t *Table) BigInteger(name string) *Column {
	return t.addColumn(name, BigInteger)
}

func (t *Table) Decimal(name string, precision, scale int) *Column {
	c := t.addColumn(name, Decimal)
	c.Precision = precision
	c.Scale = scale
	return c
}

func (t *Table) Boolean(name string) *Column {
	return t.addColumn(name, Boolean)
}

func (t *Table) Timestamp(name string) *Column {
	return t.addColumn(name, Timestamp)
}

func (t *Table) JSONB(name string) *Column {
	return t.addColumn(name, JSONB)
}

func (t *Table) Date(name string) *Column {
	return t.addColumn(name, Date)
}

func (t *Table) Time(name string) *Column {
	return t.addColumn(name, Time)
}

func (t *Table) Binary(name string) *Column {
	return t.addColumn(name, Binary)
}

// Timestamps adds created_at and updated_at columns.
func (t *Table) Timestamps() {
	t.addColumn("created_at", Timestamp).NotNull()
	t.addColumn("updated_at", Timestamp).NotNull()
}

// ColumnType represents the data type of a database column.
type ColumnType int

const (
	UUID ColumnType = iota
	String
	Text
	Integer
	BigInteger
	Decimal
	Boolean
	Timestamp
	JSONB
	Date
	Time
	Binary
)

`
