// Code generated by tickle. DO NOT EDIT.
package generator

const embedAUTHSESSION = `// Code generated by Pickle. DO NOT EDIT.
package __PACKAGE__

import (
	"database/sql"
	"errors"
	"net/http"
	"time"
	pickle "github.com/shortontech/pickle/pkg/cooked"
)

// Driver implements session-based authentication using database-backed sessions.
// Sessions are identified by a cookie. The session record is looked up in the
// sessions table and validated for expiry.
type Driver struct {
	db         *sql.DB
	cookieName string
	ttl        int // seconds
}

// NewDriver creates a session auth driver. Config is read from environment:
//   - SESSION_COOKIE: cookie name (default: "session_id")
//   - SESSION_TTL: session lifetime in seconds (default: 86400)
//
func NewDriver(env func(string, string) string, db *sql.DB) *Driver {
	ttl := 86400
	if v := env("SESSION_TTL", ""); v != "" {
		n := 0
		for _, c := range v {
			if c >= '0' && c <= '9' {
				n = n*10 + int(c-'0')
			}
		}
		if n > 0 {
			ttl = n
		}
	}

	return &Driver{
		db:         db,
		cookieName: env("SESSION_COOKIE", "session_id"),
		ttl:        ttl,
	}
}

// Authenticate reads the session cookie, looks up the session in the database,
// and returns AuthInfo on success.
func (d *Driver) Authenticate(r *http.Request) (*pickle.AuthInfo, error) {
	cookie, err := r.Cookie(d.cookieName)
	if err != nil {
		return nil, errors.New("session: missing session cookie")
	}

	if d.db == nil {
		return nil, errors.New("session: database not configured")
	}

	var userID, role string
	var expiresAt time.Time

	err = d.db.QueryRow(
		"SELECT user_id, role, expires_at FROM sessions WHERE id = $1 AND expires_at > NOW()",
		cookie.Value,
	).Scan(&userID, &role, &expiresAt)
	if err == sql.ErrNoRows {
		return nil, errors.New("session: invalid or expired session")
	}
	if err != nil {
		return nil, errors.New("session: database error")
	}

	return &pickle.AuthInfo{
		UserID: userID,
		Role:   role,
	}, nil
}

// TTL returns the configured session lifetime in seconds.
func (d *Driver) TTL() int {
	return d.ttl
}

// CookieName returns the configured session cookie name.
func (d *Driver) CookieName() string {
	return d.cookieName
}

`
