// Code generated by tickle. DO NOT EDIT.
package generator

const embed_2026_03_25_000001_create_graphql_changelog_table = `// Code generated by Pickle. DO NOT EDIT.

package __PACKAGE__

// CreateGraphqlChangelogTable_2026_03_25_000001 creates the graphql_changelog table.
type CreateGraphqlChangelogTable_2026_03_25_000001 struct {
	Migration
}

func (m *CreateGraphqlChangelogTable_2026_03_25_000001) Up() {
	m.CreateTable("graphql_changelog", func(t *Table) {
		t.String("id", 255).PrimaryKey()
		t.Integer("batch").NotNull()
		t.String("state", 20).NotNull()
		t.Text("error").Nullable()
		t.Timestamp("started_at").Nullable()
		t.Timestamp("completed_at").Nullable()
	})
}

func (m *CreateGraphqlChangelogTable_2026_03_25_000001) Down() {
	m.DropTableIfExists("graphql_changelog")
}
`

const embed_2026_03_25_000002_create_graphql_exposures_table = `// Code generated by Pickle. DO NOT EDIT.

package __PACKAGE__

// CreateGraphqlExposuresTable_2026_03_25_000002 creates the graphql_exposures table.
type CreateGraphqlExposuresTable_2026_03_25_000002 struct {
	Migration
}

func (m *CreateGraphqlExposuresTable_2026_03_25_000002) Up() {
	m.CreateTable("graphql_exposures", func(t *Table) {
		t.UUID("id").PrimaryKey().Default("uuid_generate_v7()")
		t.String("model", 100).NotNull()
		t.String("operation", 20).NotNull()
		t.Timestamps()
	})

	m.AddUniqueIndex("graphql_exposures", "model", "operation")
}

func (m *CreateGraphqlExposuresTable_2026_03_25_000002) Down() {
	m.DropTableIfExists("graphql_exposures")
}
`

const embed_2026_03_25_000003_create_graphql_actions_table = `// Code generated by Pickle. DO NOT EDIT.

package __PACKAGE__

// CreateGraphqlActionsTable_2026_03_25_000003 creates the graphql_actions table.
type CreateGraphqlActionsTable_2026_03_25_000003 struct {
	Migration
}

func (m *CreateGraphqlActionsTable_2026_03_25_000003) Up() {
	m.CreateTable("graphql_actions", func(t *Table) {
		t.UUID("id").PrimaryKey().Default("uuid_generate_v7()")
		t.String("name", 100).NotNull().Unique()
		t.Timestamps()
	})
}

func (m *CreateGraphqlActionsTable_2026_03_25_000003) Down() {
	m.DropTableIfExists("graphql_actions")
}
`

