// Code generated by tickle. DO NOT EDIT.
package generator

const embed_2026_03_23_000001_create_roles_table = `// Code generated by Pickle. DO NOT EDIT.

package __PACKAGE__

// CreateRolesTable_2026_03_23_000001 creates the roles table for RBAC.
type CreateRolesTable_2026_03_23_000001 struct {
	Migration
}

func (m *CreateRolesTable_2026_03_23_000001) Up() {
	m.CreateTable("roles", func(t *Table) {
		t.UUID("id").PrimaryKey().Default("uuid_generate_v7()")
		t.String("slug", 50).NotNull().Unique()
		t.String("display_name", 100).NotNull()
		t.Boolean("is_manages").NotNull().Default("false")
		t.Boolean("is_default").NotNull().Default("false")
		t.String("birth_policy", 100).NotNull()
		t.Timestamps()
	})
}

func (m *CreateRolesTable_2026_03_23_000001) Down() {
	m.DropTableIfExists("roles")
}
`

const embed_2026_03_23_000002_create_role_actions_table = `// Code generated by Pickle. DO NOT EDIT.

package __PACKAGE__

// CreateRoleActionsTable_2026_03_23_000002 creates the role_actions table.
type CreateRoleActionsTable_2026_03_23_000002 struct {
	Migration
}

func (m *CreateRoleActionsTable_2026_03_23_000002) Up() {
	m.CreateTable("role_actions", func(t *Table) {
		t.UUID("id").PrimaryKey().Default("uuid_generate_v7()")
		t.String("role_slug", 50).NotNull().ForeignKey("roles", "slug")
		t.String("action", 100).NotNull()
		t.Timestamps()
	})

	m.AddIndex("role_actions", "role_slug")
	m.AddUniqueIndex("role_actions", "role_slug", "action")
}

func (m *CreateRoleActionsTable_2026_03_23_000002) Down() {
	m.DropTableIfExists("role_actions")
}
`

const embed_2026_03_23_000003_create_role_user_table = `// Code generated by Pickle. DO NOT EDIT.

package __PACKAGE__

// CreateRoleUserTable_2026_03_23_000003 creates the role_user pivot table.
type CreateRoleUserTable_2026_03_23_000003 struct {
	Migration
}

func (m *CreateRoleUserTable_2026_03_23_000003) Up() {
	m.CreateTable("role_user", func(t *Table) {
		t.UUID("id").PrimaryKey().Default("uuid_generate_v7()")
		t.UUID("user_id").NotNull().ForeignKey("users", "id")
		t.UUID("role_id").NotNull().ForeignKey("roles", "id")
		t.Timestamps()
	})

	m.AddIndex("role_user", "user_id")
	m.AddIndex("role_user", "role_id")
	m.AddUniqueIndex("role_user", "user_id", "role_id")
}

func (m *CreateRoleUserTable_2026_03_23_000003) Down() {
	m.DropTableIfExists("role_user")
}
`

const embed_2026_03_23_000004_create_rbac_changelog_table = `// Code generated by Pickle. DO NOT EDIT.

package __PACKAGE__

// CreateRbacChangelogTable_2026_03_23_000004 creates the rbac_changelog table.
type CreateRbacChangelogTable_2026_03_23_000004 struct {
	Migration
}

func (m *CreateRbacChangelogTable_2026_03_23_000004) Up() {
	m.CreateTable("rbac_changelog", func(t *Table) {
		t.String("id", 255).PrimaryKey()
		t.Integer("batch").NotNull()
		t.String("state", 20).NotNull()
		t.Text("error").Nullable()
		t.Timestamp("started_at").Nullable()
		t.Timestamp("completed_at").Nullable()
	})
}

func (m *CreateRbacChangelogTable_2026_03_23_000004) Down() {
	m.DropTableIfExists("rbac_changelog")
}
`

