package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateGraphQLDataloaders generates dataloader_gen.go with per-relationship
// batch loaders and a DataLoaderRegistry.
func GenerateGraphQLDataloaders(tables []*schema.Table, relationships []SchemaRelationship, modelsImport, packageName string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	if len(relationships) == 0 {
		// No relationships — empty registry, no imports needed
		b.WriteString("// DataLoaderRegistry holds per-request loader instances.\n")
		b.WriteString("type DataLoaderRegistry struct{}\n\n")
		b.WriteString("func newDataLoaderRegistry() *DataLoaderRegistry {\n\treturn &DataLoaderRegistry{}\n}\n")
		return format.Source(b.Bytes())
	}

	b.WriteString("import (\n")
	b.WriteString(fmt.Sprintf("\t\"%s\"\n", modelsImport))
	b.WriteString("\t\"github.com/google/uuid\"\n")
	b.WriteString(")\n\n")

	// Registry struct
	b.WriteString("// DataLoaderRegistry holds per-request loader instances.\n")
	b.WriteString("type DataLoaderRegistry struct {\n")
	for _, rel := range relationships {
		fkCol := strings.TrimSuffix(rel.ParentTable, "s") + "_id"
		childStruct := tableToStructName(rel.ChildTable)
		loaderField := snakeToCamel(rel.ChildTable) + "By" + snakeToPascal(fkCol)
		switch rel.Type {
		case "has_many":
			b.WriteString(fmt.Sprintf("\t%s *batchLoader[uuid.UUID, []*models.%s]\n", loaderField, childStruct))
		case "has_one":
			b.WriteString(fmt.Sprintf("\t%s *batchLoader[uuid.UUID, *models.%s]\n", loaderField, childStruct))
		}
	}
	b.WriteString("}\n\n")

	// Constructor
	b.WriteString("func newDataLoaderRegistry() *DataLoaderRegistry {\n")
	b.WriteString("\tr := &DataLoaderRegistry{}\n")
	for _, rel := range relationships {
		fkCol := strings.TrimSuffix(rel.ParentTable, "s") + "_id"
		loaderField := snakeToCamel(rel.ChildTable) + "By" + snakeToPascal(fkCol)
		b.WriteString(fmt.Sprintf("\tr.%s = newBatchLoader(r.batch%s)\n", loaderField, snakeToPascal(rel.ChildTable)+"By"+snakeToPascal(fkCol)))
	}
	b.WriteString("\treturn r\n}\n\n")

	// Batch functions and load helpers
	for _, rel := range relationships {
		fkCol := strings.TrimSuffix(rel.ParentTable, "s") + "_id"
		childStruct := tableToStructName(rel.ChildTable)
		loaderField := snakeToCamel(rel.ChildTable) + "By" + snakeToPascal(fkCol)
		batchFn := "batch" + snakeToPascal(rel.ChildTable) + "By" + snakeToPascal(fkCol)
		whereFn := "Where" + snakeToPascal(fkCol) + "In"

		switch rel.Type {
		case "has_many":
			// Load function (called from field resolver)
			b.WriteString(fmt.Sprintf("func (r *RootResolver) load%sList(ctx *ResolveContext, parentID uuid.UUID, selections []Field) (any, error) {\n",
				childStruct+"By"+snakeToPascal(fkCol)))
			b.WriteString(fmt.Sprintf("\trecords, err := ctx.loaders.(*DataLoaderRegistry).%s.load(parentID)\n", loaderField))
			b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			b.WriteString("\tresult := make([]map[string]any, len(records))\n")
			b.WriteString("\tfor i, rec := range records {\n")
			b.WriteString(fmt.Sprintf("\t\tobj, err := r.resolve%sObject(ctx, rec, selections)\n", childStruct))
			b.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
			b.WriteString("\t\tresult[i] = obj\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn result, nil\n}\n\n")

			// Batch function
			b.WriteString(fmt.Sprintf("func (r *DataLoaderRegistry) %s(ids []uuid.UUID) []batchResult[[]*models.%s] {\n", batchFn, childStruct))
			b.WriteString(fmt.Sprintf("\trecords, err := models.Query%s().%s(ids...).All()\n", childStruct, whereFn))
			b.WriteString(fmt.Sprintf("\tresults := make([]batchResult[[]*models.%s], len(ids))\n", childStruct))
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\tfor i := range results {\n")
			b.WriteString(fmt.Sprintf("\t\t\tresults[i] = batchResult[[]*models.%s]{err: err}\n", childStruct))
			b.WriteString("\t\t}\n\t\treturn results\n\t}\n\n")
			b.WriteString(fmt.Sprintf("\tgrouped := make(map[uuid.UUID][]*models.%s)\n", childStruct))
			b.WriteString(fmt.Sprintf("\tfor i := range records {\n"))
			b.WriteString(fmt.Sprintf("\t\tgrouped[records[i].%s] = append(grouped[records[i].%s], &records[i])\n",
				snakeToPascal(fkCol), snakeToPascal(fkCol)))
			b.WriteString("\t}\n")
			b.WriteString("\tfor i, id := range ids {\n")
			b.WriteString(fmt.Sprintf("\t\tresults[i] = batchResult[[]*models.%s]{val: grouped[id]}\n", childStruct))
			b.WriteString("\t}\n\treturn results\n}\n\n")

		case "has_one":
			// Load function
			b.WriteString(fmt.Sprintf("func (r *RootResolver) load%s(ctx *ResolveContext, parentID uuid.UUID, selections []Field) (any, error) {\n",
				childStruct+"By"+snakeToPascal(fkCol)))
			b.WriteString(fmt.Sprintf("\trecord, err := ctx.loaders.(*DataLoaderRegistry).%s.load(parentID)\n", loaderField))
			b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			b.WriteString("\tif record == nil {\n\t\treturn nil, nil\n\t}\n")
			b.WriteString(fmt.Sprintf("\treturn r.resolve%sObject(ctx, record, selections)\n", childStruct))
			b.WriteString("}\n\n")

			// Batch function
			b.WriteString(fmt.Sprintf("func (r *DataLoaderRegistry) %s(ids []uuid.UUID) []batchResult[*models.%s] {\n", batchFn, childStruct))
			b.WriteString(fmt.Sprintf("\trecords, err := models.Query%s().%s(ids...).All()\n", childStruct, whereFn))
			b.WriteString(fmt.Sprintf("\tresults := make([]batchResult[*models.%s], len(ids))\n", childStruct))
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\tfor i := range results {\n")
			b.WriteString(fmt.Sprintf("\t\t\tresults[i] = batchResult[*models.%s]{err: err}\n", childStruct))
			b.WriteString("\t\t}\n\t\treturn results\n\t}\n\n")
			b.WriteString(fmt.Sprintf("\tbyKey := make(map[uuid.UUID]*models.%s)\n", childStruct))
			b.WriteString(fmt.Sprintf("\tfor i := range records {\n"))
			b.WriteString(fmt.Sprintf("\t\tbyKey[records[i].%s] = &records[i]\n", snakeToPascal(fkCol)))
			b.WriteString("\t}\n")
			b.WriteString("\tfor i, id := range ids {\n")
			b.WriteString(fmt.Sprintf("\t\tresults[i] = batchResult[*models.%s]{val: byKey[id]}\n", childStruct))
			b.WriteString("\t}\n\treturn results\n}\n\n")
		}
	}

	return format.Source(b.Bytes())
}
