package generator

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateGraphQLTypes generates types_gen.go containing GQL response structs,
// connection types, and input structs.
func GenerateGraphQLTypes(tables []*schema.Table, packageName string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// GQL response types
	for _, tbl := range tables {
		structName := tableToStructName(tbl.Name)
		b.WriteString(fmt.Sprintf("// %sGQL is the GraphQL response type for %s.\n", structName, structName))
		b.WriteString(fmt.Sprintf("type %sGQL struct {\n", structName))
		for _, col := range tbl.Columns {
			if isExcludedFromGraphQL(col) {
				continue
			}
			goType := graphqlGoSerType(col)
			if goType == "" {
				continue
			}
			fieldName := snakeToPascal(col.Name)
			jsonTag := snakeToCamel(col.Name)
			if col.IsNullable {
				goType = "*" + goType
				jsonTag += ",omitempty"
			}
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, jsonTag))
		}
		b.WriteString("}\n\n")
	}

	// Connection types
	b.WriteString("// PageInfo holds pagination metadata.\n")
	b.WriteString("type PageInfoGQL struct {\n")
	b.WriteString("\tHasNextPage     bool    `json:\"hasNextPage\"`\n")
	b.WriteString("\tHasPreviousPage bool    `json:\"hasPreviousPage\"`\n")
	b.WriteString("\tStartCursor     *string `json:\"startCursor\"`\n")
	b.WriteString("\tEndCursor       *string `json:\"endCursor\"`\n")
	b.WriteString("}\n\n")

	// Input types
	for _, tbl := range tables {
		if tbl.IsImmutable {
			continue
		}
		structName := tableToStructName(tbl.Name)

		// CreateInput
		b.WriteString(fmt.Sprintf("// Create%sInput is the GraphQL input for creating a %s.\n", structName, structName))
		b.WriteString(fmt.Sprintf("type Create%sInput struct {\n", structName))
		for _, col := range tbl.Columns {
			if isExcludedFromInput(col) {
				continue
			}
			goType := graphqlGoSerType(col)
			if goType == "" {
				continue
			}
			fieldName := snakeToPascal(col.Name)
			jsonTag := snakeToCamel(col.Name)
			// Optional fields with defaults
			if col.IsNullable || col.DefaultValue != nil {
				goType = "*" + goType
				jsonTag += ",omitempty"
			}
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, jsonTag))
		}
		b.WriteString("}\n\n")

		// UpdateInput (all fields are pointers)
		if !tbl.IsAppendOnly {
			b.WriteString(fmt.Sprintf("// Update%sInput is the GraphQL input for updating a %s.\n", structName, structName))
			b.WriteString(fmt.Sprintf("type Update%sInput struct {\n", structName))
			for _, col := range tbl.Columns {
				if isExcludedFromInput(col) {
					continue
				}
				goType := graphqlGoSerType(col)
				if goType == "" {
					continue
				}
				fieldName := snakeToPascal(col.Name)
				jsonTag := snakeToCamel(col.Name) + ",omitempty"
				b.WriteString(fmt.Sprintf("\t%s *%s `json:\"%s\"`\n", fieldName, goType, jsonTag))
			}
			b.WriteString("}\n\n")
		}
	}

	return format.Source(b.Bytes())
}
