package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateGraphQLSchema generates schema_gen.go containing the SDL string constant
// and the parsed schema variable.
func GenerateGraphQLSchema(tables []*schema.Table, relationships []SchemaRelationship, requests []RequestDef, packageName string) ([]byte, error) {
	return GenerateGraphQLSchemaWithPlans(legacyGraphQLModelPlans(tables), relationships, requests, packageName)
}

// GenerateGraphQLSchemaWithPlans generates schema_gen.go using exact
// operation-level exposure plans.
func GenerateGraphQLSchemaWithPlans(plans []GraphQLModelPlan, relationships []SchemaRelationship, requests []RequestDef, packageName string) ([]byte, error) {
	sdl := BuildSDLWithPlans(plans, relationships, requests)

	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/vektah/gqlparser/v2\"\n")
	b.WriteString("\t\"github.com/vektah/gqlparser/v2/ast\"\n")
	b.WriteString(")\n\n")
	b.WriteString(fmt.Sprintf("// SchemaSDL is the GraphQL schema as an SDL string, embedded at compile time.\nconst SchemaSDL = %s\n\n", quoteSDL(sdl)))
	b.WriteString("// parsedSchema is compiled once at init from SchemaSDL.\n")
	b.WriteString("var parsedSchema *ast.Schema = gqlparser.MustLoadSchema(&ast.Source{\n")
	b.WriteString("\tName:  \"schema.graphql\",\n")
	b.WriteString("\tInput: SchemaSDL,\n")
	b.WriteString("})\n")

	return format.Source(b.Bytes())
}

func quoteSDL(s string) string {
	if !strings.Contains(s, "`") {
		return "`\n" + s + "`"
	}
	return fmt.Sprintf("%q", s)
}

// BuildSDL constructs the GraphQL SDL string from tables, relationships, and requests.
func BuildSDL(tables []*schema.Table, relationships []SchemaRelationship, requests []RequestDef) string {
	return BuildSDLWithPlans(legacyGraphQLModelPlans(tables), relationships, requests)
}

// BuildSDLWithPlans constructs SDL from operation-level model plans.
func BuildSDLWithPlans(plans []GraphQLModelPlan, relationships []SchemaRelationship, requests []RequestDef) string {
	var tables []*schema.Table
	for _, plan := range plans {
		if plan.Table != nil {
			tables = append(tables, plan.Table)
		}
	}
	relationships = graphQLRelationshipsForPlans(plans, relationships)
	exposedTables := tableSetFromPlans(plans)

	// Build relationship lookup
	relByParent := map[string][]SchemaRelationship{}
	for _, rel := range relationships {
		if !exposedTables[rel.ParentTable] || !exposedTables[rel.ChildTable] {
			continue
		}
		relByParent[rel.ParentTable] = append(relByParent[rel.ParentTable], rel)
	}

	var b strings.Builder

	// Custom scalars
	b.WriteString("scalar DateTime\n\n")
	if HasResourceIDFields(requests) {
		b.WriteString("scalar ResourceID\n\n")
	}

	// Auth directives
	b.WriteString("directive @public on FIELD_DEFINITION\n")
	b.WriteString("directive @auth on FIELD_DEFINITION\n")
	b.WriteString("directive @ownerOnly on FIELD_DEFINITION\n")
	b.WriteString("directive @requireRole(roles: [String!]!) on FIELD_DEFINITION\n\n")

	// Object types
	for _, tbl := range tables {
		writeObjectType(&b, tbl, relByParent[tbl.Name])
	}

	// Input types for filters
	for _, tbl := range tables {
		writeFilterType(&b, tbl)
		writeSortEnum(&b, tbl)
	}

	// Shared filter input types
	writeSharedFilterTypes(&b)

	// Pagination types
	writePaginationTypes(&b)

	// Connection types per table
	for _, tbl := range tables {
		writeConnectionType(&b, tbl)
	}

	// Query root
	writeQueryTypeWithPlans(&b, plans)

	// Mutation root (includes nested mutations from relationships)
	if len(relationships) > 0 {
		writeMutationTypeWithNestingAndPlans(&b, plans, relationships)
	} else {
		writeMutationTypeWithPlans(&b, plans)
	}

	// Enums from oneof= validation tags
	enums := ExtractEnums(requests)
	for _, e := range enums {
		b.WriteString(fmt.Sprintf("enum %s {\n", e.Name))
		for _, v := range e.Values {
			b.WriteString(fmt.Sprintf("  %s\n", v))
		}
		b.WriteString("}\n\n")
	}

	// Input types for mutations
	enumFields := EnumFieldMap(requests)
	for _, tbl := range tables {
		writeInputTypes(&b, tbl, enumFields)
	}

	return b.String()
}

func writeObjectType(b *strings.Builder, tbl *schema.Table, rels []SchemaRelationship) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("type %s {\n", structName))

	for _, col := range tbl.Columns {
		if isExcludedFromGraphQL(tbl, col) {
			continue
		}
		gqlType := graphqlType(col)
		if gqlType == "" {
			continue
		}
		nullable := graphqlNullable(col)
		fieldName := snakeToCamel(col.Name)

		// Apply auth directive based on visibility annotation
		var directive string
		if col.IsPublic {
			directive = " @public"
		} else if col.IsOwnerSees {
			directive = " @ownerOnly"
		} else {
			directive = " @auth"
		}

		b.WriteString(fmt.Sprintf("  %s: %s%s%s\n", fieldName, gqlType, nullable, directive))
	}

	// Relationship fields
	for _, rel := range rels {
		childStruct := tableToStructName(rel.ChildTable)
		fieldName := snakeToCamel(rel.ChildTable)
		switch rel.Type {
		case "has_many":
			b.WriteString(fmt.Sprintf("  %s: [%s!]! @auth\n", fieldName, childStruct))
		case "has_one":
			b.WriteString(fmt.Sprintf("  %s: %s @auth\n", fieldName, childStruct))
		}
	}

	b.WriteString("}\n\n")
}

func writeFilterType(b *strings.Builder, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("input %sFilter {\n", structName))
	for _, col := range tbl.Columns {
		if isExcludedFromGraphQL(tbl, col) {
			continue
		}
		gqlType := graphqlType(col)
		if gqlType == "" {
			continue
		}
		fieldName := snakeToCamel(col.Name)
		filterType := filterTypeForGraphQL(gqlType)
		if filterType != "" {
			b.WriteString(fmt.Sprintf("  %s: %s\n", fieldName, filterType))
		}
	}
	b.WriteString("}\n\n")
}

func filterTypeForGraphQL(gqlType string) string {
	switch gqlType {
	case "ID":
		return "IDFilter"
	case "String":
		return "StringFilter"
	case "Int":
		return "IntFilter"
	case "Boolean":
		return "BooleanFilter"
	case "DateTime":
		return "DateTimeFilter"
	default:
		return "StringFilter"
	}
}

func writeSortEnum(b *strings.Builder, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("enum %sSort {\n", structName))
	for _, col := range tbl.Columns {
		if isExcludedFromGraphQL(tbl, col) || !isSortableGraphQLColumn(col) {
			continue
		}
		gqlType := graphqlType(col)
		if gqlType == "" {
			continue
		}
		upper := strings.ToUpper(col.Name)
		b.WriteString(fmt.Sprintf("  %s_ASC\n", upper))
		b.WriteString(fmt.Sprintf("  %s_DESC\n", upper))
	}
	b.WriteString("}\n\n")
}

func isSortableGraphQLColumn(col *schema.Column) bool {
	if col == nil {
		return false
	}
	return !col.IsEncrypted && !col.IsSealed
}

func writeSharedFilterTypes(b *strings.Builder) {
	b.WriteString(`input IDFilter {
  eq: ID
  in: [ID!]
}

input StringFilter {
  eq: String
  like: String
  in: [String!]
}

input IntFilter {
  eq: Int
  gt: Int
  gte: Int
  lt: Int
  lte: Int
  in: [Int!]
}

input BooleanFilter {
  eq: Boolean
}

input DateTimeFilter {
  gt: DateTime
  gte: DateTime
  lt: DateTime
  lte: DateTime
}

`)
}

func writePaginationTypes(b *strings.Builder) {
	b.WriteString(`input PageInput {
  first: Int
  after: String
  last: Int
  before: String
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

`)
}

func writeConnectionType(b *strings.Builder, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("type %sConnection {\n", structName))
	b.WriteString(fmt.Sprintf("  edges: [%sEdge!]!\n", structName))
	b.WriteString("  pageInfo: PageInfo!\n")
	b.WriteString("  totalCount: Int!\n")
	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("type %sEdge {\n", structName))
	b.WriteString(fmt.Sprintf("  node: %s!\n", structName))
	b.WriteString("  cursor: String!\n")
	b.WriteString("}\n\n")
}

func writeQueryType(b *strings.Builder, tables []*schema.Table) {
	writeQueryTypeWithPlans(b, legacyGraphQLModelPlans(tables))
}

func writeQueryTypeWithPlans(b *strings.Builder, plans []GraphQLModelPlan) {
	b.WriteString("type Query {\n")
	for _, plan := range plans {
		tbl := plan.Table
		if tbl == nil {
			continue
		}
		structName := tableToStructName(tbl.Name)
		plural := snakeToCamel(tbl.Name)
		singular := snakeToCamel(strings.TrimSuffix(tbl.Name, "s"))

		if operationAllowed(plan, "list") {
			b.WriteString(fmt.Sprintf("  %s(filter: %sFilter, sort: %sSort, page: PageInput): %sConnection!\n",
				plural, structName, structName, structName))
		}
		if operationAllowed(plan, "show") {
			b.WriteString(fmt.Sprintf("  %s(id: ID!): %s\n", singular, structName))
		}
	}
	b.WriteString("}\n\n")
}

func writeMutationType(b *strings.Builder, tables []*schema.Table) {
	writeMutationTypeWithPlans(b, legacyGraphQLModelPlans(tables))
}

func writeMutationTypeWithPlans(b *strings.Builder, plans []GraphQLModelPlan) {
	var fields strings.Builder
	for _, plan := range plans {
		tbl := plan.Table
		if tbl == nil {
			continue
		}
		structName := tableToStructName(tbl.Name)

		if !tbl.IsImmutable {
			if operationAllowed(plan, "create") {
				fields.WriteString(fmt.Sprintf("  create%s(input: Create%sInput!): %s! @auth\n", structName, structName, structName))
			}
			if operationAllowed(plan, "update") && !tbl.IsAppendOnly {
				fields.WriteString(fmt.Sprintf("  update%s(id: ID!, input: Update%sInput!): %s! @auth\n", structName, structName, structName))
			}
			if operationAllowed(plan, "delete") {
				fields.WriteString(fmt.Sprintf("  delete%s(id: ID!): Boolean! @auth\n", structName))
			}
		}
	}
	if fields.Len() == 0 {
		return
	}
	b.WriteString("type Mutation {\n")
	b.WriteString(fields.String())
	b.WriteString("}\n\n")
}

// writeMutationTypeWithNesting writes the Mutation type including nested resource mutations.
// This is used when relationships are present to add parent-scoped create mutations.
func writeMutationTypeWithNesting(b *strings.Builder, tables []*schema.Table, relationships []SchemaRelationship) {
	writeMutationTypeWithNestingAndPlans(b, legacyGraphQLModelPlans(tables), relationships)
}

func writeMutationTypeWithNestingAndPlans(b *strings.Builder, plans []GraphQLModelPlan, relationships []SchemaRelationship) {
	childToParent := map[string]SchemaRelationship{}
	for _, rel := range relationships {
		childToParent[rel.ChildTable] = rel
	}

	var fields strings.Builder
	for _, plan := range plans {
		tbl := plan.Table
		if tbl == nil {
			continue
		}
		structName := tableToStructName(tbl.Name)

		if !tbl.IsImmutable {
			if operationAllowed(plan, "create") {
				fields.WriteString(fmt.Sprintf("  create%s(input: Create%sInput!): %s! @auth\n", structName, structName, structName))
			}
			if operationAllowed(plan, "update") && !tbl.IsAppendOnly {
				fields.WriteString(fmt.Sprintf("  update%s(id: ID!, input: Update%sInput!): %s! @auth\n", structName, structName, structName))
			}
			if operationAllowed(plan, "delete") {
				fields.WriteString(fmt.Sprintf("  delete%s(id: ID!): Boolean! @auth\n", structName))
			}

			// Nested create mutation if this table is a child
			if operationAllowed(plan, "create") {
				rel, ok := childToParent[tbl.Name]
				if !ok {
					continue
				}
				parentSingular := strings.TrimSuffix(rel.ParentTable, "s")
				parentArgName := snakeToCamel(parentSingular) + "Id"
				fields.WriteString(fmt.Sprintf("  createNested%s(%s: ID!, input: Create%sInput!): %s! @auth\n",
					structName, parentArgName, structName, structName))
			}
		}
	}
	if fields.Len() == 0 {
		return
	}
	b.WriteString("type Mutation {\n")
	b.WriteString(fields.String())
	b.WriteString("}\n\n")
}

func writeInputTypes(b *strings.Builder, tbl *schema.Table, enumFields map[string]string) {
	if tbl.IsImmutable {
		return
	}

	structName := tableToStructName(tbl.Name)

	// CreateInput
	createInputName := "Create" + structName + "Input"
	b.WriteString(fmt.Sprintf("input %s {\n", createInputName))
	for _, col := range tbl.Columns {
		if isExcludedFromInput(col) {
			continue
		}
		gqlType := graphqlType(col)
		if gqlType == "" {
			continue
		}
		fieldName := snakeToCamel(col.Name)
		goFieldName := snakeToPascal(col.Name)
		// Use enum type if available
		if enumType, ok := enumFields[createInputName+"."+goFieldName]; ok {
			gqlType = enumType
		}
		// Required if NOT NULL without a default
		if !col.IsNullable && col.DefaultValue == nil {
			b.WriteString(fmt.Sprintf("  %s: %s!\n", fieldName, gqlType))
		} else {
			b.WriteString(fmt.Sprintf("  %s: %s\n", fieldName, gqlType))
		}
	}
	b.WriteString("}\n\n")

	// UpdateInput (all fields optional)
	if !tbl.IsAppendOnly {
		updateInputName := "Update" + structName + "Input"
		b.WriteString(fmt.Sprintf("input %s {\n", updateInputName))
		for _, col := range tbl.Columns {
			if isExcludedFromInput(col) {
				continue
			}
			gqlType := graphqlType(col)
			if gqlType == "" {
				continue
			}
			fieldName := snakeToCamel(col.Name)
			goFieldName := snakeToPascal(col.Name)
			if enumType, ok := enumFields[updateInputName+"."+goFieldName]; ok {
				gqlType = enumType
			}
			b.WriteString(fmt.Sprintf("  %s: %s\n", fieldName, gqlType))
		}
		b.WriteString("}\n\n")
	}
}

func isExcludedFromInput(col *schema.Column) bool {
	// Exclude PKs, timestamps, FKs (set via nesting), and internal columns
	if col.IsPrimaryKey {
		return true
	}
	if col.Name == "created_at" || col.Name == "updated_at" || col.Name == "deleted_at" {
		return true
	}
	if col.Name == "row_hash" || col.Name == "prev_hash" || col.Name == "version_id" {
		return true
	}
	if col.Type == schema.Binary {
		return true
	}
	if col.Name == "password_hash" || col.Name == "password" {
		return true
	}
	return false
}

// snakeToCamel converts snake_case to camelCase (first letter lowercase).
func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
