package generator

import (
	"bytes"
	"fmt"
	"go/format"
)

// GenerateGraphQLHandler generates handler_gen.go with the net/http handler
// that bridges pickle auth context to GraphQL and uses structured error mapping.
func GenerateGraphQLHandler(packageName string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	b.WriteString(`import (
	"encoding/json"
	"fmt"
	"net/http"
)

// Handler returns a net/http handler for the GraphQL endpoint.
// Mount it at /graphql in your routes or main.go.
//
// The handler extracts auth from the pickle context if present,
// bridging the existing pickle HTTP auth middleware to GraphQL resolvers.
func Handler() http.Handler {
	root := &RootResolver{}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// SDL endpoint for tooling
		if r.Method == http.MethodGet && r.URL.Query().Get("sdl") != "" {
			w.Header().Set("Content-Type", "text/plain")
			w.Write([]byte(SchemaSDL))
			return
		}

		// Parse request body
		var body struct {
			Query         string         ` + "`" + `json:"query"` + "`" + `
			OperationName string         ` + "`" + `json:"operationName"` + "`" + `
			Variables     map[string]any ` + "`" + `json:"variables"` + "`" + `
		}
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			writeError(w, "invalid JSON", "GRAPHQL_PARSE_FAILED")
			return
		}

		// Build resolve context — extract auth from request
		auth := extractAuth(r)
		ctx := &ResolveContext{
			auth:      auth,
			variables: body.Variables,
		}
		ctx.loaders = newDataLoaderRegistry(ctx.Visibility())

		// Parse and validate against schema
		doc, err := parseDocument(parsedSchema, body.Query)
		if err != nil {
			writeError(w, err.Error(), "GRAPHQL_PARSE_FAILED")
			return
		}
		doc.Variables = body.Variables

		// Introspection control
		if !allowIntrospection {
			for _, f := range doc.Fields {
				if isIntrospectionField(f.Name) {
					writeError(w, "introspection is disabled", CodeForbidden)
					return
				}
			}
		}

		// Query depth limiting
		if depth := queryDepth(doc.Fields); depth > maxQueryDepth {
			writeError(w, fmt.Sprintf("query depth %d exceeds maximum %d", depth, maxQueryDepth), CodeBadUserInput)
			return
		}

		data, gqlErrs := execute(ctx, root, doc)

		w.Header().Set("Content-Type", "application/json")
		resp := map[string]any{"data": data}
		if len(gqlErrs) > 0 {
			resp["errors"] = gqlErrs
		}
		json.NewEncoder(w).Encode(resp)
	})
}
`)

	return format.Source(b.Bytes())
}
