package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateGraphQLResolvers generates resolver_gen.go with query dispatch,
// per-type field resolvers, and object resolution helpers.
func GenerateGraphQLResolvers(tables []*schema.Table, relationships []SchemaRelationship, modelsImport, packageName string) ([]byte, error) {
	relByParent := map[string][]SchemaRelationship{}
	for _, rel := range relationships {
		relByParent[rel.ParentTable] = append(relByParent[rel.ParentTable], rel)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"time\"\n\n")
	b.WriteString(fmt.Sprintf("\t\"%s\"\n", modelsImport))
	b.WriteString("\t\"github.com/google/uuid\"\n")
	b.WriteString(")\n\n")

	// Ensure imports are used
	b.WriteString("var _ = time.RFC3339\n")
	b.WriteString("var _ = uuid.Nil\n\n")

	// RootResolver dispatches GraphQL operations.
	b.WriteString("// RootResolver dispatches GraphQL queries and mutations.\n")
	b.WriteString("type RootResolver struct{}\n\n")

	// Query dispatch
	b.WriteString("func (r *RootResolver) resolveQuery(ctx *ResolveContext, field Field) (any, error) {\n")
	b.WriteString("\tswitch field.Name {\n")
	for _, tbl := range tables {
		plural := snakeToCamel(tbl.Name)
		singular := snakeToCamel(strings.TrimSuffix(tbl.Name, "s"))
		b.WriteString(fmt.Sprintf("\tcase \"%s\":\n\t\treturn r.query%s(ctx, field)\n", plural, tableToStructName(tbl.Name)+"List"))
		b.WriteString(fmt.Sprintf("\tcase \"%s\":\n\t\treturn r.query%s(ctx, field)\n", singular, tableToStructName(tbl.Name)))
	}
	b.WriteString("\tdefault:\n\t\treturn nil, fmt.Errorf(\"unknown query field: %s\", field.Name)\n")
	b.WriteString("\t}\n}\n\n")

	// Per-table query resolvers
	for _, tbl := range tables {
		writeListResolver(&b, tbl)
		writeSingleResolver(&b, tbl)
		writeObjectResolver(&b, tbl, relByParent[tbl.Name])
		writeFieldResolver(&b, tbl, relByParent[tbl.Name])
	}

	return format.Source(b.Bytes())
}

func writeListResolver(b *bytes.Buffer, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("func (r *RootResolver) query%sList(ctx *ResolveContext, field Field) (any, error) {\n", structName))
	b.WriteString(fmt.Sprintf("\tq := models.Query%s()\n\n", structName))

	// Visibility (only for tables with annotations)
	if hasVisibilityAnnotations(tbl) {
		b.WriteString("\tswitch ctx.Visibility() {\n")
		b.WriteString("\tcase VisibilityPublic:\n\t\tq.SelectPublic()\n")
		b.WriteString("\tcase VisibilityOwner:\n\t\tq.SelectOwner()\n")
		b.WriteString("\t}\n\n")
	}

	// Pagination
	b.WriteString("\tpage := extractPage(field.Args)\n")
	b.WriteString("\tq.Limit(page.First + 1)\n")
	b.WriteString("\tif page.After != \"\" {\n")
	b.WriteString("\t\tq.Offset(decodeCursor(page.After))\n")
	b.WriteString("\t}\n\n")

	b.WriteString(fmt.Sprintf("\trecords, err := q.All()\n"))
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")

	b.WriteString("\thasNext := len(records) > page.First\n")
	b.WriteString("\tif hasNext {\n\t\trecords = records[:page.First]\n\t}\n\n")

	b.WriteString("\tnodeSelections := selectionsFor(field.Selections, \"edges\", \"node\")\n")
	b.WriteString("\tedges := make([]map[string]any, len(records))\n")
	b.WriteString("\tfor i := range records {\n")
	b.WriteString(fmt.Sprintf("\t\tnode, err := r.resolve%sObject(ctx, &records[i], nodeSelections)\n", structName))
	b.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
	b.WriteString("\t\tedges[i] = map[string]any{\n")
	b.WriteString("\t\t\t\"node\":   node,\n")
	b.WriteString("\t\t\t\"cursor\": encodeCursor(page.Offset + i),\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\treturn map[string]any{\n")
	b.WriteString("\t\t\"edges\": edges,\n")
	b.WriteString("\t\t\"pageInfo\": map[string]any{\n")
	b.WriteString("\t\t\t\"hasNextPage\":     hasNext,\n")
	b.WriteString("\t\t\t\"hasPreviousPage\": page.Offset > 0,\n")
	b.WriteString("\t\t},\n")
	b.WriteString("\t\t\"totalCount\": len(edges),\n")
	b.WriteString("\t}, nil\n")
	b.WriteString("}\n\n")
}

func writeSingleResolver(b *bytes.Buffer, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	fieldName := snakeToCamel(strings.TrimSuffix(tbl.Name, "s"))
	pk := pkColumn(tbl)
	pkMethodName := "Where" + snakeToPascal(pk.Name)

	b.WriteString(fmt.Sprintf("func (r *RootResolver) query%s(ctx *ResolveContext, field Field) (any, error) {\n", structName))
	b.WriteString("\tidStr, ok := field.Args[\"id\"].(string)\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"%s: id argument required\")\n", fieldName))
	b.WriteString("\t}\n")

	parseExpr, needsErr := pkParseExpr(tbl, "idStr")
	if needsErr {
		b.WriteString(fmt.Sprintf("\tid, err := %s\n", parseExpr))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"%s: invalid id\")\n", fieldName))
		b.WriteString("\t}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("\tid := %s\n\n", parseExpr))
	}

	b.WriteString(fmt.Sprintf("\tq := models.Query%s().%s(id)\n", structName, pkMethodName))
	if hasVisibilityAnnotations(tbl) {
		b.WriteString("\tswitch ctx.Visibility() {\n")
		b.WriteString("\tcase VisibilityPublic:\n\t\tq.SelectPublic()\n")
		b.WriteString("\tcase VisibilityOwner:\n\t\tq.SelectOwner()\n")
		b.WriteString("\t}\n\n")
	}
	b.WriteString(fmt.Sprintf("\trecord, err := q.First()\n"))
	b.WriteString("\tif err != nil {\n\t\treturn nil, nil\n\t}\n\n")
	b.WriteString(fmt.Sprintf("\treturn r.resolve%sObject(ctx, record, field.Selections)\n", structName))
	b.WriteString("}\n\n")
}

func writeObjectResolver(b *bytes.Buffer, tbl *schema.Table, rels []SchemaRelationship) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("func (r *RootResolver) resolve%sObject(ctx *ResolveContext, record *models.%s, selections []Field) (map[string]any, error) {\n", structName, structName))
	b.WriteString("\tresult := make(map[string]any, len(selections))\n")
	b.WriteString("\tfor _, f := range selections {\n")
	b.WriteString("\t\talias := f.Alias\n")
	b.WriteString("\t\tif alias == \"\" {\n\t\t\talias = f.Name\n\t\t}\n")
	b.WriteString(fmt.Sprintf("\t\tval, err := r.resolve%sField(ctx, record, f)\n", structName))
	b.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
	b.WriteString("\t\tresult[alias] = val\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn result, nil\n")
	b.WriteString("}\n\n")
}

func writeFieldResolver(b *bytes.Buffer, tbl *schema.Table, rels []SchemaRelationship) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("func (r *RootResolver) resolve%sField(ctx *ResolveContext, record *models.%s, field Field) (any, error) {\n", structName, structName))
	b.WriteString("\tswitch field.Name {\n")

	// __typename
	b.WriteString(fmt.Sprintf("\tcase \"__typename\":\n\t\treturn \"%s\", nil\n", structName))

	for _, col := range tbl.Columns {
		if isExcludedFromGraphQL(col) {
			continue
		}
		gqlType := graphqlType(col)
		if gqlType == "" {
			continue
		}
		fieldName := snakeToCamel(col.Name)
		goFieldName := snakeToPascal(col.Name)

		b.WriteString(fmt.Sprintf("\tcase \"%s\":\n", fieldName))

		// Visibility gate
		if col.IsOwnerSees {
			// Need to find the owner column to get the owner ID
			ownerField := findOwnerField(tbl)
			if ownerField != "" {
				b.WriteString(fmt.Sprintf("\t\tif !ctx.CanSeeOwnerFields(record.%s.String()) {\n\t\t\treturn nil, nil\n\t\t}\n", ownerField))
			} else {
				b.WriteString("\t\tif !ctx.IsAuthenticated() {\n\t\t\treturn nil, nil\n\t\t}\n")
			}
		} else if !col.IsPublic && !col.IsPrimaryKey {
			b.WriteString("\t\tif !ctx.IsAuthenticated() {\n\t\t\treturn nil, nil\n\t\t}\n")
		}

		// Value conversion
		switch col.Type {
		case schema.UUID:
			b.WriteString(fmt.Sprintf("\t\treturn record.%s.String(), nil\n", goFieldName))
		case schema.Timestamp:
			if col.IsNullable {
				b.WriteString(fmt.Sprintf("\t\tif record.%s == nil {\n\t\t\treturn nil, nil\n\t\t}\n", goFieldName))
				b.WriteString(fmt.Sprintf("\t\treturn record.%s.Format(time.RFC3339), nil\n", goFieldName))
			} else {
				b.WriteString(fmt.Sprintf("\t\treturn record.%s.Format(time.RFC3339), nil\n", goFieldName))
			}
		case schema.Decimal:
			b.WriteString(fmt.Sprintf("\t\treturn record.%s.String(), nil\n", goFieldName))
		default:
			b.WriteString(fmt.Sprintf("\t\treturn record.%s, nil\n", goFieldName))
		}
	}

	// Relationship fields
	for _, rel := range rels {
		childCamel := snakeToCamel(rel.ChildTable)
		childStruct := tableToStructName(rel.ChildTable)
		b.WriteString(fmt.Sprintf("\tcase \"%s\":\n", childCamel))
		// Use dataloader
		fkCol := findFKColumn(tbl.Name, rel.ChildTable)
		if fkCol == "" {
			fkCol = strings.TrimSuffix(tbl.Name, "s") + "_id"
		}
		switch rel.Type {
		case "has_many":
			b.WriteString(fmt.Sprintf("\t\treturn r.load%sBy%s(ctx, record.ID, field.Selections)\n",
				childStruct+"List", snakeToPascal(fkCol)))
		case "has_one":
			b.WriteString(fmt.Sprintf("\t\treturn r.load%sBy%s(ctx, record.ID, field.Selections)\n",
				childStruct, snakeToPascal(fkCol)))
		}
	}

	b.WriteString(fmt.Sprintf("\tdefault:\n\t\treturn nil, fmt.Errorf(\"unknown field %s.%%s\", field.Name)\n", structName))
	b.WriteString("\t}\n}\n\n")
}

func findOwnerField(tbl *schema.Table) string {
	for _, col := range tbl.Columns {
		if col.IsOwnerColumn {
			return snakeToPascal(col.Name)
		}
	}
	// If table has ID and the IsOwner is on ID itself
	for _, col := range tbl.Columns {
		if col.IsPrimaryKey && col.IsOwnerColumn {
			return snakeToPascal(col.Name)
		}
	}
	return ""
}

func findFKColumn(parentTable, childTable string) string {
	singular := strings.TrimSuffix(parentTable, "s")
	return singular + "_id"
}
