package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateGraphQLMutations generates mutation_gen.go with mutation dispatch
// and create/update/delete methods.
func GenerateGraphQLMutations(tables []*schema.Table, modelsImport, packageName string) ([]byte, error) {
	// Collect imports needed
	needsTime := false
	needsDecimal := false
	needsJSON := false
	for _, tbl := range tables {
		if tbl.IsImmutable {
			continue
		}
		for _, col := range tbl.Columns {
			if isExcludedFromInput(col) {
				continue
			}
			switch col.Type {
			case schema.Timestamp, schema.Date, schema.Time:
				needsTime = true
			case schema.Decimal:
				needsDecimal = true
			case schema.JSONB:
				needsJSON = true
			}
		}
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	if needsJSON {
		b.WriteString("\t\"encoding/json\"\n")
	}
	if needsTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("\t\"%s\"\n", modelsImport))
	b.WriteString("\t\"github.com/google/uuid\"\n")
	if needsDecimal {
		b.WriteString("\t\"github.com/shopspring/decimal\"\n")
	}
	b.WriteString(")\n\n")

	b.WriteString("var _ = uuid.Nil\n")
	if needsTime {
		b.WriteString("var _ = time.RFC3339\n")
	}
	if needsDecimal {
		b.WriteString("var _ = decimal.Zero\n")
	}
	if needsJSON {
		b.WriteString("var _ = json.RawMessage{}\n")
	}
	b.WriteString("\n")

	// Mutation dispatch
	b.WriteString("func (r *RootResolver) resolveMutation(ctx *ResolveContext, field Field) (any, error) {\n")
	b.WriteString("\tswitch field.Name {\n")
	for _, tbl := range tables {
		if tbl.IsImmutable {
			continue
		}
		structName := tableToStructName(tbl.Name)
		b.WriteString(fmt.Sprintf("\tcase \"create%s\":\n\t\treturn r.mutationCreate%s(ctx, field)\n", structName, structName))
		if !tbl.IsAppendOnly {
			b.WriteString(fmt.Sprintf("\tcase \"update%s\":\n\t\treturn r.mutationUpdate%s(ctx, field)\n", structName, structName))
		}
		b.WriteString(fmt.Sprintf("\tcase \"delete%s\":\n\t\treturn r.mutationDelete%s(ctx, field)\n", structName, structName))
	}
	b.WriteString("\tdefault:\n\t\treturn nil, fmt.Errorf(\"unknown mutation field: %s\", field.Name)\n")
	b.WriteString("\t}\n}\n\n")

	// Per-table mutation methods
	for _, tbl := range tables {
		if tbl.IsImmutable {
			continue
		}
		writeCreateMutation(&b, tbl)
		if !tbl.IsAppendOnly {
			writeUpdateMutation(&b, tbl)
		}
		writeDeleteMutation(&b, tbl)
	}

	// Input extractors
	for _, tbl := range tables {
		if tbl.IsImmutable {
			continue
		}
		writeInputExtractor(&b, tbl, "Create")
		if !tbl.IsAppendOnly {
			writeInputExtractor(&b, tbl, "Update")
		}
	}

	return format.Source(b.Bytes())
}

// inputToModelConversion returns the Go code to convert a GQL input field (string)
// to the model field's actual Go type. If asPointer is true, returns a pointer expression.
func inputToModelConversion(col *schema.Column, inputExpr string, asPointer bool) string {
	switch col.Type {
	case schema.UUID:
		if asPointer {
			return fmt.Sprintf("func() *uuid.UUID { u := uuid.MustParse(%s); return &u }()", inputExpr)
		}
		return fmt.Sprintf("uuid.MustParse(%s)", inputExpr)
	case schema.Timestamp:
		if col.IsNullable || asPointer {
			return fmt.Sprintf("func() *time.Time { t, _ := time.Parse(time.RFC3339, %s); return &t }()", inputExpr)
		}
		return fmt.Sprintf("func() time.Time { t, _ := time.Parse(time.RFC3339, %s); return t }()", inputExpr)
	case schema.Decimal:
		return fmt.Sprintf("decimal.RequireFromString(%s)", inputExpr)
	case schema.JSONB:
		return fmt.Sprintf("func() *json.RawMessage { r := json.RawMessage(%s); return &r }()", inputExpr)
	default:
		return inputExpr
	}
}

// needsConversion returns true if the column type requires conversion from string.
func needsConversion(col *schema.Column) bool {
	switch col.Type {
	case schema.UUID, schema.Timestamp, schema.Decimal, schema.JSONB:
		return true
	}
	return false
}

func writeCreateMutation(b *bytes.Buffer, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)

	b.WriteString(fmt.Sprintf("func (r *RootResolver) mutationCreate%s(ctx *ResolveContext, field Field) (any, error) {\n", structName))
	b.WriteString("\tif !ctx.IsAuthenticated() {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, Unauthenticated(\"create%s: authentication required\")\n", structName))
	b.WriteString("\t}\n\n")

	b.WriteString(fmt.Sprintf("\tinput, err := extractCreate%sInput(field.Args[\"input\"])\n", structName))
	b.WriteString("\tif err != nil {\n\t\treturn nil, BadInput(err.Error())\n\t}\n\n")

	b.WriteString("\tif err := validateInput(input); err != nil {\n\t\treturn nil, err\n\t}\n\n")

	b.WriteString(fmt.Sprintf("\trecord := &models.%s{}\n", structName))

	// Set all fields with proper type conversion
	for _, col := range tbl.Columns {
		if isExcludedFromInput(col) {
			continue
		}
		if graphqlGoSerType(col) == "" {
			continue
		}
		goFieldName := snakeToPascal(col.Name)
		conv := inputToModelConversion(col, fmt.Sprintf("input.%s", goFieldName), false)

		if col.IsNullable || col.DefaultValue != nil {
			// Pointer field - check if provided
			b.WriteString(fmt.Sprintf("\tif input.%s != nil {\n", goFieldName))
			conv = inputToModelConversion(col, fmt.Sprintf("*input.%s", goFieldName), col.IsNullable)
			b.WriteString(fmt.Sprintf("\t\trecord.%s = %s\n", goFieldName, conv))
			b.WriteString("\t}\n")
		} else {
			b.WriteString(fmt.Sprintf("\trecord.%s = %s\n", goFieldName, conv))
		}
	}

	b.WriteString(fmt.Sprintf("\n\tif err := models.Query%s().Create(record); err != nil {\n\t\treturn nil, InternalError(err.Error())\n\t}\n\n", structName))
	b.WriteString(fmt.Sprintf("\treturn r.resolve%sObject(ctx, record, field.Selections)\n", structName))
	b.WriteString("}\n\n")
}

func writeUpdateMutation(b *bytes.Buffer, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)

	b.WriteString(fmt.Sprintf("func (r *RootResolver) mutationUpdate%s(ctx *ResolveContext, field Field) (any, error) {\n", structName))
	b.WriteString("\tif !ctx.IsAuthenticated() {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, Unauthenticated(\"update%s: authentication required\")\n", structName))
	b.WriteString("\t}\n\n")

	b.WriteString("\tidStr, _ := field.Args[\"id\"].(string)\n")
	parseExpr, needsErr := pkParseExpr(tbl, "idStr")
	if needsErr {
		b.WriteString(fmt.Sprintf("\tid, err := %s\n", parseExpr))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"update%s: invalid id\")\n", structName))
		b.WriteString("\t}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("\tid := %s\n\n", parseExpr))
	}

	b.WriteString(fmt.Sprintf("\tinput, err := extractUpdate%sInput(field.Args[\"input\"])\n", structName))
	b.WriteString("\tif err != nil {\n\t\treturn nil, BadInput(err.Error())\n\t}\n\n")

	b.WriteString("\tif err := validateInput(input); err != nil {\n\t\treturn nil, err\n\t}\n\n")

	pk := pkColumn(tbl)
	pkMethod := "Where" + snakeToPascal(pk.Name)
	b.WriteString(fmt.Sprintf("\trecord, err := models.Query%s().%s(id).First()\n", structName, pkMethod))
	b.WriteString("\tif err != nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, NotFound(\"%s\")\n", strings.TrimSuffix(tbl.Name, "s")))
	b.WriteString("\t}\n\n")

	// Apply partial update with type conversion
	for _, col := range tbl.Columns {
		if isExcludedFromInput(col) {
			continue
		}
		if graphqlGoSerType(col) == "" {
			continue
		}
		goFieldName := snakeToPascal(col.Name)
		conv := inputToModelConversion(col, fmt.Sprintf("*input.%s", goFieldName), col.IsNullable)
		b.WriteString(fmt.Sprintf("\tif input.%s != nil {\n\t\trecord.%s = %s\n\t}\n", goFieldName, goFieldName, conv))
	}

	b.WriteString(fmt.Sprintf("\n\tif err := models.Query%s().Update(record); err != nil {\n\t\treturn nil, InternalError(err.Error())\n\t}\n\n", structName))
	b.WriteString(fmt.Sprintf("\treturn r.resolve%sObject(ctx, record, field.Selections)\n", structName))
	b.WriteString("}\n\n")
}

func writeDeleteMutation(b *bytes.Buffer, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)

	b.WriteString(fmt.Sprintf("func (r *RootResolver) mutationDelete%s(ctx *ResolveContext, field Field) (any, error) {\n", structName))
	b.WriteString("\tif !ctx.IsAuthenticated() {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, Unauthenticated(\"delete%s: authentication required\")\n", structName))
	b.WriteString("\t}\n\n")

	b.WriteString("\tidStr, _ := field.Args[\"id\"].(string)\n")
	parseExpr, needsErrDel := pkParseExpr(tbl, "idStr")
	if needsErrDel {
		b.WriteString(fmt.Sprintf("\tid, err := %s\n", parseExpr))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"delete%s: invalid id\")\n", structName))
		b.WriteString("\t}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("\tid := %s\n\n", parseExpr))
	}

	// Fetch then delete (Delete requires *T)
	pk := pkColumn(tbl)
	pkMethod := "Where" + snakeToPascal(pk.Name)
	b.WriteString(fmt.Sprintf("\trecord, err := models.Query%s().%s(id).First()\n", structName, pkMethod))
	b.WriteString("\tif err != nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, NotFound(\"%s\")\n", strings.TrimSuffix(tbl.Name, "s")))
	b.WriteString("\t}\n\n")

	b.WriteString(fmt.Sprintf("\tif err := models.Query%s().Delete(record); err != nil {\n", structName))
	b.WriteString(fmt.Sprintf("\t\treturn nil, InternalError(\"delete %s: \" + err.Error())\n", strings.TrimSuffix(tbl.Name, "s")))
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn true, nil\n")
	b.WriteString("}\n\n")
}

func writeInputExtractor(b *bytes.Buffer, tbl *schema.Table, prefix string) {
	structName := tableToStructName(tbl.Name)
	inputType := prefix + structName + "Input"
	fnName := "extract" + inputType

	b.WriteString(fmt.Sprintf("func %s(raw any) (*%s, error) {\n", fnName, inputType))
	b.WriteString("\tm, ok := raw.(map[string]any)\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"%s: expected object\")\n", fnName))
	b.WriteString("\t}\n")
	b.WriteString(fmt.Sprintf("\tinput := &%s{}\n", inputType))

	for _, col := range tbl.Columns {
		if isExcludedFromInput(col) {
			continue
		}
		goFieldName := snakeToPascal(col.Name)
		jsonName := snakeToCamel(col.Name)
		goType := graphqlGoSerType(col)
		if goType == "" {
			continue
		}

		isPointer := prefix == "Update" || col.IsNullable || col.DefaultValue != nil

		b.WriteString(fmt.Sprintf("\tif v, ok := m[\"%s\"]; ok && v != nil {\n", jsonName))
		switch goType {
		case "string":
			b.WriteString("\t\tif s, ok := v.(string); ok {\n")
			if isPointer {
				b.WriteString(fmt.Sprintf("\t\t\tinput.%s = &s\n", goFieldName))
			} else {
				b.WriteString(fmt.Sprintf("\t\t\tinput.%s = s\n", goFieldName))
			}
			b.WriteString("\t\t}\n")
		case "int":
			b.WriteString("\t\tif s, ok := v.(string); ok {\n")
			b.WriteString("\t\t\tn := parseInt(s)\n")
			if isPointer {
				b.WriteString(fmt.Sprintf("\t\t\tinput.%s = &n\n", goFieldName))
			} else {
				b.WriteString(fmt.Sprintf("\t\t\tinput.%s = n\n", goFieldName))
			}
			b.WriteString("\t\t}\n")
		case "int64":
			b.WriteString("\t\tif s, ok := v.(string); ok {\n")
			b.WriteString("\t\t\tn := int64(parseInt(s))\n")
			if isPointer {
				b.WriteString(fmt.Sprintf("\t\t\tinput.%s = &n\n", goFieldName))
			} else {
				b.WriteString(fmt.Sprintf("\t\t\tinput.%s = n\n", goFieldName))
			}
			b.WriteString("\t\t}\n")
		case "bool":
			b.WriteString("\t\tif s, ok := v.(string); ok {\n")
			b.WriteString("\t\t\tbv := s == \"true\"\n")
			if isPointer {
				b.WriteString(fmt.Sprintf("\t\t\tinput.%s = &bv\n", goFieldName))
			} else {
				b.WriteString(fmt.Sprintf("\t\t\tinput.%s = bv\n", goFieldName))
			}
			b.WriteString("\t\t}\n")
		}
		b.WriteString("\t}\n")
	}

	b.WriteString("\treturn input, nil\n")
	b.WriteString("}\n\n")
}
