package generator

import (
	"bytes"
	"fmt"
	"go/format"
)

// AdapterConfig holds configuration for generating controller action adapter resolvers.
type AdapterConfig struct {
	Actions           []DerivedAction
	ControllersImport string
	ModelsImport      string
	PackageName       string
}

// GenerateGraphQLAdapterResolvers generates adapter_resolver_gen.go with resolvers
// that bridge GraphQL mutations to existing controller methods.
// Each ControllerAction("name", handler) becomes a mutation resolver that:
// 1. Extracts input from the GraphQL request
// 2. Builds a pickle.Context
// 3. Calls the controller method
// 4. Adapts the response
func GenerateGraphQLAdapterResolvers(cfg AdapterConfig) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", cfg.PackageName))
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString(")\n\n")
	b.WriteString("var _ = json.RawMessage{}\n")
	b.WriteString("var _ = fmt.Sprintf\n\n")

	// Generate a dispatch function that maps mutation names to adapter calls
	b.WriteString("// adapterMutationNames returns the list of controller-action mutation names.\n")
	b.WriteString("func adapterMutationNames() []string {\n")
	b.WriteString("\treturn []string{\n")
	for _, action := range cfg.Actions {
		b.WriteString(fmt.Sprintf("\t\t%q,\n", action.Name))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Generate resolver stub for each action
	for _, action := range cfg.Actions {
		writeAdapterResolver(&b, action)
	}

	return format.Source(b.Bytes())
}

// writeAdapterResolver generates a single adapter resolver for a controller action.
func writeAdapterResolver(b *bytes.Buffer, action DerivedAction) {
	funcName := "resolve" + snakeToPascal(action.Name)
	b.WriteString(fmt.Sprintf("// %s dispatches the %q GraphQL mutation to the corresponding controller action.\n", funcName, action.Name))
	b.WriteString(fmt.Sprintf("func (r *RootResolver) %s(ctx *ResolveContext, field Field) (any, error) {\n", funcName))
	b.WriteString("\tif !ctx.IsAuthenticated() {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, Unauthenticated(%q)\n", action.Name+": authentication required"))
	b.WriteString("\t}\n\n")

	// Extract input from args
	b.WriteString("\tinputRaw, hasInput := field.Args[\"input\"]\n")
	b.WriteString("\t_ = inputRaw\n")
	b.WriteString("\t_ = hasInput\n\n")

	// Placeholder: the adapter calls through the generated controller bridge.
	// The actual controller method binding is resolved at compile time in the
	// user project, not here — this generates the resolver shape that the
	// user's controller_actions_gen.go will wire up.
	b.WriteString(fmt.Sprintf("\treturn nil, fmt.Errorf(%q)\n", action.Name+": adapter not wired — implement "+snakeToPascal(action.Name)+" in controller_actions.go"))
	b.WriteString("}\n\n")
}

// snakeToPascal is defined in helpers.go
