package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
)

// CRUDConfig holds the configuration for zero-controller CRUD generation.
type CRUDConfig struct {
	Tables        []*schema.Table
	Relationships []SchemaRelationship
	ModelsImport  string
	PackageName   string
}

// GenerateGraphQLCRUDResolvers generates crud_resolver_gen.go with ownership-scoped
// CRUD resolvers, nested resource mutations, and constraint-based validation.
// This implements spec 018: zero-controller GraphQL from migrations alone.
func GenerateGraphQLCRUDResolvers(cfg CRUDConfig) ([]byte, error) {
	relByParent := map[string][]SchemaRelationship{}
	childToParent := map[string]SchemaRelationship{}
	for _, rel := range cfg.Relationships {
		relByParent[rel.ParentTable] = append(relByParent[rel.ParentTable], rel)
		childToParent[rel.ChildTable] = rel
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", cfg.PackageName))
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"time\"\n\n")
	b.WriteString(fmt.Sprintf("\t\"%s\"\n", cfg.ModelsImport))
	b.WriteString("\t\"github.com/google/uuid\"\n")
	b.WriteString(")\n\n")
	b.WriteString("var _ = json.RawMessage{}\n")
	b.WriteString("var _ = time.RFC3339\n")
	b.WriteString("var _ = uuid.Nil\n")
	b.WriteString("var _ = strings.ToLower\n")
	b.WriteString("var _ = fmt.Sprintf\n\n")

	// Generate ownership-scoped create mutations
	for _, tbl := range cfg.Tables {
		if tbl.IsImmutable {
			continue
		}
		writeCRUDCreateMutation(&b, tbl, childToParent)
		if !tbl.IsAppendOnly {
			writeCRUDUpdateMutation(&b, tbl)
		}
		writeCRUDDeleteMutation(&b, tbl)
	}

	// Generate nested resource mutations (parent-scoped)
	for _, tbl := range cfg.Tables {
		if tbl.IsImmutable {
			continue
		}
		if rel, ok := childToParent[tbl.Name]; ok {
			writeNestedCreateMutation(&b, tbl, rel)
		}
	}

	// Generate constraint validation helpers
	writeConstraintValidators(&b, cfg.Tables)

	return format.Source(b.Bytes())
}

// ownerColumn returns the IsOwner column for a table, or nil if none.
func ownerColumn(tbl *schema.Table) *schema.Column {
	for _, col := range tbl.Columns {
		if col.IsOwnerColumn {
			return col
		}
	}
	return nil
}

// writeCRUDCreateMutation generates a create mutation with ownership auto-scoping.
func writeCRUDCreateMutation(b *bytes.Buffer, tbl *schema.Table, childToParent map[string]SchemaRelationship) {
	structName := tableToStructName(tbl.Name)
	ownerCol := ownerColumn(tbl)

	b.WriteString(fmt.Sprintf("func (r *RootResolver) crudCreate%s(ctx *ResolveContext, field Field) (any, error) {\n", structName))
	b.WriteString("\tif !ctx.IsAuthenticated() {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, Unauthenticated(\"create%s: authentication required\")\n", structName))
	b.WriteString("\t}\n\n")

	b.WriteString(fmt.Sprintf("\tinput, err := extractCreate%sInput(field.Args[\"input\"])\n", structName))
	b.WriteString("\tif err != nil {\n\t\treturn nil, BadInput(err.Error())\n\t}\n\n")

	// Constraint-based validation
	b.WriteString(fmt.Sprintf("\tif err := validate%sConstraints(input); err != nil {\n\t\treturn nil, err\n\t}\n\n", structName))

	b.WriteString("\tif err := validateInput(input); err != nil {\n\t\treturn nil, err\n\t}\n\n")

	b.WriteString(fmt.Sprintf("\trecord := &models.%s{}\n", structName))

	// Set owner column from auth context
	if ownerCol != nil {
		goField := snakeToPascal(ownerCol.Name)
		b.WriteString(fmt.Sprintf("\t// Ownership: auto-set %s from authenticated user\n", ownerCol.Name))
		if ownerCol.Type == schema.UUID {
			b.WriteString(fmt.Sprintf("\townerID, err := uuid.Parse(ctx.UserID())\n"))
			b.WriteString("\tif err != nil {\n")
			b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"create%s: invalid owner ID\")\n", structName))
			b.WriteString("\t}\n")
			b.WriteString(fmt.Sprintf("\trecord.%s = ownerID\n\n", goField))
		} else {
			b.WriteString(fmt.Sprintf("\trecord.%s = ctx.UserID()\n\n", goField))
		}
	}

	// Set fields from input
	for _, col := range tbl.Columns {
		if isExcludedFromInput(col) {
			continue
		}
		// Skip owner column - already set from auth
		if ownerCol != nil && col.Name == ownerCol.Name {
			continue
		}
		// Skip FK columns that come from nesting
		if _, ok := childToParent[tbl.Name]; ok && isFKToParent(col, childToParent[tbl.Name]) {
			continue
		}
		goFieldName := snakeToPascal(col.Name)
		conv := inputToModelConversion(col, fmt.Sprintf("input.%s", goFieldName), false)

		if col.IsNullable || col.DefaultValue != nil {
			b.WriteString(fmt.Sprintf("\tif input.%s != nil {\n", goFieldName))
			conv = inputToModelConversion(col, fmt.Sprintf("*input.%s", goFieldName), col.IsNullable)
			b.WriteString(fmt.Sprintf("\t\trecord.%s = %s\n", goFieldName, conv))
			b.WriteString("\t}\n")
		} else {
			b.WriteString(fmt.Sprintf("\trecord.%s = %s\n", goFieldName, conv))
		}
	}

	b.WriteString(fmt.Sprintf("\n\tif err := models.Query%s().Create(record); err != nil {\n\t\treturn nil, InternalError(err.Error())\n\t}\n\n", structName))
	b.WriteString(fmt.Sprintf("\treturn r.resolve%sObject(ctx, record, field.Selections)\n", structName))
	b.WriteString("}\n\n")
}

// writeCRUDUpdateMutation generates an update mutation with ownership scoping.
func writeCRUDUpdateMutation(b *bytes.Buffer, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	ownerCol := ownerColumn(tbl)

	b.WriteString(fmt.Sprintf("func (r *RootResolver) crudUpdate%s(ctx *ResolveContext, field Field) (any, error) {\n", structName))
	b.WriteString("\tif !ctx.IsAuthenticated() {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, Unauthenticated(\"update%s: authentication required\")\n", structName))
	b.WriteString("\t}\n\n")

	b.WriteString("\tidStr, _ := field.Args[\"id\"].(string)\n")
	parseExpr, needsErr := pkParseExpr(tbl, "idStr")
	if needsErr {
		b.WriteString(fmt.Sprintf("\tid, err := %s\n", parseExpr))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"update%s: invalid id\")\n", structName))
		b.WriteString("\t}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("\tid := %s\n\n", parseExpr))
	}

	b.WriteString(fmt.Sprintf("\tinput, err := extractUpdate%sInput(field.Args[\"input\"])\n", structName))
	b.WriteString("\tif err != nil {\n\t\treturn nil, BadInput(err.Error())\n\t}\n\n")

	b.WriteString("\tif err := validateInput(input); err != nil {\n\t\treturn nil, err\n\t}\n\n")

	pk := pkColumn(tbl)
	pkMethod := "Where" + snakeToPascal(pk.Name)

	// Ownership-scoped fetch
	b.WriteString(fmt.Sprintf("\tq := models.Query%s().%s(id)\n", structName, pkMethod))
	if ownerCol != nil {
		goField := snakeToPascal(ownerCol.Name)
		b.WriteString(fmt.Sprintf("\t// Ownership: scope by owner — users can only update their own records\n"))
		if ownerCol.Type == schema.UUID {
			b.WriteString(fmt.Sprintf("\townerID, err := uuid.Parse(ctx.UserID())\n"))
			b.WriteString("\tif err != nil {\n")
			b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"update%s: invalid owner ID\")\n", structName))
			b.WriteString("\t}\n")
			b.WriteString(fmt.Sprintf("\tq.Where%s(ownerID)\n", goField))
		} else {
			b.WriteString(fmt.Sprintf("\tq.Where%s(ctx.UserID())\n", goField))
		}
	}

	b.WriteString("\trecord, err := q.First()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, NotFound(\"%s\")\n", strings.TrimSuffix(tbl.Name, "s")))
	b.WriteString("\t}\n\n")

	// Apply partial update
	for _, col := range tbl.Columns {
		if isExcludedFromInput(col) {
			continue
		}
		if ownerCol != nil && col.Name == ownerCol.Name {
			continue // never allow changing owner
		}
		goFieldName := snakeToPascal(col.Name)
		conv := inputToModelConversion(col, fmt.Sprintf("*input.%s", goFieldName), col.IsNullable)
		b.WriteString(fmt.Sprintf("\tif input.%s != nil {\n\t\trecord.%s = %s\n\t}\n", goFieldName, goFieldName, conv))
	}

	b.WriteString(fmt.Sprintf("\n\tif err := models.Query%s().Update(record); err != nil {\n\t\treturn nil, InternalError(err.Error())\n\t}\n\n", structName))
	b.WriteString(fmt.Sprintf("\treturn r.resolve%sObject(ctx, record, field.Selections)\n", structName))
	b.WriteString("}\n\n")
}

// writeCRUDDeleteMutation generates a delete mutation with ownership scoping.
func writeCRUDDeleteMutation(b *bytes.Buffer, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	ownerCol := ownerColumn(tbl)

	b.WriteString(fmt.Sprintf("func (r *RootResolver) crudDelete%s(ctx *ResolveContext, field Field) (any, error) {\n", structName))
	b.WriteString("\tif !ctx.IsAuthenticated() {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, Unauthenticated(\"delete%s: authentication required\")\n", structName))
	b.WriteString("\t}\n\n")

	b.WriteString("\tidStr, _ := field.Args[\"id\"].(string)\n")
	parseExpr, needsErrDel := pkParseExpr(tbl, "idStr")
	if needsErrDel {
		b.WriteString(fmt.Sprintf("\tid, err := %s\n", parseExpr))
		b.WriteString("\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"delete%s: invalid id\")\n", structName))
		b.WriteString("\t}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("\tid := %s\n\n", parseExpr))
	}

	pk := pkColumn(tbl)
	pkMethod := "Where" + snakeToPascal(pk.Name)

	b.WriteString(fmt.Sprintf("\tq := models.Query%s().%s(id)\n", structName, pkMethod))
	if ownerCol != nil {
		goField := snakeToPascal(ownerCol.Name)
		b.WriteString(fmt.Sprintf("\t// Ownership: scope by owner — users can only delete their own records\n"))
		if ownerCol.Type == schema.UUID {
			b.WriteString(fmt.Sprintf("\townerID, err := uuid.Parse(ctx.UserID())\n"))
			b.WriteString("\tif err != nil {\n")
			b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"delete%s: invalid owner ID\")\n", structName))
			b.WriteString("\t}\n")
			b.WriteString(fmt.Sprintf("\tq.Where%s(ownerID)\n", goField))
		} else {
			b.WriteString(fmt.Sprintf("\tq.Where%s(ctx.UserID())\n", goField))
		}
	}

	b.WriteString("\trecord, err := q.First()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, NotFound(\"%s\")\n", strings.TrimSuffix(tbl.Name, "s")))
	b.WriteString("\t}\n\n")

	b.WriteString(fmt.Sprintf("\tif err := models.Query%s().Delete(record); err != nil {\n", structName))
	b.WriteString(fmt.Sprintf("\t\treturn nil, InternalError(\"delete %s: \" + err.Error())\n", strings.TrimSuffix(tbl.Name, "s")))
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn true, nil\n")
	b.WriteString("}\n\n")
}

// writeNestedCreateMutation generates a parent-scoped create mutation for child tables.
// e.g., createPost(userId: ID!, input: CreatePostInput!) sets the FK automatically.
func writeNestedCreateMutation(b *bytes.Buffer, tbl *schema.Table, rel SchemaRelationship) {
	structName := tableToStructName(tbl.Name)
	parentSingular := strings.TrimSuffix(rel.ParentTable, "s")
	fkCol := parentSingular + "_id"
	parentArgName := snakeToCamel(parentSingular) + "Id"
	parentStructName := tableToStructName(rel.ParentTable)

	b.WriteString(fmt.Sprintf("func (r *RootResolver) crudCreateNested%s(ctx *ResolveContext, field Field) (any, error) {\n", structName))
	b.WriteString("\tif !ctx.IsAuthenticated() {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, Unauthenticated(\"create%s: authentication required\")\n", structName))
	b.WriteString("\t}\n\n")

	// Extract parent ID
	b.WriteString(fmt.Sprintf("\tparentIDStr, ok := field.Args[\"%s\"].(string)\n", parentArgName))
	b.WriteString("\tif !ok {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"create%s: %s argument required\")\n", structName, parentArgName))
	b.WriteString("\t}\n")
	b.WriteString("\tparentID, err := uuid.Parse(parentIDStr)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"create%s: invalid %s\")\n", structName, parentArgName))
	b.WriteString("\t}\n\n")

	// Verify parent exists
	b.WriteString(fmt.Sprintf("\t_, err = models.Query%s().WhereID(parentID).First()\n", parentStructName))
	b.WriteString("\tif err != nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, NotFound(\"%s\")\n", parentSingular))
	b.WriteString("\t}\n\n")

	b.WriteString(fmt.Sprintf("\tinput, err := extractCreate%sInput(field.Args[\"input\"])\n", structName))
	b.WriteString("\tif err != nil {\n\t\treturn nil, BadInput(err.Error())\n\t}\n\n")

	b.WriteString(fmt.Sprintf("\tif err := validate%sConstraints(input); err != nil {\n\t\treturn nil, err\n\t}\n\n", structName))

	b.WriteString("\tif err := validateInput(input); err != nil {\n\t\treturn nil, err\n\t}\n\n")

	b.WriteString(fmt.Sprintf("\trecord := &models.%s{}\n", structName))

	// Set FK from parent
	b.WriteString(fmt.Sprintf("\trecord.%s = parentID\n", snakeToPascal(fkCol)))

	// Set owner column from auth if present
	ownerCol := ownerColumn(tbl)
	if ownerCol != nil && ownerCol.Name != fkCol {
		goField := snakeToPascal(ownerCol.Name)
		if ownerCol.Type == schema.UUID {
			b.WriteString(fmt.Sprintf("\townerID, err := uuid.Parse(ctx.UserID())\n"))
			b.WriteString("\tif err != nil {\n")
			b.WriteString(fmt.Sprintf("\t\treturn nil, BadInput(\"create%s: invalid owner ID\")\n", structName))
			b.WriteString("\t}\n")
			b.WriteString(fmt.Sprintf("\trecord.%s = ownerID\n", goField))
		} else {
			b.WriteString(fmt.Sprintf("\trecord.%s = ctx.UserID()\n", goField))
		}
	}

	// Set remaining fields from input
	for _, col := range tbl.Columns {
		if isExcludedFromInput(col) {
			continue
		}
		if col.Name == fkCol {
			continue // already set from parent
		}
		if ownerCol != nil && col.Name == ownerCol.Name {
			continue // already set from auth
		}
		goFieldName := snakeToPascal(col.Name)
		conv := inputToModelConversion(col, fmt.Sprintf("input.%s", goFieldName), false)

		if col.IsNullable || col.DefaultValue != nil {
			b.WriteString(fmt.Sprintf("\tif input.%s != nil {\n", goFieldName))
			conv = inputToModelConversion(col, fmt.Sprintf("*input.%s", goFieldName), col.IsNullable)
			b.WriteString(fmt.Sprintf("\t\trecord.%s = %s\n", goFieldName, conv))
			b.WriteString("\t}\n")
		} else {
			b.WriteString(fmt.Sprintf("\trecord.%s = %s\n", goFieldName, conv))
		}
	}

	b.WriteString(fmt.Sprintf("\n\tif err := models.Query%s().Create(record); err != nil {\n\t\treturn nil, InternalError(err.Error())\n\t}\n\n", structName))
	b.WriteString(fmt.Sprintf("\treturn r.resolve%sObject(ctx, record, field.Selections)\n", structName))
	b.WriteString("}\n\n")
}

// isFKToParent returns true if the column is a foreign key to the parent table in a nesting relationship.
func isFKToParent(col *schema.Column, rel SchemaRelationship) bool {
	parentSingular := strings.TrimSuffix(rel.ParentTable, "s")
	return col.Name == parentSingular+"_id"
}

// writeConstraintValidators generates validation functions derived from column constraints.
func writeConstraintValidators(b *bytes.Buffer, tables []*schema.Table) {
	for _, tbl := range tables {
		if tbl.IsImmutable {
			continue
		}
		structName := tableToStructName(tbl.Name)

		// Validate constraints for CreateInput
		b.WriteString(fmt.Sprintf("func validate%sConstraints(input any) error {\n", structName))
		b.WriteString(fmt.Sprintf("\tswitch v := input.(type) {\n"))

		// CreateInput validation
		createInputType := "Create" + structName + "Input"
		b.WriteString(fmt.Sprintf("\tcase *%s:\n", createInputType))
		hasCreateValidation := false
		for _, col := range tbl.Columns {
			if isExcludedFromInput(col) {
				continue
			}
			goField := snakeToPascal(col.Name)
			fieldLabel := snakeToCamel(col.Name)

			// String length constraint
			if col.Length > 0 && (col.Type == schema.String || col.Type == schema.Text) {
				hasCreateValidation = true
				isPtr := col.IsNullable || col.DefaultValue != nil
				if isPtr {
					b.WriteString(fmt.Sprintf("\t\tif v.%s != nil && len(*v.%s) > %d {\n", goField, goField, col.Length))
				} else {
					b.WriteString(fmt.Sprintf("\t\tif len(v.%s) > %d {\n", goField, col.Length))
				}
				b.WriteString(fmt.Sprintf("\t\t\treturn BadInput(\"%s: maximum length %d\")\n", fieldLabel, col.Length))
				b.WriteString("\t\t}\n")
			}

			// UUID format validation for FK columns
			if col.ForeignKeyTable != "" && col.Type == schema.UUID {
				hasCreateValidation = true
				isPtr := col.IsNullable || col.DefaultValue != nil
				if isPtr {
					b.WriteString(fmt.Sprintf("\t\tif v.%s != nil {\n", goField))
					b.WriteString(fmt.Sprintf("\t\t\tif _, err := uuid.Parse(*v.%s); err != nil {\n", goField))
					b.WriteString(fmt.Sprintf("\t\t\t\treturn BadInput(\"%s: invalid UUID format\")\n", fieldLabel))
					b.WriteString("\t\t\t}\n")
					b.WriteString("\t\t}\n")
				} else {
					b.WriteString(fmt.Sprintf("\t\tif _, err := uuid.Parse(v.%s); err != nil {\n", goField))
					b.WriteString(fmt.Sprintf("\t\t\treturn BadInput(\"%s: invalid UUID format\")\n", fieldLabel))
					b.WriteString("\t\t}\n")
				}
			}
		}
		if !hasCreateValidation {
			b.WriteString("\t\t_ = v\n")
		}

		// UpdateInput validation
		if !tbl.IsAppendOnly {
			updateInputType := "Update" + structName + "Input"
			b.WriteString(fmt.Sprintf("\tcase *%s:\n", updateInputType))
			hasUpdateValidation := false
			for _, col := range tbl.Columns {
				if isExcludedFromInput(col) {
					continue
				}
				goField := snakeToPascal(col.Name)
				fieldLabel := snakeToCamel(col.Name)

				if col.Length > 0 && (col.Type == schema.String || col.Type == schema.Text) {
					hasUpdateValidation = true
					b.WriteString(fmt.Sprintf("\t\tif v.%s != nil && len(*v.%s) > %d {\n", goField, goField, col.Length))
					b.WriteString(fmt.Sprintf("\t\t\treturn BadInput(\"%s: maximum length %d\")\n", fieldLabel, col.Length))
					b.WriteString("\t\t}\n")
				}

				if col.ForeignKeyTable != "" && col.Type == schema.UUID {
					hasUpdateValidation = true
					b.WriteString(fmt.Sprintf("\t\tif v.%s != nil {\n", goField))
					b.WriteString(fmt.Sprintf("\t\t\tif _, err := uuid.Parse(*v.%s); err != nil {\n", goField))
					b.WriteString(fmt.Sprintf("\t\t\t\treturn BadInput(\"%s: invalid UUID format\")\n", fieldLabel))
					b.WriteString("\t\t\t}\n")
					b.WriteString("\t\t}\n")
				}
			}
			if !hasUpdateValidation {
				b.WriteString("\t\t_ = v\n")
			}
		}

		b.WriteString("\t}\n")
		b.WriteString("\treturn nil\n")
		b.WriteString("}\n\n")
	}
}

// GenerateGraphQLCRUDSchema extends the SDL with nested resource mutations.
// Returns additional mutation fields to append to the schema.
func GenerateNestedMutationSDL(tables []*schema.Table, relationships []SchemaRelationship) string {
	childToParent := map[string]SchemaRelationship{}
	for _, rel := range relationships {
		childToParent[rel.ChildTable] = rel
	}

	var b strings.Builder
	for _, tbl := range tables {
		if tbl.IsImmutable {
			continue
		}
		rel, isChild := childToParent[tbl.Name]
		if !isChild {
			continue
		}
		structName := tableToStructName(tbl.Name)
		parentSingular := strings.TrimSuffix(rel.ParentTable, "s")
		parentArgName := snakeToCamel(parentSingular) + "Id"

		b.WriteString(fmt.Sprintf("  createNested%s(%s: ID!, input: Create%sInput!): %s! @auth\n",
			structName, parentArgName, structName, structName))
	}
	return b.String()
}

// ColumnConstraints extracts validation constraints from column definitions
// to generate validate tags for input structs when no request struct exists.
func ColumnConstraints(col *schema.Column) string {
	var parts []string

	// Required on create: NOT NULL without default
	if !col.IsNullable && col.DefaultValue == nil {
		parts = append(parts, "required")
	}

	// String length
	if col.Length > 0 && (col.Type == schema.String || col.Type == schema.Text) {
		parts = append(parts, fmt.Sprintf("max=%d", col.Length))
	}

	// UUID format
	if col.Type == schema.UUID {
		parts = append(parts, "uuid")
	}

	return strings.Join(parts, ",")
}

// HasCRUDOverride checks if a user-written resolver file exists for a specific
// resource, implementing the per-resource override pattern.
func HasCRUDOverride(graphqlDir, tableName string) bool {
	singular := strings.TrimSuffix(tableName, "s")
	return hasOverride(graphqlDir, singular+"_resolvers.go")
}
