package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateGraphQLSchema generates schema_gen.go containing the SDL string constant
// and the parsed schema variable.
func GenerateGraphQLSchema(tables []*schema.Table, relationships []SchemaRelationship, packageName string) ([]byte, error) {
	sdl := buildSDL(tables, relationships)

	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/vektah/gqlparser/v2\"\n")
	b.WriteString("\t\"github.com/vektah/gqlparser/v2/ast\"\n")
	b.WriteString(")\n\n")
	b.WriteString(fmt.Sprintf("// SchemaSDL is the GraphQL schema as an SDL string, embedded at compile time.\nconst SchemaSDL = %s\n\n", quoteSDL(sdl)))
	b.WriteString("// parsedSchema is compiled once at init from SchemaSDL.\n")
	b.WriteString("var parsedSchema *ast.Schema = gqlparser.MustLoadSchema(&ast.Source{\n")
	b.WriteString("\tName:  \"schema.graphql\",\n")
	b.WriteString("\tInput: SchemaSDL,\n")
	b.WriteString("})\n")

	return format.Source(b.Bytes())
}

func quoteSDL(s string) string {
	if !strings.Contains(s, "`") {
		return "`\n" + s + "`"
	}
	return fmt.Sprintf("%q", s)
}

func buildSDL(tables []*schema.Table, relationships []SchemaRelationship) string {
	// Build relationship lookup
	relByParent := map[string][]SchemaRelationship{}
	for _, rel := range relationships {
		relByParent[rel.ParentTable] = append(relByParent[rel.ParentTable], rel)
	}

	var b strings.Builder

	// Custom scalars
	b.WriteString("scalar DateTime\n\n")

	// Object types
	for _, tbl := range tables {
		writeObjectType(&b, tbl, relByParent[tbl.Name])
	}

	// Input types for filters
	for _, tbl := range tables {
		writeFilterType(&b, tbl)
		writeSortEnum(&b, tbl)
	}

	// Shared filter input types
	writeSharedFilterTypes(&b)

	// Pagination types
	writePaginationTypes(&b)

	// Connection types per table
	for _, tbl := range tables {
		writeConnectionType(&b, tbl)
	}

	// Query root
	writeQueryType(&b, tables)

	// Mutation root
	writeMutationType(&b, tables)

	// Input types for mutations
	for _, tbl := range tables {
		writeInputTypes(&b, tbl)
	}

	return b.String()
}

func writeObjectType(b *strings.Builder, tbl *schema.Table, rels []SchemaRelationship) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("type %s {\n", structName))

	for _, col := range tbl.Columns {
		if isExcludedFromGraphQL(col) {
			continue
		}
		gqlType := graphqlType(col)
		if gqlType == "" {
			continue
		}
		nullable := graphqlNullable(col)
		fieldName := snakeToCamel(col.Name)

		// Add visibility directive as comment
		var directive string
		if col.IsPublic {
			directive = " # @public"
		} else if col.IsOwnerSees {
			directive = " # @ownerOnly"
		}

		b.WriteString(fmt.Sprintf("  %s: %s%s%s\n", fieldName, gqlType, nullable, directive))
	}

	// Relationship fields
	for _, rel := range rels {
		childStruct := tableToStructName(rel.ChildTable)
		fieldName := snakeToCamel(rel.ChildTable)
		switch rel.Type {
		case "has_many":
			b.WriteString(fmt.Sprintf("  %s: [%s!]!\n", fieldName, childStruct))
		case "has_one":
			b.WriteString(fmt.Sprintf("  %s: %s\n", fieldName, childStruct))
		}
	}

	b.WriteString("}\n\n")
}

func writeFilterType(b *strings.Builder, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("input %sFilter {\n", structName))
	for _, col := range tbl.Columns {
		if isExcludedFromGraphQL(col) {
			continue
		}
		gqlType := graphqlType(col)
		if gqlType == "" {
			continue
		}
		fieldName := snakeToCamel(col.Name)
		filterType := filterTypeForGraphQL(gqlType)
		if filterType != "" {
			b.WriteString(fmt.Sprintf("  %s: %s\n", fieldName, filterType))
		}
	}
	b.WriteString("}\n\n")
}

func filterTypeForGraphQL(gqlType string) string {
	switch gqlType {
	case "ID":
		return "IDFilter"
	case "String":
		return "StringFilter"
	case "Int":
		return "IntFilter"
	case "Boolean":
		return "BooleanFilter"
	case "DateTime":
		return "DateTimeFilter"
	default:
		return "StringFilter"
	}
}

func writeSortEnum(b *strings.Builder, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("enum %sSort {\n", structName))
	for _, col := range tbl.Columns {
		if isExcludedFromGraphQL(col) {
			continue
		}
		gqlType := graphqlType(col)
		if gqlType == "" {
			continue
		}
		upper := strings.ToUpper(col.Name)
		b.WriteString(fmt.Sprintf("  %s_ASC\n", upper))
		b.WriteString(fmt.Sprintf("  %s_DESC\n", upper))
	}
	b.WriteString("}\n\n")
}

func writeSharedFilterTypes(b *strings.Builder) {
	b.WriteString(`input IDFilter {
  eq: ID
  in: [ID!]
}

input StringFilter {
  eq: String
  like: String
  in: [String!]
}

input IntFilter {
  eq: Int
  gt: Int
  gte: Int
  lt: Int
  lte: Int
  in: [Int!]
}

input BooleanFilter {
  eq: Boolean
}

input DateTimeFilter {
  gt: DateTime
  gte: DateTime
  lt: DateTime
  lte: DateTime
}

`)
}

func writePaginationTypes(b *strings.Builder) {
	b.WriteString(`input PageInput {
  first: Int
  after: String
  last: Int
  before: String
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

`)
}

func writeConnectionType(b *strings.Builder, tbl *schema.Table) {
	structName := tableToStructName(tbl.Name)
	b.WriteString(fmt.Sprintf("type %sConnection {\n", structName))
	b.WriteString(fmt.Sprintf("  edges: [%sEdge!]!\n", structName))
	b.WriteString("  pageInfo: PageInfo!\n")
	b.WriteString("  totalCount: Int!\n")
	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("type %sEdge {\n", structName))
	b.WriteString(fmt.Sprintf("  node: %s!\n", structName))
	b.WriteString("  cursor: String!\n")
	b.WriteString("}\n\n")
}

func writeQueryType(b *strings.Builder, tables []*schema.Table) {
	b.WriteString("type Query {\n")
	for _, tbl := range tables {
		structName := tableToStructName(tbl.Name)
		plural := snakeToCamel(tbl.Name)
		singular := snakeToCamel(strings.TrimSuffix(tbl.Name, "s"))

		b.WriteString(fmt.Sprintf("  %s(filter: %sFilter, sort: %sSort, page: PageInput): %sConnection!\n",
			plural, structName, structName, structName))
		b.WriteString(fmt.Sprintf("  %s(id: ID!): %s\n", singular, structName))
	}
	b.WriteString("}\n\n")
}

func writeMutationType(b *strings.Builder, tables []*schema.Table) {
	b.WriteString("type Mutation {\n")
	for _, tbl := range tables {
		structName := tableToStructName(tbl.Name)

		if !tbl.IsImmutable {
			b.WriteString(fmt.Sprintf("  create%s(input: Create%sInput!): %s!\n", structName, structName, structName))
			if !tbl.IsAppendOnly {
				b.WriteString(fmt.Sprintf("  update%s(id: ID!, input: Update%sInput!): %s!\n", structName, structName, structName))
			}
			b.WriteString(fmt.Sprintf("  delete%s(id: ID!): Boolean!\n", structName))
		}
	}
	b.WriteString("}\n\n")
}

func writeInputTypes(b *strings.Builder, tbl *schema.Table) {
	if tbl.IsImmutable {
		return
	}

	structName := tableToStructName(tbl.Name)

	// CreateInput
	b.WriteString(fmt.Sprintf("input Create%sInput {\n", structName))
	for _, col := range tbl.Columns {
		if isExcludedFromInput(col) {
			continue
		}
		gqlType := graphqlType(col)
		if gqlType == "" {
			continue
		}
		fieldName := snakeToCamel(col.Name)
		// Required if NOT NULL without a default
		if !col.IsNullable && col.DefaultValue == nil {
			b.WriteString(fmt.Sprintf("  %s: %s!\n", fieldName, gqlType))
		} else {
			b.WriteString(fmt.Sprintf("  %s: %s\n", fieldName, gqlType))
		}
	}
	b.WriteString("}\n\n")

	// UpdateInput (all fields optional)
	if !tbl.IsAppendOnly {
		b.WriteString(fmt.Sprintf("input Update%sInput {\n", structName))
		for _, col := range tbl.Columns {
			if isExcludedFromInput(col) {
				continue
			}
			gqlType := graphqlType(col)
			if gqlType == "" {
				continue
			}
			fieldName := snakeToCamel(col.Name)
			b.WriteString(fmt.Sprintf("  %s: %s\n", fieldName, gqlType))
		}
		b.WriteString("}\n\n")
	}
}

func isExcludedFromInput(col *schema.Column) bool {
	// Exclude PKs, timestamps, FKs (set via nesting), and internal columns
	if col.IsPrimaryKey {
		return true
	}
	if col.Name == "created_at" || col.Name == "updated_at" || col.Name == "deleted_at" {
		return true
	}
	if col.Name == "row_hash" || col.Name == "prev_hash" || col.Name == "version_id" {
		return true
	}
	if col.Type == schema.Binary {
		return true
	}
	if col.Name == "password_hash" || col.Name == "password" {
		return true
	}
	return false
}

// snakeToCamel converts snake_case to camelCase (first letter lowercase).
func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
