package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateGraphQLTypes generates types_gen.go containing GQL response structs,
// connection types, and input structs.
func GenerateGraphQLTypes(tables []*schema.Table, requests []RequestDef, packageName string, relationships ...[]SchemaRelationship) ([]byte, error) {
	return GenerateGraphQLTypesWithPlans(legacyGraphQLModelPlans(tables), requests, packageName, relationships...)
}

// GenerateGraphQLTypesWithPlans generates GraphQL types and field cost metadata
// using operation-level model plans.
func GenerateGraphQLTypesWithPlans(plans []GraphQLModelPlan, requests []RequestDef, packageName string, relationships ...[]SchemaRelationship) ([]byte, error) {
	var tables []*schema.Table
	for _, plan := range plans {
		if plan.Table != nil {
			tables = append(tables, plan.Table)
		}
	}
	reqValMap := BuildRequestValidationMap(requests)
	colValMap := BuildColumnValidationMap(tables)
	valMap := MergeValidationMaps(reqValMap, colValMap)
	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// GQL response types
	for _, tbl := range tables {
		structName := tableToStructName(tbl.Name)
		b.WriteString(fmt.Sprintf("// %sGQL is the GraphQL response type for %s.\n", structName, structName))
		b.WriteString(fmt.Sprintf("type %sGQL struct {\n", structName))
		for _, col := range tbl.Columns {
			if isExcludedFromGraphQL(tbl, col) {
				continue
			}
			goType := graphqlGoSerType(col)
			if goType == "" {
				continue
			}
			fieldName := snakeToPascal(col.Name)
			jsonTag := snakeToCamel(col.Name)
			if col.IsNullable {
				goType = "*" + goType
				jsonTag += ",omitempty"
			}
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, jsonTag))
		}
		b.WriteString("}\n\n")
	}

	// Connection types
	b.WriteString("// PageInfo holds pagination metadata.\n")
	b.WriteString("type PageInfoGQL struct {\n")
	b.WriteString("\tHasNextPage     bool    `json:\"hasNextPage\"`\n")
	b.WriteString("\tHasPreviousPage bool    `json:\"hasPreviousPage\"`\n")
	b.WriteString("\tStartCursor     *string `json:\"startCursor\"`\n")
	b.WriteString("\tEndCursor       *string `json:\"endCursor\"`\n")
	b.WriteString("}\n\n")

	var rels []SchemaRelationship
	if len(relationships) > 0 {
		rels = relationships[0]
	}
	rels = graphQLRelationshipsForPlans(plans, rels)
	writeGraphQLFieldCostRegistration(&b, plans, rels)

	// Input types
	for _, tbl := range tables {
		if tbl.IsImmutable {
			continue
		}
		structName := tableToStructName(tbl.Name)

		// CreateInput
		createInputName := "Create" + structName + "Input"
		b.WriteString(fmt.Sprintf("// %s is the GraphQL input for creating a %s.\n", createInputName, structName))
		b.WriteString(fmt.Sprintf("type %s struct {\n", createInputName))
		for _, col := range tbl.Columns {
			if isExcludedFromInput(col) {
				continue
			}
			goType := graphqlGoSerType(col)
			if goType == "" {
				continue
			}
			fieldName := snakeToPascal(col.Name)
			jsonTag := snakeToCamel(col.Name)
			// Optional fields with defaults
			if col.IsNullable || col.DefaultValue != nil {
				goType = "*" + goType
				jsonTag += ",omitempty"
			}
			valTag := valMap[createInputName+"."+fieldName]
			if valTag != "" {
				b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\" validate:\"%s\"`\n", fieldName, goType, jsonTag, valTag))
			} else {
				b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, jsonTag))
			}
		}
		b.WriteString("}\n\n")

		// UpdateInput (all fields are pointers)
		if !tbl.IsAppendOnly {
			updateInputName := "Update" + structName + "Input"
			b.WriteString(fmt.Sprintf("// %s is the GraphQL input for updating a %s.\n", updateInputName, structName))
			b.WriteString(fmt.Sprintf("type %s struct {\n", updateInputName))
			for _, col := range tbl.Columns {
				if isExcludedFromInput(col) {
					continue
				}
				goType := graphqlGoSerType(col)
				if goType == "" {
					continue
				}
				fieldName := snakeToPascal(col.Name)
				jsonTag := snakeToCamel(col.Name) + ",omitempty"
				valTag := valMap[updateInputName+"."+fieldName]
				if valTag != "" {
					b.WriteString(fmt.Sprintf("\t%s *%s `json:\"%s\" validate:\"%s\"`\n", fieldName, goType, jsonTag, valTag))
				} else {
					b.WriteString(fmt.Sprintf("\t%s *%s `json:\"%s\"`\n", fieldName, goType, jsonTag))
				}
			}
			b.WriteString("}\n\n")
		}
	}

	return format.Source(b.Bytes())
}

func writeGraphQLFieldCostRegistration(b *bytes.Buffer, plans []GraphQLModelPlan, relationships []SchemaRelationship) {
	tableSet := map[string]bool{}
	planByTable := map[string]GraphQLModelPlan{}
	var tables []*schema.Table
	for _, plan := range plans {
		if plan.Table == nil {
			continue
		}
		tables = append(tables, plan.Table)
		tableSet[plan.Table.Name] = true
		planByTable[plan.Table.Name] = plan
	}

	b.WriteString("func init() {\n")
	b.WriteString("\tregisterGraphQLFieldCosts(map[string]FieldCost{\n")
	for _, tbl := range tables {
		structName := tableToStructName(tbl.Name)
		if operationAllowed(planByTable[tbl.Name], "list") {
			fieldName := snakeToCamel(tbl.Name)
			b.WriteString(fmt.Sprintf("\t\t%q: {TypeName: \"Query\", FieldName: %q, BaseCost: 1, IsList: true, DefaultLimit: defaultGraphQLPageSize, MaxLimit: maxGraphQLPageSize},\n", "Query."+fieldName, fieldName))
		}
		if operationAllowed(planByTable[tbl.Name], "show") {
			fieldName := snakeToCamel(strings.TrimSuffix(tbl.Name, "s"))
			b.WriteString(fmt.Sprintf("\t\t%q: {TypeName: \"Query\", FieldName: %q, BaseCost: 1},\n", "Query."+fieldName, fieldName))
		}
		for _, col := range tbl.Columns {
			if isExcludedFromGraphQL(tbl, col) || graphqlGoSerType(col) == "" {
				continue
			}
			fieldName := snakeToCamel(col.Name)
			key := structName + "." + fieldName
			b.WriteString(fmt.Sprintf("\t\t%q: {TypeName: %q, FieldName: %q, BaseCost: 1},\n", key, structName, fieldName))
		}
	}
	for _, rel := range relationships {
		if !tableSet[rel.ParentTable] || !tableSet[rel.ChildTable] {
			continue
		}
		parent := tableToStructName(rel.ParentTable)
		fieldName := snakeToCamel(rel.ChildTable)
		key := parent + "." + fieldName
		baseCost := 5
		maxLimit := "maxGraphQLPageSize"
		isList := "false"
		if rel.Type == "has_many" {
			baseCost = 10
			isList = "true"
		}
		if override, ok := planByTable[rel.ParentTable].Relationships[fieldName]; ok {
			if override.Cost > 0 {
				baseCost = override.Cost
			}
			if override.MaxPageSize > 0 {
				maxLimit = fmt.Sprintf("%d", override.MaxPageSize)
			}
		}
		b.WriteString(fmt.Sprintf("\t\t%q: {TypeName: %q, FieldName: %q, BaseCost: %d, IsList: %s, IsRelation: true, DefaultLimit: defaultGraphQLPageSize, MaxLimit: %s},\n", key, parent, fieldName, baseCost, isList, maxLimit))
	}
	b.WriteString("\t})\n")
	b.WriteString("}\n\n")
}
