package generator

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/shortontech/pickle/pkg/schema"
)

func TestGenerateModelUsers(t *testing.T) {
	tbl := &schema.Table{Name: "users"}
	tbl.UUID("id").PrimaryKey().Default("uuid_generate_v7()")
	tbl.String("name", 255).NotNull()
	tbl.String("email", 255).NotNull().Unique()
	tbl.String("password", 255).NotNull()
	tbl.Timestamps()

	out, err := GenerateModel(tbl, "models")
	if err != nil {
		t.Fatalf("GenerateModel: %v", err)
	}

	src := string(out)

	// Verify it parses as valid Go
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "user.go", src, 0); err != nil {
		t.Fatalf("generated code does not parse: %v\n%s", err, src)
	}

	// Check struct name
	if !strings.Contains(src, "type User struct") {
		t.Errorf("missing struct declaration\n%s", src)
	}

	// Check fields
	for _, field := range []string{"ID", "Name", "Email", "Password", "CreatedAt", "UpdatedAt"} {
		if !strings.Contains(src, field) {
			t.Errorf("missing field %s\n%s", field, src)
		}
	}

	// Check uuid import
	if !strings.Contains(src, `"github.com/google/uuid"`) {
		t.Errorf("missing uuid import\n%s", src)
	}

	// Check generated header
	if !strings.Contains(src, "Code generated by Pickle. DO NOT EDIT.") {
		t.Errorf("missing generated header\n%s", src)
	}
}

func TestGenerateModelNullableFields(t *testing.T) {
	tbl := &schema.Table{Name: "transfers"}
	tbl.UUID("id").PrimaryKey()
	tbl.String("status").NotNull()
	tbl.String("brale_transfer_id", 255).Nullable()
	tbl.String("processor_order_id", 255).Nullable()
	tbl.JSONB("metadata").Nullable()
	tbl.Timestamps()

	out, err := GenerateModel(tbl, "models")
	if err != nil {
		t.Fatalf("GenerateModel: %v", err)
	}

	src := string(out)

	// Verify valid Go
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "transfer.go", src, 0); err != nil {
		t.Fatalf("generated code does not parse: %v\n%s", err, src)
	}

	// Nullable strings should be pointers
	if !strings.Contains(src, "BraleTransferID  *string") {
		t.Errorf("expected *string for nullable string\n%s", src)
	}

	// Nullable JSONB should be pointer
	if !strings.Contains(src, "*json.RawMessage") {
		t.Errorf("expected *json.RawMessage for nullable JSONB\n%s", src)
	}

	// Nullable fields should have omitempty
	if !strings.Contains(src, `json:"brale_transfer_id,omitempty"`) {
		t.Errorf("expected omitempty on nullable field\n%s", src)
	}

	// Non-nullable should not have omitempty
	if strings.Contains(src, `json:"status,omitempty"`) {
		t.Errorf("non-nullable field should not have omitempty\n%s", src)
	}
}

func TestGenerateModelNullableEncryptedFields(t *testing.T) {
	// A nullable .Sealed()/.Encrypted() column produces a pointer plaintext field
	// (*string). The generated Marshal/Unmarshal closures must be type-correct for
	// the pointer (regression: they used to emit `field = string(b)` on a *string,
	// which fails to compile).
	tbl := &schema.Table{Name: "connections"}
	tbl.UUID("id").PrimaryKey()
	tbl.Text("access_token").NotNull().Sealed()   // non-nullable -> string
	tbl.Text("refresh_token").Nullable().Sealed() // nullable -> *string
	tbl.Timestamps()

	out, err := GenerateModel(tbl, "models")
	if err != nil {
		t.Fatalf("GenerateModel: %v", err)
	}
	src := string(out)

	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "connection.go", src, 0); err != nil {
		t.Fatalf("generated code does not parse: %v\n%s", err, src)
	}

	// Nullable plaintext field is a pointer.
	if !strings.Contains(src, "RefreshToken            *string") &&
		!strings.Contains(src, "RefreshToken  *string") {
		// tolerate gofmt alignment differences
		if !strings.Contains(src, "*string") {
			t.Errorf("expected *string plaintext field for nullable sealed column\n%s", src)
		}
	}

	// Nullable Unmarshal must allocate and take the address — never assign a
	// string directly to the *string field.
	if !strings.Contains(src, "c.RefreshToken = &s") {
		t.Errorf("nullable Unmarshal should allocate (&s), got:\n%s", src)
	}
	if strings.Contains(src, "c.RefreshToken = string(b)") {
		t.Errorf("nullable Unmarshal assigns string to *string (won't compile):\n%s", src)
	}
	// Nullable Marshal must nil-check (NULL stays NULL) and deref the pointer.
	if !strings.Contains(src, "if c.RefreshToken == nil {") {
		t.Errorf("nullable Marshal should nil-check the pointer, got:\n%s", src)
	}
	if !strings.Contains(src, "fmt.Sprint(*c.RefreshToken)") {
		t.Errorf("nullable Marshal should deref the pointer, got:\n%s", src)
	}

	// Non-nullable path unchanged.
	if !strings.Contains(src, "c.AccessToken = string(b)") {
		t.Errorf("non-nullable Unmarshal should assign string directly, got:\n%s", src)
	}
}

func TestGenerateModelDecimal(t *testing.T) {
	tbl := &schema.Table{Name: "transfers"}
	tbl.Decimal("amount", 18, 2).NotNull()

	out, err := GenerateModel(tbl, "models")
	if err != nil {
		t.Fatalf("GenerateModel: %v", err)
	}

	src := string(out)

	if !strings.Contains(src, "decimal.Decimal") {
		t.Errorf("expected decimal.Decimal type\n%s", src)
	}
	if !strings.Contains(src, `"github.com/shopspring/decimal"`) {
		t.Errorf("expected decimal import\n%s", src)
	}
}
