package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"text/template"

	"github.com/shortontech/pickle/pkg/schema"
)

var modelTemplate = template.Must(template.New("model").Parse(`// Code generated by Pickle. DO NOT EDIT.
package {{ .Package }}
{{ if .Imports }}
import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
)
{{ end }}
type {{ .StructName }} struct {
{{- range .Fields }}
	{{ .Name }} {{ .Type }} ` + "`" + `json:"{{ .JSONTag }}" db:"{{ .DBTag }}"` + "`" + `
{{- end }}
}
{{ if .PublicFields }}
// {{ .StructName }}Public is a projection of {{ .StructName }} without sensitive fields.
type {{ .StructName }}Public struct {
{{- range .PublicFields }}
	{{ .Name }} {{ .Type }} ` + "`" + `json:"{{ .JSONTag }}"` + "`" + `
{{- end }}
}

// Public returns a {{ .StructName }}Public with sensitive fields stripped.
func (m *{{ .StructName }}) Public() {{ .StructName }}Public {
	return {{ .StructName }}Public{
{{- range .PublicFields }}
		{{ .Name }}: m.{{ .Name }},
{{- end }}
	}
}

// Public{{ .StructName }}s converts a slice of {{ .StructName }} to a slice of {{ .StructName }}Public.
func Public{{ .StructName }}s(records []{{ .StructName }}) []{{ .StructName }}Public {
	result := make([]{{ .StructName }}Public, len(records))
	for i := range records {
		result[i] = records[i].Public()
	}
	return result
}
{{ end }}
`))

type modelData struct {
	Package      string
	StructName   string
	Imports      []string
	Fields       []fieldData
	PublicFields []fieldData // non-nil only when model has hidden fields
}

type fieldData struct {
	Name    string
	Type    string
	JSONTag string
	DBTag   string
}

// GenerateModel produces a Go source file containing the model struct for a table.
func GenerateModel(table *schema.Table, packageName string) ([]byte, error) {
	imports := map[string]bool{}
	var fields []fieldData

	for _, col := range table.Columns {
		goType := columnGoType(col)
		if imp := columnImport(col); imp != "" {
			imports[imp] = true
		}

		jsonTag := col.Name
		if col.Name == "password" || col.Name == "password_hash" {
			jsonTag = "-"
		} else if col.IsNullable {
			jsonTag += ",omitempty"
		}

		fields = append(fields, fieldData{
			Name:    snakeToPascal(col.Name),
			Type:    goType,
			JSONTag: jsonTag,
			DBTag:   col.Name,
		})
	}

	var sortedImports []string
	for imp := range imports {
		sortedImports = append(sortedImports, imp)
	}
	sort.Strings(sortedImports)

	// Separate stdlib and third-party imports
	var stdImports, extImports []string
	for _, imp := range sortedImports {
		if strings.Contains(imp, ".") {
			extImports = append(extImports, imp)
		} else {
			stdImports = append(stdImports, imp)
		}
	}
	orderedImports := append(stdImports, extImports...)

	// Collect public (non-hidden) fields for the Public projection
	var publicFields []fieldData
	hasHidden := false
	for _, f := range fields {
		if f.JSONTag == "-" {
			hasHidden = true
		} else {
			publicFields = append(publicFields, f)
		}
	}

	data := modelData{
		Package:    packageName,
		StructName: tableToStructName(table.Name),
		Imports:    orderedImports,
		Fields:     fields,
	}
	if hasHidden {
		data.PublicFields = publicFields
	}

	var buf bytes.Buffer
	if err := modelTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("template execution: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("go format: %w", err)
	}

	return formatted, nil
}
