package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"text/template"

	"github.com/shortontech/pickle/pkg/schema"
)

var modelTemplate = template.Must(template.New("model").Parse(`// Code generated by Pickle. DO NOT EDIT.
package {{ .Package }}
{{ if .Imports }}
import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
)
{{ end }}
type {{ .StructName }} struct {
{{- range .Fields }}
	{{ .Name }} {{ .Type }} ` + "`" + `json:"{{ .JSONTag }}" db:"{{ .DBTag }}"` + "`" + `
{{- end }}
}
{{ if .IsImmutable }}
// CreatedAt returns the time this record was first created, extracted from
// the UUID v7 timestamp in ID. Not a database column — never stored.
func (m *{{ .StructName }}) CreatedAt() time.Time {
	return uuidV7Time([16]byte(m.ID))
}

// UpdatedAt returns the time this version was created, extracted from
// the UUID v7 timestamp in VersionID. Not a database column — never stored.
func (m *{{ .StructName }}) UpdatedAt() time.Time {
	return uuidV7Time([16]byte(m.VersionID))
}
{{ end }}{{ if .IsAppendOnly }}
// CreatedAt returns the time this record was created, extracted from
// the UUID v7 timestamp in ID. Not a database column — never stored.
func (m *{{ .StructName }}) CreatedAt() time.Time {
	return uuidV7Time([16]byte(m.ID))
}
{{ end }}
{{ if .OwnerField }}
// OwnerID returns the ID of the user who owns this record.
func (m *{{ .StructName }}) OwnerID() string {
	return m.{{ .OwnerField }}.String()
}
{{ end }}
{{ if .PublicFields }}
// {{ .StructName }}Public is a projection of {{ .StructName }} without sensitive fields.
type {{ .StructName }}Public struct {
{{- range .PublicFields }}
	{{ .Name }} {{ .Type }} ` + "`" + `json:"{{ .JSONTag }}"` + "`" + `
{{- end }}
}

// Public returns a {{ .StructName }}Public with sensitive fields stripped.
func (m *{{ .StructName }}) Public() {{ .StructName }}Public {
	return {{ .StructName }}Public{
{{- range .PublicFields }}
		{{ .Name }}: m.{{ .Name }},
{{- end }}
	}
}

// Public{{ .StructName }}s converts a slice of {{ .StructName }} to a slice of {{ .StructName }}Public.
func Public{{ .StructName }}s(records []{{ .StructName }}) []{{ .StructName }}Public {
	result := make([]{{ .StructName }}Public, len(records))
	for i := range records {
		result[i] = records[i].Public()
	}
	return result
}
{{ end }}
`))

type modelData struct {
	Package      string
	StructName   string
	Imports      []string
	Fields       []fieldData
	PublicFields []fieldData // non-nil only when model has hidden fields
	IsImmutable  bool
	IsAppendOnly bool
	OwnerField   string // Go field name of the IsOwner column, if any
}

type fieldData struct {
	Name    string
	Type    string
	JSONTag string
	DBTag   string
}

// GenerateModel produces a Go source file containing the model struct for a table.
func GenerateModel(table *schema.Table, packageName string) ([]byte, error) {
	imports := map[string]bool{}
	var fields []fieldData

	type encFieldInfo struct {
		FieldName     string // Go field name (e.g. "Email")
		SnakeName     string // original column name (e.g. "email")
		GoType        string // Go type (e.g. "string")
		Deterministic bool   // true = AES-SIV (.Encrypted()), false = AES-GCM (.Sealed())
	}
	var encFields []encFieldInfo

	for _, col := range table.Columns {
		goType := columnGoType(col)
		if imp := columnImport(col); imp != "" {
			imports[imp] = true
		}

		jsonTag := col.Name
		if col.Name == "password" || col.Name == "password_hash" ||
			col.Name == "row_hash" || col.Name == "prev_hash" {
			jsonTag = "-"
		} else if col.IsNullable {
			jsonTag += ",omitempty"
		}

		if col.IsEncrypted || col.IsSealed {
			// The Go struct field retains the original name with db:"-"
			fields = append(fields, fieldData{
				Name:    snakeToPascal(col.Name),
				Type:    goType,
				JSONTag: jsonTag,
				DBTag:   "-",
			})
			// Add _encrypted column (TEXT, same nullability)
			encColName := col.Name + "_encrypted"
			encType := "string"
			encJSONTag := "-"
			if col.IsNullable {
				encType = "*string"
			}
			fields = append(fields, fieldData{
				Name:    snakeToPascal(encColName),
				Type:    encType,
				JSONTag: encJSONTag,
				DBTag:   encColName,
			})
			// Add _encrypted_v2 column (TEXT, always nullable)
			v2ColName := col.Name + "_encrypted_v2"
			fields = append(fields, fieldData{
				Name:    snakeToPascal(v2ColName),
				Type:    "*string",
				JSONTag: "-",
				DBTag:   v2ColName,
			})
			encFields = append(encFields, encFieldInfo{
				FieldName:     snakeToPascal(col.Name),
				SnakeName:     col.Name,
				GoType:        goType,
				Deterministic: col.IsEncrypted,
			})
		} else {
			fields = append(fields, fieldData{
				Name:    snakeToPascal(col.Name),
				Type:    goType,
				JSONTag: jsonTag,
				DBTag:   col.Name,
			})
		}
	}

	// Immutable/append-only tables need time for CreatedAt()/UpdatedAt() methods
	if table.IsImmutable || table.IsAppendOnly {
		imports["time"] = true
	}

	// Encrypted/sealed fields need fmt for Sprint in Marshal
	if len(encFields) > 0 {
		imports["fmt"] = true
	}

	var sortedImports []string
	for imp := range imports {
		sortedImports = append(sortedImports, imp)
	}
	sort.Strings(sortedImports)

	// Separate stdlib and third-party imports
	var stdImports, extImports []string
	for _, imp := range sortedImports {
		if strings.Contains(imp, ".") {
			extImports = append(extImports, imp)
		} else {
			stdImports = append(stdImports, imp)
		}
	}
	orderedImports := append(stdImports, extImports...)

	// Collect public (non-hidden) fields for the Public projection
	var publicFields []fieldData
	hasHidden := false
	for _, f := range fields {
		if f.JSONTag == "-" {
			hasHidden = true
		} else {
			publicFields = append(publicFields, f)
		}
	}

	// Find owner column if present
	var ownerField string
	for _, col := range table.Columns {
		if col.IsOwnerColumn {
			ownerField = snakeToPascal(col.Name)
			break
		}
	}

	data := modelData{
		Package:      packageName,
		StructName:   tableToStructName(table.Name),
		Imports:      orderedImports,
		Fields:       fields,
		IsImmutable:  table.IsImmutable,
		IsAppendOnly: table.IsAppendOnly,
		OwnerField:   ownerField,
	}
	if hasHidden {
		data.PublicFields = publicFields
	}

	var buf bytes.Buffer
	if err := modelTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("template execution: %w", err)
	}

	// Generate encryptedFields() method if there are encrypted/sealed columns
	if len(encFields) > 0 {
		structName := tableToStructName(table.Name)
		receiver := strings.ToLower(structName[:1])
		buf.WriteString(fmt.Sprintf("// encryptedFields returns the column-to-field mappings for encrypted/sealed columns.\n"))
		buf.WriteString(fmt.Sprintf("// Used by the query builder for transparent encrypt on write / decrypt on read.\n"))
		buf.WriteString(fmt.Sprintf("func (%s *%s) encryptedFields() []encryptedFieldMapping {\n", receiver, structName))
		buf.WriteString(fmt.Sprintf("\treturn []encryptedFieldMapping{\n"))
		for _, ef := range encFields {
			buf.WriteString(fmt.Sprintf("\t\t{\n"))
			buf.WriteString(fmt.Sprintf("\t\t\tField:         &%s.%s,\n", receiver, ef.FieldName))
			buf.WriteString(fmt.Sprintf("\t\t\tColumn:        %q,\n", ef.SnakeName+"_encrypted"))
			buf.WriteString(fmt.Sprintf("\t\t\tColumnV2:      %q,\n", ef.SnakeName+"_encrypted_v2"))
			buf.WriteString(fmt.Sprintf("\t\t\tDeterministic: %v,\n", ef.Deterministic))
			marshalExpr := fmt.Sprintf("return []byte(fmt.Sprint(%s.%s)), nil", receiver, ef.FieldName)
			unmarshalExpr := fmt.Sprintf("%s.%s = string(b); return nil", receiver, ef.FieldName)
			buf.WriteString(fmt.Sprintf("\t\t\tMarshal:       func() ([]byte, error) { %s },\n", marshalExpr))
			buf.WriteString(fmt.Sprintf("\t\t\tUnmarshal:     func(b []byte) error { %s },\n", unmarshalExpr))
			buf.WriteString(fmt.Sprintf("\t\t},\n"))
		}
		buf.WriteString(fmt.Sprintf("\t}\n"))
		buf.WriteString(fmt.Sprintf("}\n"))
	}

	// Generate ForRoles and ForOwner serialization methods if table has role visibility
	generateModelRoleViews(&buf, table, tableToStructName(table.Name))

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("go format: %w", err)
	}

	return formatted, nil
}

// generateModelRoleViews emits ForRoles(roles) and ForOwner(roles) serialization
// methods on the model struct. These return a map[string]any containing only the
// fields visible to the given role set.
func generateModelRoleViews(buf *bytes.Buffer, table *schema.Table, structName string) {
	// Collect role visibility info
	hasRoles := false
	for _, col := range table.Columns {
		if len(col.VisibleTo) > 0 {
			hasRoles = true
			break
		}
	}
	if !hasRoles {
		return
	}

	// Build column -> role slugs mapping and public/owner sets
	type colVis struct {
		Name      string
		GoField   string
		IsPublic  bool
		IsOwner   bool
		RoleSlugs map[string]bool
	}
	var cols []colVis
	for _, col := range table.Columns {
		if col.Name == "password" || col.Name == "password_hash" ||
			col.Name == "row_hash" || col.Name == "prev_hash" {
			continue // never serialized
		}
		if col.IsEncrypted || col.IsSealed {
			continue // plaintext field has db:"-", encrypted is json:"-"
		}
		cv := colVis{
			Name:      col.Name,
			GoField:   snakeToPascal(col.Name),
			IsPublic:  col.IsPublic,
			IsOwner:   col.IsOwnerSees,
			RoleSlugs: col.VisibleTo,
		}
		cols = append(cols, cv)
	}

	receiver := strings.ToLower(structName[:1])

	// ForRoles(roles []string) map[string]any
	buf.WriteString(fmt.Sprintf("// ForRoles returns a filtered map of the model's fields visible to the given roles.\n"))
	buf.WriteString(fmt.Sprintf("// Public columns are always included. Manages roles see all fields.\n"))
	buf.WriteString(fmt.Sprintf("func (%s *%s) ForRoles(roles []string) map[string]any {\n", receiver, structName))
	buf.WriteString("\troleSet := map[string]bool{}\n")
	buf.WriteString("\tfor _, r := range roles { roleSet[r] = true }\n")
	buf.WriteString("\tout := map[string]any{}\n")
	for _, cv := range cols {
		if cv.IsPublic {
			buf.WriteString(fmt.Sprintf("\tout[%q] = %s.%s\n", cv.Name, receiver, cv.GoField))
		} else if len(cv.RoleSlugs) > 0 {
			var slugChecks []string
			for slug := range cv.RoleSlugs {
				slugChecks = append(slugChecks, fmt.Sprintf("roleSet[%q]", slug))
			}
			sort.Strings(slugChecks)
			buf.WriteString(fmt.Sprintf("\tif %s {\n", strings.Join(slugChecks, " || ")))
			buf.WriteString(fmt.Sprintf("\t\tout[%q] = %s.%s\n", cv.Name, receiver, cv.GoField))
			buf.WriteString("\t}\n")
		}
		// Non-public, non-role columns are omitted
	}
	buf.WriteString("\treturn out\n")
	buf.WriteString("}\n\n")

	// ForOwner(roles []string) map[string]any
	buf.WriteString(fmt.Sprintf("// ForOwner returns a filtered map including role-visible and OwnerSees fields.\n"))
	buf.WriteString(fmt.Sprintf("func (%s *%s) ForOwner(roles []string) map[string]any {\n", receiver, structName))
	buf.WriteString(fmt.Sprintf("\tout := %s.ForRoles(roles)\n", receiver))
	for _, cv := range cols {
		if cv.IsOwner && !cv.IsPublic {
			buf.WriteString(fmt.Sprintf("\tout[%q] = %s.%s\n", cv.Name, receiver, cv.GoField))
		}
	}
	buf.WriteString("\treturn out\n")
	buf.WriteString("}\n\n")
}
