package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"text/template"

	"github.com/shortontech/pickle/pkg/schema"
)

var modelTemplate = template.Must(template.New("model").Parse(`// Code generated by Pickle. DO NOT EDIT.
package {{ .Package }}
{{ if .Imports }}
import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
)
{{ end }}
type {{ .StructName }} struct {
{{- range .Fields }}
	{{ .Name }} {{ .Type }} ` + "`" + `json:"{{ .JSONTag }}" db:"{{ .DBTag }}"` + "`" + `
{{- end }}
}
`))

type modelData struct {
	Package    string
	StructName string
	Imports    []string
	Fields     []fieldData
}

type fieldData struct {
	Name    string
	Type    string
	JSONTag string
	DBTag   string
}

// GenerateModel produces a Go source file containing the model struct for a table.
func GenerateModel(table *schema.Table, packageName string) ([]byte, error) {
	imports := map[string]bool{}
	var fields []fieldData

	for _, col := range table.Columns {
		goType := columnGoType(col)
		if imp := columnImport(col); imp != "" {
			imports[imp] = true
		}

		jsonTag := col.Name
		if col.Name == "password" || col.Name == "password_hash" {
			jsonTag = "-"
		} else if col.IsNullable {
			jsonTag += ",omitempty"
		}

		fields = append(fields, fieldData{
			Name:    snakeToPascal(col.Name),
			Type:    goType,
			JSONTag: jsonTag,
			DBTag:   col.Name,
		})
	}

	var sortedImports []string
	for imp := range imports {
		sortedImports = append(sortedImports, imp)
	}
	sort.Strings(sortedImports)

	// Separate stdlib and third-party imports
	var stdImports, extImports []string
	for _, imp := range sortedImports {
		if strings.Contains(imp, ".") {
			extImports = append(extImports, imp)
		} else {
			stdImports = append(stdImports, imp)
		}
	}
	orderedImports := append(stdImports, extImports...)

	data := modelData{
		Package:    packageName,
		StructName: tableToStructName(table.Name),
		Imports:    orderedImports,
		Fields:     fields,
	}

	var buf bytes.Buffer
	if err := modelTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("template execution: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("go format: %w", err)
	}

	return formatted, nil
}
