package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
	"text/template"
)

// PolicyFileEntry pairs a policy ID (filename stem) with the struct name.
type PolicyFileEntry struct {
	ID         string // "2026_03_23_100000_create_initial_roles"
	StructName string // "CreateInitialRoles_2026_03_23_100000"
}

// ScanPolicyFiles scans a directory for role policy files (structs embedding Policy).
func ScanPolicyFiles(policiesDir string) ([]PolicyFileEntry, error) {
	return scanPolicyDir(policiesDir, "Policy")
}

// ScanGraphQLPolicyFiles scans a directory for GraphQL policy files (structs embedding GraphQLPolicy).
func ScanGraphQLPolicyFiles(policiesDir string) ([]PolicyFileEntry, error) {
	return scanPolicyDir(policiesDir, "GraphQLPolicy")
}

func scanPolicyDir(dir, embedType string) ([]PolicyFileEntry, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var result []PolicyFileEntry

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}

		stem := strings.TrimSuffix(e.Name(), ".go")
		stem = strings.TrimSuffix(stem, "_gen")
		if !migrationTimestamp.MatchString(stem) && !strings.HasSuffix(e.Name(), "_gen.go") {
			continue
		}

		structNames, err := findEmbeddingStructs(dir, e.Name(), embedType)
		if err != nil {
			return nil, fmt.Errorf("parsing %s: %w", e.Name(), err)
		}
		if len(structNames) == 0 {
			continue
		}

		for _, structName := range structNames {
			id := structNameToMigrationID(structName)
			if id == "" {
				continue
			}
			result = append(result, PolicyFileEntry{
				ID:         id,
				StructName: structName,
			})
		}
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].ID < result[j].ID
	})

	return result, nil
}

// findEmbeddingStructs returns all struct names in a file that embed the given type.
func findEmbeddingStructs(dir, filename, embedType string) ([]string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, fmt.Sprintf("%s/%s", dir, filename), nil, 0)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range st.Fields.List {
				if len(field.Names) == 0 {
					if ident, ok := field.Type.(*ast.Ident); ok && ident.Name == embedType {
						names = append(names, ts.Name.Name)
					}
				}
			}
		}
	}
	return names, nil
}

var rolePolicyRegistryTemplate = template.Must(template.New("policy_registry").Parse(`// Code generated by Pickle. DO NOT EDIT.
package {{ .Package }}

// PolicyRegistry is the ordered list of role policies for this project.
var PolicyRegistry = []PolicyEntry{
{{ range .Entries }}	{ID: "{{ .ID }}", Policy: &{{ .StructName }}{}},
{{ end }}}
`))

var graphqlPolicyRegistryTemplate = template.Must(template.New("graphql_policy_registry").Parse(`// Code generated by Pickle. DO NOT EDIT.
package {{ .Package }}

// GraphQLPolicyRegistry is the ordered list of GraphQL policies for this project.
var GraphQLPolicyRegistry = []GraphQLPolicyEntry{
{{ range .Entries }}	{ID: "{{ .ID }}", Policy: &{{ .StructName }}{}},
{{ end }}}
`))

// GeneratePolicyRegistry produces the contents of database/policies/registry_gen.go.
func GeneratePolicyRegistry(pkg string, entries []PolicyFileEntry) ([]byte, error) {
	data := struct {
		Package string
		Entries []PolicyFileEntry
	}{
		Package: pkg,
		Entries: entries,
	}

	var buf bytes.Buffer
	if err := rolePolicyRegistryTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("policy registry template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("go format: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

// GenerateGraphQLPolicyRegistry produces the contents of database/policies/graphql/registry_gen.go.
func GenerateGraphQLPolicyRegistry(pkg string, entries []PolicyFileEntry) ([]byte, error) {
	data := struct {
		Package string
		Entries []PolicyFileEntry
	}{
		Package: pkg,
		Entries: entries,
	}

	var buf bytes.Buffer
	if err := graphqlPolicyRegistryTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("graphql policy registry template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("go format: %w\n%s", err, buf.String())
	}
	return formatted, nil
}
