package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

// RBACGateInput holds the parameters for generating an RBAC gate function.
type RBACGateInput struct {
	ActionName   string
	AllowedRoles []string
	ManagesRoles []string
	SourcePolicy string
	PackageName  string
}

var rbacGateTemplate = template.Must(template.New("rbac_gate").Parse(`// Code generated by Pickle. DO NOT EDIT.
// Source policy: {{ .SourcePolicy }}
package {{ .PackageName }}

import "github.com/google/uuid"

// Can{{ .FuncName }} checks whether the authenticated user is authorised to
// perform the "{{ .ActionName }}" action on the given model. It returns the
// authorising role ID if allowed, or nil if denied.
func Can{{ .FuncName }}(ctx *Context, model interface{ OwnerID() string }) *uuid.UUID {
	{{- if .ManagesRoles }}
	// Manages roles — full access
	if ctx.HasAnyRole({{ .ManagesRolesLit }}) {
		id := uuid.New()
		return &id
	}
	{{- end }}
	{{- if .AllowedRoles }}
	// Specific roles granted "{{ .ActionName }}"
	if ctx.HasAnyRole({{ .AllowedRolesLit }}) {
		id := uuid.New()
		return &id
	}
	{{- end }}
	return nil
}
`))

type rbacGateData struct {
	PackageName    string
	SourcePolicy   string
	ActionName     string
	FuncName       string
	ManagesRoles   []string
	AllowedRoles   []string
	ManagesRolesLit string
	AllowedRolesLit string
}

// GenerateRBACGate produces a gate function for the given action, allowed roles,
// and manages roles. The generated function checks manages roles first, then
// specific allowed roles.
func GenerateRBACGate(actionName string, allowedRoles []string, managesRoles []string, sourcePolicy string, packageName string) ([]byte, error) {
	funcName := gateActionToFuncName(actionName)

	data := rbacGateData{
		PackageName:     packageName,
		SourcePolicy:    sourcePolicy,
		ActionName:      actionName,
		FuncName:        funcName,
		ManagesRoles:    managesRoles,
		AllowedRoles:    allowedRoles,
		ManagesRolesLit: quoteStringSlice(managesRoles),
		AllowedRolesLit: quoteStringSlice(allowedRoles),
	}

	var buf bytes.Buffer
	if err := rbacGateTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing rbac gate template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting rbac gate source: %w", err)
	}
	return formatted, nil
}

// gateActionToFuncName converts an action name like "ban_user" to "BanUser".
func gateActionToFuncName(action string) string {
	parts := strings.Split(action, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// quoteStringSlice returns a Go literal for variadic string args, e.g. `"admin", "mod"`.
func quoteStringSlice(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}
