package generator

import (
	"strings"
	"testing"
)

func TestGenerateRBACGate_Basic(t *testing.T) {
	out, err := GenerateRBACGate(
		"ban_user",
		[]string{"moderator", "support"},
		[]string{"admin"},
		"2026_03_01_create_roles",
		"pickle",
	)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	src := string(out)

	if !strings.Contains(src, "func CanBanUser(") {
		t.Error("expected CanBanUser function declaration")
	}
	if !strings.Contains(src, `"admin"`) {
		t.Error("expected admin in manages roles check")
	}
	if !strings.Contains(src, `"moderator", "support"`) {
		t.Error("expected moderator, support in allowed roles check")
	}
	// Manages check should appear before allowed roles
	managesIdx := strings.Index(src, "Manages roles")
	allowedIdx := strings.Index(src, "Specific roles")
	if managesIdx < 0 || allowedIdx < 0 {
		t.Error("expected both manages and specific role comments")
	}
	if managesIdx > allowedIdx {
		t.Error("manages roles check should come before specific roles check")
	}
}

func TestGenerateRBACGate_NoManagesRoles(t *testing.T) {
	out, err := GenerateRBACGate(
		"edit_post",
		[]string{"editor"},
		nil,
		"2026_03_01_create_roles",
		"models",
	)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	src := string(out)

	if !strings.Contains(src, "func CanEditPost(") {
		t.Error("expected CanEditPost function declaration")
	}
	if strings.Contains(src, "Manages roles") {
		t.Error("expected no manages roles block when none provided")
	}
	if !strings.Contains(src, `"editor"`) {
		t.Error("expected editor in allowed roles check")
	}
}

func TestGenerateRBACGate_NoAllowedRoles(t *testing.T) {
	out, err := GenerateRBACGate(
		"delete",
		nil,
		[]string{"superadmin"},
		"2026_03_01_create_roles",
		"pickle",
	)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	src := string(out)

	if !strings.Contains(src, "func CanDelete(") {
		t.Error("expected CanDelete function declaration")
	}
	if !strings.Contains(src, `"superadmin"`) {
		t.Error("expected superadmin in manages roles")
	}
	if strings.Contains(src, "Specific roles") {
		t.Error("expected no specific roles block when none provided")
	}
}

func TestGenerateRBACGate_PackageName(t *testing.T) {
	out, err := GenerateRBACGate("view", []string{"viewer"}, nil, "policy1", "mypkg")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(string(out), "package mypkg") {
		t.Error("expected package mypkg")
	}
}

func TestGenerateRBACGate_GeneratedHeader(t *testing.T) {
	out, err := GenerateRBACGate("view", []string{"viewer"}, nil, "policy1", "pickle")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(string(out), "Code generated by Pickle. DO NOT EDIT.") {
		t.Error("expected generated header")
	}
}

func TestGateActionToFuncName(t *testing.T) {
	tests := []struct {
		input, want string
	}{
		{"ban_user", "BanUser"},
		{"delete", "Delete"},
		{"edit_post", "EditPost"},
		{"view", "View"},
		{"create_draft_post", "CreateDraftPost"},
	}
	for _, tt := range tests {
		got := gateActionToFuncName(tt.input)
		if got != tt.want {
			t.Errorf("gateActionToFuncName(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}
