package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateRowPolicyRegistry emits desired PostgreSQL RLS state into the
// generated policy package. The policy runner reconciles it only during an
// explicit policy migration command.
func GenerateRowPolicyRegistry(packageName string, plans []PostgresRowPolicyPlan) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\npackage " + packageName + "\n\n")
	b.WriteString("var GeneratedRowPolicyDDL = []string{\n")
	for _, helper := range PostgresPolicyIdentityHelpers() {
		fmt.Fprintf(&b, "\t%s,\n", strconv.Quote(helper))
	}
	for _, plan := range plans {
		table := quotePolicyIdent(plan.Table)
		if plan.Enable {
			fmt.Fprintf(&b, "\t%s,\n", strconv.Quote("ALTER TABLE "+table+" ENABLE ROW LEVEL SECURITY"))
		}
		if plan.Force {
			fmt.Fprintf(&b, "\t%s,\n", strconv.Quote("ALTER TABLE "+table+" FORCE ROW LEVEL SECURITY"))
		}
		for _, policy := range plan.Policies {
			fmt.Fprintf(&b, "\t%s,\n", strconv.Quote("DROP POLICY IF EXISTS "+quotePolicyIdent(policy.Name)+" ON "+table))
			q := "CREATE POLICY " + quotePolicyIdent(policy.Name) + " ON " + table + " FOR " + string(policy.Command) + " TO PUBLIC"
			if policy.Using != "" {
				q += " USING (" + policy.Using + ")"
			}
			if policy.WithCheck != "" {
				q += " WITH CHECK (" + policy.WithCheck + ")"
			}
			fmt.Fprintf(&b, "\t%s,\n", strconv.Quote(q))
		}
	}
	b.WriteString("}\n\nvar GeneratedRowPolicyDesired = map[string][]string{\n")
	for _, plan := range plans {
		names := make([]string, len(plan.Policies))
		for i, p := range plan.Policies {
			names[i] = p.Name
		}
		sort.Strings(names)
		fmt.Fprintf(&b, "\t%s: {", strconv.Quote(plan.Table))
		for i, name := range names {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(name))
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting row policy registry: %w\n%s", err, b.String())
	}
	return src, nil
}

func GenerateRowPolicyRuntimeRegistry(packageName string, policies []ResolvedRowPolicy) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\npackage " + packageName + "\n\nfunc init() {\n")
	for _, resolved := range policies {
		fmt.Fprintf(&b, "\tregisterRowPolicyRuntime(rowPolicyRuntimeDefinition{Table: %s, SubjectCombination: %s, EnforcementClass: %s, Identities: []string{", strconv.Quote(resolved.Protection.Table), strconv.Quote(string(resolved.Protection.SubjectCombination)), strconv.Quote(resolved.EnforcementClass))
		identityNames := make([]string, 0, len(resolved.Identities))
		for name := range resolved.Identities {
			identityNames = append(identityNames, name)
		}
		sort.Strings(identityNames)
		for i, name := range identityNames {
			if i > 0 {
				b.WriteString(",")
			}
			b.WriteString(strconv.Quote(name))
		}
		b.WriteString("}, Rules: []rowPolicyRuntimeRule{\n")
		for _, rule := range resolved.Protection.Rules {
			fmt.Fprintf(&b, "\t\t{Key:%s, SubjectKind:%s, SubjectName:%s", strconv.Quote(rule.Key), strconv.Quote(string(rule.Subject.Kind)), strconv.Quote(rule.Subject.Name))
			writeRuntimePredicateField(&b, "Select", rule.Select)
			writeRuntimePredicateField(&b, "Insert", rule.Insert)
			writeRuntimePredicateField(&b, "UpdateOld", rule.UpdateOld)
			writeRuntimePredicateField(&b, "UpdateNew", rule.UpdateNew)
			writeRuntimePredicateField(&b, "Delete", rule.Delete)
			b.WriteString("},\n")
		}
		b.WriteString("\t}})\n")
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting row policy runtime registry: %w\n%s", err, b.String())
	}
	return src, nil
}

func writeRuntimePredicateField(b *bytes.Buffer, name string, predicate *schema.RowPredicate) {
	if predicate == nil {
		return
	}
	fmt.Fprintf(b, ", %s: &", name)
	writeRuntimePredicate(b, *predicate)
}
func writeRuntimePredicate(b *bytes.Buffer, p schema.RowPredicate) {
	fmt.Fprintf(b, "rowPolicyRuntimePredicate{Kind:%s, Name:%s", strconv.Quote(string(p.Kind)), strconv.Quote(p.Name))
	if len(p.Children) > 0 {
		b.WriteString(", Children: []rowPolicyRuntimePredicate{")
		for _, child := range p.Children {
			writeRuntimePredicate(b, child)
			b.WriteString(",")
		}
		b.WriteString("}")
	}
	b.WriteString("}")
}

func GeneratedRowPolicyFingerprint(plans []PostgresRowPolicyPlan) string {
	var parts []string
	for _, plan := range plans {
		for _, policy := range plan.Policies {
			parts = append(parts, plan.Table+":"+policy.Name+":"+string(policy.Command)+":"+policy.Using+":"+policy.WithCheck)
		}
	}
	sort.Strings(parts)
	return generatedRowPolicyName(strings.Join(parts, "|"), "state")
}
