package generator

import (
	"strings"
	"testing"
)

func TestGenerateSchemaInspector(t *testing.T) {
	migrations := []MigrationEntry{
		{StructName: "CreateUsersTable_2026_02_21_100000"},
		{StructName: "CreatePostsTable_2026_02_21_100001"},
	}

	out, err := GenerateSchemaInspector("github.com/example/myapp/migrations", migrations)
	if err != nil {
		t.Fatalf("GenerateSchemaInspector: %v", err)
	}

	src := string(out)

	// Check it imports the project's migrations package
	if !strings.Contains(src, `"github.com/example/myapp/migrations"`) {
		t.Errorf("missing migrations import\n%s", src)
	}

	// Check it references both migration structs
	if !strings.Contains(src, "migrations.CreateUsersTable_2026_02_21_100000") {
		t.Errorf("missing users migration\n%s", src)
	}
	if !strings.Contains(src, "migrations.CreatePostsTable_2026_02_21_100001") {
		t.Errorf("missing posts migration\n%s", src)
	}

	// Check it supports --json flag
	if !strings.Contains(src, `"--json"`) {
		t.Errorf("missing --json flag support\n%s", src)
	}

	// Check generated header
	if !strings.Contains(src, "Code generated by Pickle. DO NOT EDIT.") {
		t.Errorf("missing generated header\n%s", src)
	}
}

func TestGenerateSchemaInspectorSortsAlphabetically(t *testing.T) {
	migrations := []MigrationEntry{
		{StructName: "CreatePostsTable_2026_02_21_100001"},
		{StructName: "CreateUsersTable_2026_02_21_100000"},
	}

	out, err := GenerateSchemaInspector("github.com/example/myapp/migrations", migrations)
	if err != nil {
		t.Fatalf("GenerateSchemaInspector: %v", err)
	}

	src := string(out)
	usersIdx := strings.Index(src, "CreateUsersTable")
	postsIdx := strings.Index(src, "CreatePostsTable")

	if postsIdx > usersIdx {
		t.Error("migrations should be sorted alphabetically (posts before users)")
	}
}
