package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
	"github.com/shortontech/pickle/pkg/tickle"
)

// GenerateQueryScopes produces a Go source file with typed Where*/With* methods
// for a given table, using scope templates parsed from the cooked scopes file.
func GenerateQueryScopes(table *schema.Table, blocks []tickle.ScopeBlock, packageName string) ([]byte, error) {
	columns := tickle.ColumnsFromTable(table)
	structName := tableToStructName(table.Name)
	scopeBody, err := tickle.GenerateScopes(blocks, columns, structName)
	if err != nil {
		return nil, fmt.Errorf("generating scopes for %s: %w", structName, err)
	}

	// Collect imports needed by the generated scopes
	imports := collectScopeImports(table, blocks)

	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		b.WriteString(")\n\n")
	}

	// Generate the model-specific query wrapper type
	queryType := structName + "Query"
	builderType := "QueryBuilder" // mutable by default
	if table.IsImmutable {
		builderType = "ImmutableQueryBuilder"
	}

	b.WriteString(fmt.Sprintf("// %s provides typed query methods for %s.\n", queryType, structName))
	b.WriteString(fmt.Sprintf("type %s struct {\n\t*%s[%s]\n}\n\n", queryType, builderType, structName))

	// Generate a typed Query constructor
	b.WriteString(fmt.Sprintf("// Query%s starts a new query for %s.\n", structName, structName))
	b.WriteString(fmt.Sprintf("func Query%s() *%s {\n", structName, queryType))
	if table.IsImmutable {
		softDeletes := table.HasSoftDelete
		if table.Connection != "" {
			b.WriteString(fmt.Sprintf("\treturn &%s{ImmutableQueryBuilder: ImmutableQuery[%s](%q, %v, %q)}\n", queryType, structName, table.Name, softDeletes, table.Connection))
		} else {
			b.WriteString(fmt.Sprintf("\treturn &%s{ImmutableQueryBuilder: ImmutableQuery[%s](%q, %v)}\n", queryType, structName, table.Name, softDeletes))
		}
	} else {
		if table.Connection != "" {
			b.WriteString(fmt.Sprintf("\treturn &%s{QueryBuilder: Query[%s](%q, %q)}\n", queryType, structName, table.Name, table.Connection))
		} else {
			b.WriteString(fmt.Sprintf("\treturn &%s{QueryBuilder: Query[%s](%q)}\n", queryType, structName, table.Name))
		}
	}
	b.WriteString("}\n\n")

	// Generate eager loading methods from foreign keys
	for _, col := range table.Columns {
		if col.ForeignKeyTable != "" {
			relName := tableToStructName(col.ForeignKeyTable)
			b.WriteString(fmt.Sprintf("func (q *%s) With%s() *%s {\n", queryType, relName, queryType))
			b.WriteString(fmt.Sprintf("\tq.EagerLoad(%q)\n", col.ForeignKeyTable))
			b.WriteString(fmt.Sprintf("\treturn q\n"))
			b.WriteString("}\n\n")
		}
	}

	// Generate ownership scope if table has an owner column
	for _, col := range table.Columns {
		if col.IsOwnerColumn {
			goType := columnGoType(col)
			paramName := "ownerID"
			b.WriteString(fmt.Sprintf("// WhereOwnedBy filters records by the ownership column.\n"))
			b.WriteString(fmt.Sprintf("func (q *%s) WhereOwnedBy(%s %s) *%s {\n", queryType, paramName, goType, queryType))
			b.WriteString(fmt.Sprintf("\tq.where(%q, %s)\n", col.Name, paramName))
			b.WriteString(fmt.Sprintf("\treturn q\n"))
			b.WriteString("}\n\n")
			break
		}
	}

	// Generate chainable wrappers for base builder methods so they
	// return the typed query wrapper instead of the builder type.
	// Immutable tables get these in generateImmutableMethods instead.
	if !table.IsImmutable {
		for _, m := range []struct{ name, sig, call string }{
			{"AnyOwner", "", "AnyOwner()"},
			{"Limit", "n int", "Limit(n)"},
			{"Offset", "n int", "Offset(n)"},
			{"Lock", "", "Lock()"},
			{"LockForUpdate", "", "LockForUpdate()"},
			{"LockForShare", "", "LockForShare()"},
			{"SkipLocked", "", "SkipLocked()"},
			{"NoWait", "", "NoWait()"},
			{"Timeout", "d time.Duration", "Timeout(d)"},
		} {
			b.WriteString(fmt.Sprintf("func (q *%s) %s(%s) *%s {\n", queryType, m.name, m.sig, queryType))
			b.WriteString(fmt.Sprintf("\tq.QueryBuilder.%s\n", m.call))
			b.WriteString(fmt.Sprintf("\treturn q\n"))
			b.WriteString("}\n\n")
		}

		// Generate typed OrderBy methods per column
		generateOrderByMethods(&b, table, queryType, "QueryBuilder")
	}

	// Generate LockInfo() for all table types
	b.WriteString(fmt.Sprintf("// LockInfo returns the current lock status for the %s table.\n", table.Name))
	b.WriteString(fmt.Sprintf("// Queries pg_locks and pg_stat_activity. Use for monitoring, not application logic.\n"))
	b.WriteString(fmt.Sprintf("func (q *%s) LockInfo() (*LockStatus, error) {\n", queryType))
	b.WriteString(fmt.Sprintf("\treturn queryLockInfo(q.db(), %q)\n", table.Name))
	b.WriteString("}\n\n")

	// Generate per-column Select methods
	for _, col := range table.Columns {
		pascal := snakeToPascal(col.Name)
		selectCol := col.Name
		if col.IsEncrypted || col.IsSealed {
			selectCol = col.Name + "_encrypted"
		}
		b.WriteString(fmt.Sprintf("func (q *%s) Select%s() *%s {\n", queryType, pascal, queryType))
		b.WriteString(fmt.Sprintf("\tq.addSelect(%q)\n", selectCol))
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}

	// Generate per-column Sum/Avg methods for numeric columns.
	// Both QueryBuilder and ImmutableQueryBuilder have their own aggregate()
	// method that handles dedup correctly for their table type.
	for _, col := range table.Columns {
		if col.IsEncrypted || col.IsSealed {
			continue // aggregates on ciphertext are meaningless
		}
		scope := tickle.ScopeForType(col.Type)
		if scope != "numeric" {
			continue
		}
		pascal := snakeToPascal(col.Name)
		for _, fn := range []string{"Sum", "Avg"} {
			b.WriteString(fmt.Sprintf("func (q *%s) %s%s() (*float64, error) {\n", queryType, fn, pascal))
			b.WriteString(fmt.Sprintf("\treturn q.aggregate(%q, %q)\n", strings.ToUpper(fn), col.Name))
			b.WriteString("}\n\n")
		}
	}

	// Generate visibility scope methods (SelectPublic, SelectOwner, SelectAll)
	hasVisibility := false
	var publicCols, ownerCols []string
	for _, col := range table.Columns {
		if col.IsPublic {
			publicCols = append(publicCols, col.Name)
			ownerCols = append(ownerCols, col.Name)
			hasVisibility = true
		} else if col.IsOwnerSees {
			ownerCols = append(ownerCols, col.Name)
			hasVisibility = true
		}
	}

	if hasVisibility {
		// SelectPublic
		b.WriteString(fmt.Sprintf("// SelectPublic selects only columns marked Public().\n"))
		b.WriteString(fmt.Sprintf("func (q *%s) SelectPublic() *%s {\n", queryType, queryType))
		b.WriteString(fmt.Sprintf("\tq.selectedCols = []string{"))
		for i, c := range publicCols {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", c))
		}
		b.WriteString("}\n")
		b.WriteString("\tq.setVisibility(visibilityPublic)\n")
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")

		// SelectOwner
		b.WriteString(fmt.Sprintf("// SelectOwner selects columns visible to the resource owner.\n"))
		b.WriteString(fmt.Sprintf("func (q *%s) SelectOwner() *%s {\n", queryType, queryType))
		b.WriteString(fmt.Sprintf("\tq.selectedCols = []string{"))
		for i, c := range ownerCols {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", c))
		}
		b.WriteString("}\n")
		b.WriteString("\tq.setVisibility(visibilityOwner)\n")
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}

	// SelectAll — always generated
	b.WriteString(fmt.Sprintf("// SelectAll selects all columns. Use for internal/admin queries.\n"))
	b.WriteString(fmt.Sprintf("func (q *%s) SelectAll() *%s {\n", queryType, queryType))
	b.WriteString("\tq.setVisibility(visibilityAll)\n")
	b.WriteString(fmt.Sprintf("\treturn q\n"))
	b.WriteString("}\n\n")

	// Generate table-level scopes (FetchResource / FetchResources)
	tableScopeBody := tickle.GenerateTableScopes(blocks, structName, HasOwnership(table))
	b.WriteString(tableScopeBody)

	b.WriteString(scopeBody)

	// Generate Search methods
	generateSearchMethods(&b, table, queryType, structName)

	// Generate immutable table methods
	if table.IsImmutable {
		generateImmutableMethods(&b, table, queryType, structName)
	}

	// Generate append-only table methods
	if table.IsAppendOnly {
		generateAppendOnlyMethods(&b, table, queryType, structName)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("go format: %w\n%s", err, b.String())
	}

	return formatted, nil
}

// generateImmutableMethods emits Create, Update, and Delete (if SoftDeletes)
// for an immutable table's query type. Terminal query methods (All, First, Count,
// AllVersions, aggregate) are provided by ImmutableQueryBuilder itself.
func generateImmutableMethods(b *bytes.Buffer, table *schema.Table, queryType, structName string) {
	softDeletes := table.HasSoftDelete

	// Chainable wrappers that return the typed wrapper
	for _, m := range []struct{ name, sig, call string }{
		{"AllVersions", "", "AllVersions()"},
		{"Limit", "n int", "Limit(n)"},
		{"Offset", "n int", "Offset(n)"},
		{"AnyOwner", "", "AnyOwner()"},
		{"Lock", "", "Lock()"},
		{"LockForUpdate", "", "LockForUpdate()"},
		{"LockForShare", "", "LockForShare()"},
		{"SkipLocked", "", "SkipLocked()"},
		{"NoWait", "", "NoWait()"},
		{"Timeout", "d time.Duration", "Timeout(d)"},
	} {
		b.WriteString(fmt.Sprintf("func (q *%s) %s(%s) *%s {\n", queryType, m.name, m.sig, queryType))
		b.WriteString(fmt.Sprintf("\tq.ImmutableQueryBuilder.%s\n", m.call))
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}

	// Generate typed OrderBy methods per column
	generateOrderByMethods(b, table, queryType, "ImmutableQueryBuilder")

	// Column metadata for hash chain computation
	generateColumnMeta(b, table, structName)

	// Create — generates id, version_id, and hash chain
	b.WriteString(fmt.Sprintf("func (q *%s) Create(model *%s) error {\n", queryType, structName))
	b.WriteString("\tif model.ID == (uuid.UUID{}) {\n\t\tmodel.ID = uuid.Must(uuid.NewV7())\n\t}\n")
	b.WriteString("\tmodel.VersionID = uuid.Must(uuid.NewV7())\n")
	b.WriteString(generateChainHashBlock(table.Name, structName, true))
	b.WriteString("\treturn q.ImmutableQueryBuilder.Create(model)\n}\n\n")

	// Update — version fence + insert new version with same id.
	// Acquires FOR UPDATE on the latest version row to prevent concurrent updates
	// from silently forking. If the version has changed since the caller read it,
	// returns a StaleVersionError.
	b.WriteString(fmt.Sprintf("func (q *%s) Update(model *%s) error {\n", queryType, structName))
	b.WriteString("\tdb := q.db()\n\n")
	// If not in a transaction, start an implicit one
	b.WriteString("\t// Version fence requires a transaction\n")
	b.WriteString("\tif q.ImmutableQueryBuilder.tx == nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn TransactionOn(func() *sql.DB {\n"))
	b.WriteString("\t\t\tif q.ImmutableQueryBuilder.connection != \"\" {\n")
	b.WriteString("\t\t\t\tif conn, ok := Connections[q.ImmutableQueryBuilder.connection]; ok {\n")
	b.WriteString("\t\t\t\t\treturn conn\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\treturn DB\n")
	b.WriteString("\t\t}(), func(tx *Tx) error {\n")
	b.WriteString(fmt.Sprintf("\t\t\ttxQ := tx.Query%s()\n", structName))
	b.WriteString("\t\t\treturn txQ.Update(model)\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n\n")
	// Version fence: SELECT version_id FOR UPDATE, compare
	b.WriteString("\tvar currentVersionID uuid.UUID\n")
	b.WriteString(fmt.Sprintf("\terr := db.QueryRow(\"SELECT version_id FROM %s WHERE id = $1 ORDER BY version_id DESC LIMIT 1 FOR UPDATE\", model.ID).Scan(&currentVersionID)\n", table.Name))
	b.WriteString("\tif err != nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn mapLockError(%q, err)\n", table.Name))
	b.WriteString("\t}\n")
	b.WriteString("\tif currentVersionID != model.VersionID {\n")
	b.WriteString(fmt.Sprintf("\t\treturn &StaleVersionError{\n"))
	b.WriteString(fmt.Sprintf("\t\t\tTable:           %q,\n", table.Name))
	b.WriteString("\t\t\tEntityID:        model.ID.String(),\n")
	b.WriteString("\t\t\tExpectedVersion: model.VersionID.String(),\n")
	b.WriteString("\t\t\tActualVersion:   currentVersionID.String(),\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tmodel.VersionID = uuid.Must(uuid.NewV7())\n")
	b.WriteString(generateChainHashBlock(table.Name, structName, true))
	b.WriteString("\treturn q.ImmutableQueryBuilder.Create(model)\n}\n\n")

	// Delete — only if SoftDeletes
	if softDeletes {
		b.WriteString(fmt.Sprintf("func (q *%s) Delete(model *%s) error {\n", queryType, structName))
		b.WriteString("\tnow := time.Now()\n\tmodel.DeletedAt = &now\n")
		b.WriteString("\tmodel.VersionID = uuid.Must(uuid.NewV7())\n")
		b.WriteString(generateChainHashBlock(table.Name, structName, true))
		b.WriteString("\treturn q.ImmutableQueryBuilder.Create(model)\n}\n\n")
	}

	// VerifyChain and VerifyRow
	generateVerifyMethods(b, table, queryType, structName, true)
}

// generateAppendOnlyMethods emits a Create override (with UUID generation and
// hash chain) for an append-only table. No Update, no Delete — records are permanent.
func generateAppendOnlyMethods(b *bytes.Buffer, table *schema.Table, queryType, structName string) {
	// Column metadata for hash chain
	generateColumnMeta(b, table, structName)

	// Create override — generates id + hash chain
	b.WriteString(fmt.Sprintf("func (q *%s) Create(model *%s) error {\n", queryType, structName))
	b.WriteString("\tif model.ID == (uuid.UUID{}) {\n\t\tmodel.ID = uuid.Must(uuid.NewV7())\n\t}\n")
	b.WriteString(generateChainHashBlock(table.Name, structName, false))
	b.WriteString("\treturn q.QueryBuilder.Create(model)\n}\n\n")

	// VerifyChain and VerifyRow
	generateVerifyMethods(b, table, queryType, structName, false)
}

// GenerateViewQueryScopes produces a Go source file with typed Where* methods
// for a view. The query wrapper is read-only — no Create/Update/Delete.
func GenerateViewQueryScopes(view *schema.View, blocks []tickle.ScopeBlock, packageName string) ([]byte, error) {
	// Build columns from view columns
	var columns []tickle.ColumnDef
	for _, vc := range view.Columns {
		col := &vc.Column
		col.Name = vc.OutputName()
		columns = append(columns, tickle.ColumnDef{
			PascalName: snakeToPascal(col.Name),
			SnakeName:  col.Name,
			GoType:     columnGoType(col),
			Scope:      tickle.ScopeForType(col.Type),
		})
	}

	structName := tableToStructName(view.Name)
	scopeBody, err := tickle.GenerateScopes(blocks, columns, structName)
	if err != nil {
		return nil, fmt.Errorf("generating scopes for view %s: %w", structName, err)
	}

	imports := collectViewScopeImports(view, blocks)

	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		b.WriteString(")\n\n")
	}

	queryType := structName + "Query"
	b.WriteString(fmt.Sprintf("// %s provides read-only typed query methods for the %s view.\n", queryType, view.Name))
	b.WriteString(fmt.Sprintf("type %s struct {\n\t*QueryBuilder[%s]\n}\n\n", queryType, structName))

	b.WriteString(fmt.Sprintf("// Query%s starts a new read-only query for %s.\n", structName, structName))
	b.WriteString(fmt.Sprintf("func Query%s() *%s {\n", structName, queryType))
	b.WriteString(fmt.Sprintf("\treturn &%s{QueryBuilder: Query[%s](%q)}\n", queryType, structName, view.Name))
	b.WriteString("}\n\n")

	// Generate chainable wrappers for base QueryBuilder methods.
	for _, m := range []struct{ name, sig, call string }{
		{"Limit", "n int", "Limit(n)"},
		{"Offset", "n int", "Offset(n)"},
	} {
		b.WriteString(fmt.Sprintf("func (q *%s) %s(%s) *%s {\n", queryType, m.name, m.sig, queryType))
		b.WriteString(fmt.Sprintf("\tq.QueryBuilder.%s\n", m.call))
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}

	// Generate typed OrderBy methods per view column
	for _, vc := range view.Columns {
		col := &vc.Column
		colName := vc.OutputName()
		pascal := snakeToPascal(colName)
		if col.IsEncrypted || col.IsSealed {
			continue
		}
		b.WriteString(fmt.Sprintf("// OrderBy%s orders results by the %s column.\n", pascal, colName))
		b.WriteString(fmt.Sprintf("func (q *%s) OrderBy%s(direction string) *%s {\n", queryType, pascal, queryType))
		b.WriteString(fmt.Sprintf("\tq.QueryBuilder.OrderBy(%q, direction)\n", colName))
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}

	b.WriteString(scopeBody)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("go format: %w\n%s", err, b.String())
	}

	return formatted, nil
}

func collectViewScopeImports(view *schema.View, blocks []tickle.ScopeBlock) []string {
	imports := map[string]bool{}

	hasTimestamp := false
	hasUUID := false
	hasDecimal := false
	hasJSONB := false

	for _, vc := range view.Columns {
		switch vc.Type {
		case schema.Timestamp, schema.Date:
			hasTimestamp = true
		case schema.UUID:
			hasUUID = true
		case schema.Decimal:
			hasDecimal = true
		case schema.JSONB:
			hasJSONB = true
		}
	}

	for _, block := range blocks {
		if block.Scope == "timestamp" && hasTimestamp {
			imports["time"] = true
		}
	}

	if hasUUID {
		imports["github.com/google/uuid"] = true
	}
	if hasDecimal {
		imports["github.com/shopspring/decimal"] = true
	}
	if hasTimestamp {
		imports["time"] = true
	}
	if hasJSONB {
		imports["encoding/json"] = true
	}

	var sorted []string
	for imp := range imports {
		sorted = append(sorted, imp)
	}

	var std, ext []string
	for _, imp := range sorted {
		if strings.Contains(imp, ".") {
			ext = append(ext, imp)
		} else {
			std = append(std, imp)
		}
	}
	return append(std, ext...)
}

func collectScopeImports(table *schema.Table, blocks []tickle.ScopeBlock) []string {
	imports := map[string]bool{}

	// Search methods always need fmt and net/http
	imports["fmt"] = true
	imports["net/http"] = true

	// Lock methods need time for Timeout(time.Duration)
	imports["time"] = true

	// Integrity-enabled tables need bytes and fmt for VerifyRow
	if table.IsImmutable || table.IsAppendOnly {
		imports["bytes"] = true
	}

	// Immutable tables need uuid, time, and database/sql for Create/Update/Delete overrides
	if table.IsImmutable {
		imports["github.com/google/uuid"] = true
		imports["database/sql"] = true
		if table.HasSoftDelete {
			imports["time"] = true
		}
	}

	// Append-only tables need uuid for Create override
	if table.IsAppendOnly {
		imports["github.com/google/uuid"] = true
	}

	// Only need strconv if there are numeric or boolean columns
	for _, col := range table.Columns {
		switch col.Type {
		case schema.Integer, schema.BigInteger, schema.Boolean, schema.Float, schema.Double:
			imports["strconv"] = true
		}
	}

	// Check if any timestamp columns exist and timestamp scopes are used
	hasTimestamp := false
	hasUUID := false
	hasDecimal := false
	hasJSONB := false

	for _, col := range table.Columns {
		switch col.Type {
		case schema.Timestamp, schema.Date:
			hasTimestamp = true
		case schema.UUID:
			hasUUID = true
		case schema.Decimal:
			hasDecimal = true
		case schema.JSONB:
			hasJSONB = true
		}
	}

	// Check if blocks reference these types
	for _, block := range blocks {
		if block.Scope == "timestamp" && hasTimestamp {
			imports["time"] = true
		}
	}

	// Always need these if columns of these types exist (for Where methods)
	if hasUUID {
		imports["github.com/google/uuid"] = true
	}
	if hasDecimal {
		imports["github.com/shopspring/decimal"] = true
	}
	if hasTimestamp {
		imports["time"] = true
	}
	if hasJSONB {
		imports["encoding/json"] = true
	}

	var sorted []string
	for imp := range imports {
		sorted = append(sorted, imp)
	}

	// Stdlib first
	var std, ext []string
	for _, imp := range sorted {
		if strings.Contains(imp, ".") {
			ext = append(ext, imp)
		} else {
			std = append(std, imp)
		}
	}
	return append(std, ext...)
}

// generateOrderByMethods emits typed OrderBy{Column}(direction string) methods
// for each column in the table. Encrypted/sealed columns are skipped since
// ordering ciphertext is meaningless. The generated methods call the validated
// OrderBy on the base builder with a hardcoded column name, making SQL injection
// structurally impossible.
func generateOrderByMethods(b *bytes.Buffer, table *schema.Table, queryType, builderField string) {
	for _, col := range table.Columns {
		if col.IsEncrypted || col.IsSealed {
			continue
		}
		pascal := snakeToPascal(col.Name)
		b.WriteString(fmt.Sprintf("// OrderBy%s orders results by the %s column.\n", pascal, col.Name))
		b.WriteString(fmt.Sprintf("func (q *%s) OrderBy%s(direction string) *%s {\n", queryType, pascal, queryType))
		b.WriteString(fmt.Sprintf("\tq.%s.OrderBy(%q, direction)\n", builderField, col.Name))
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}
}

// selectCols returns a comma-separated list of column names for a table, for use in SELECT statements.
func selectCols(table *schema.Table) string {
	var cols []string
	for _, col := range table.Columns {
		cols = append(cols, col.Name)
	}
	return strings.Join(cols, ", ")
}

// schemaTypeToTag maps a schema.ColumnType to the integrity type tag byte.
func schemaTypeToTag(ct schema.ColumnType) string {
	switch ct {
	case schema.UUID:
		return "0x01"
	case schema.String, schema.Text:
		return "0x02"
	case schema.Integer:
		return "0x03"
	case schema.BigInteger:
		return "0x04"
	case schema.Decimal:
		return "0x05"
	case schema.Boolean:
		return "0x06"
	case schema.Timestamp:
		return "0x07"
	case schema.JSONB:
		return "0x08"
	case schema.Binary:
		return "0x09"
	case schema.Date:
		return "0x0A"
	case schema.Time:
		return "0x0B"
	case schema.Float:
		return "0x0C"
	case schema.Double:
		return "0x0D"
	default:
		return "0x02" // default to string
	}
}

// generateColumnMeta emits a package-level variable with ColumnMeta for a table.
func generateColumnMeta(b *bytes.Buffer, table *schema.Table, structName string) {
	varName := fmt.Sprintf("%sColumns", toLowerFirst(structName))
	b.WriteString(fmt.Sprintf("var %s = []ColumnMeta{\n", varName))
	for _, col := range table.Columns {
		b.WriteString(fmt.Sprintf("\t{Name: %q, TypeTag: %s},\n", col.Name, schemaTypeToTag(col.Type)))
	}
	b.WriteString("}\n\n")
}

// generateChainHashBlock emits code to fetch the chain tail and compute the hash.
// The code assumes it's inside a Create/Update method with access to q.db(), model, and the columns var.
func generateChainHashBlock(tableName, structName string, isImmutable bool) string {
	var sb strings.Builder
	colsVar := fmt.Sprintf("%sColumns", toLowerFirst(structName))

	// Fetch chain tail — wrapped in block to avoid err redeclaration in Update
	sb.WriteString("\t// Hash chain: fetch tail and compute row_hash\n")
	sb.WriteString("\t{\n")
	sb.WriteString("\t\tvar chainTailHash []byte\n")
	if isImmutable {
		sb.WriteString(fmt.Sprintf("\t\tchainErr := q.db().QueryRow(\"SELECT row_hash FROM %s ORDER BY id DESC, version_id DESC LIMIT 1\").Scan(&chainTailHash)\n", tableName))
	} else {
		sb.WriteString(fmt.Sprintf("\t\tchainErr := q.db().QueryRow(\"SELECT row_hash FROM %s ORDER BY id DESC LIMIT 1\").Scan(&chainTailHash)\n", tableName))
	}
	sb.WriteString("\t\tif chainErr != nil {\n")
	sb.WriteString("\t\t\tchainTailHash = GenesisHash\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t\tmodel.PrevHash = chainTailHash\n")
	sb.WriteString(fmt.Sprintf("\t\tmodel.RowHash = computeRowHash(chainTailHash, model, %s)\n", colsVar))
	sb.WriteString("\t}\n\n")

	return sb.String()
}

// generateVerifyMethods emits VerifyChain and VerifyRow methods for a query type.
func generateVerifyMethods(b *bytes.Buffer, table *schema.Table, queryType, structName string, isImmutable bool) {
	colsVar := fmt.Sprintf("%sColumns", toLowerFirst(structName))

	// VerifyChain — scans into the model struct so serialization is identical to write path
	b.WriteString(fmt.Sprintf("// VerifyChain walks the full hash chain for %s from genesis to the latest row,\n", table.Name))
	b.WriteString("// recomputing each row_hash and checking it matches the stored value.\n")
	b.WriteString(fmt.Sprintf("func (q *%s) VerifyChain() error {\n", queryType))
	if isImmutable {
		b.WriteString(fmt.Sprintf("\trows, err := q.db().Query(\"SELECT %s FROM %s ORDER BY id ASC, version_id ASC\")\n",
			selectCols(table), table.Name))
	} else {
		b.WriteString(fmt.Sprintf("\trows, err := q.db().Query(\"SELECT %s FROM %s ORDER BY id ASC\")\n",
			selectCols(table), table.Name))
	}
	b.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\tdefer rows.Close()\n\n")
	b.WriteString("\tprevHash := GenesisHash\n")
	b.WriteString("\tposition := 0\n")
	b.WriteString("\tfor rows.Next() {\n")
	b.WriteString(fmt.Sprintf("\t\tvar record %s\n", structName))
	b.WriteString("\t\tif err := rows.Scan(dbScanDest(&record)...); err != nil {\n")
	b.WriteString("\t\t\treturn err\n\t\t}\n")
	b.WriteString("\t\tif !bytes.Equal(record.PrevHash, prevHash) {\n")
	b.WriteString(fmt.Sprintf("\t\t\treturn &ChainError{Table: %q, RowID: fmt.Sprintf(\"%%v\", record.ID), Expected: prevHash, Actual: record.PrevHash, Position: position}\n", table.Name))
	b.WriteString("\t\t}\n")
	b.WriteString(fmt.Sprintf("\t\trecomputed := computeRowHash(prevHash, &record, %s)\n", colsVar))
	b.WriteString("\t\tif !bytes.Equal(recomputed, record.RowHash) {\n")
	b.WriteString(fmt.Sprintf("\t\t\treturn &ChainError{Table: %q, RowID: fmt.Sprintf(\"%%v\", record.ID), Expected: recomputed, Actual: record.RowHash, Position: position}\n", table.Name))
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tprevHash = record.RowHash\n")
	b.WriteString("\t\tposition++\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn rows.Err()\n")
	b.WriteString("}\n\n")

	// VerifyRow
	b.WriteString(fmt.Sprintf("// VerifyRow checks that a single %s row's row_hash is consistent with its\n", structName))
	b.WriteString("// prev_hash and column data. Does NOT verify the full chain.\n")
	b.WriteString(fmt.Sprintf("func (q *%s) VerifyRow(record *%s) error {\n", queryType, structName))
	b.WriteString(fmt.Sprintf("\trecomputed := computeRowHash(record.PrevHash, record, %s)\n", colsVar))
	b.WriteString("\tif !bytes.Equal(recomputed, record.RowHash) {\n")
	b.WriteString(fmt.Sprintf("\t\treturn &ChainError{\n"))
	b.WriteString(fmt.Sprintf("\t\t\tTable:    %q,\n", table.Name))
	b.WriteString("\t\t\tRowID:    fmt.Sprintf(\"%v\", record.ID),\n")
	b.WriteString("\t\t\tExpected: recomputed,\n")
	b.WriteString("\t\t\tActual:   record.RowHash,\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

// GenerateTxMethods produces a tx_gen.go file with Tx.Query<Model>() methods
// for all tables in the models package.
func GenerateTxMethods(tables []*schema.Table, nestingMap map[string]SchemaRelationship, modelsDir, packageName string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// Collect only top-level tables (those that resolve to the models package)
	var topLevel []*schema.Table
	for _, tbl := range tables {
		_, pkg := resolveModelDir(modelsDir, tbl.Name, nestingMap)
		if pkg == packageName {
			topLevel = append(topLevel, tbl)
		}
	}

	if len(topLevel) == 0 {
		b.WriteString("// No models in this package.\n")
		return b.Bytes(), nil
	}

	for _, tbl := range topLevel {
		structName := tableToStructName(tbl.Name)
		queryType := structName + "Query"

		b.WriteString(fmt.Sprintf("// Query%s returns a %s scoped to this transaction.\n", structName, queryType))
		b.WriteString(fmt.Sprintf("func (tx *Tx) Query%s() *%s {\n", structName, queryType))
		b.WriteString(fmt.Sprintf("\tq := Query%s()\n", structName))
		if tbl.IsImmutable {
			b.WriteString("\tq.ImmutableQueryBuilder.setTx(tx.Conn())\n")
		} else {
			b.WriteString("\tq.QueryBuilder.setTx(tx.Conn())\n")
		}
		b.WriteString("\treturn q\n")
		b.WriteString("}\n\n")
	}

	return format.Source(b.Bytes())
}
