package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shortontech/pickle/pkg/schema"
	"github.com/shortontech/pickle/pkg/tickle"
)

// GenerateQueryScopes produces a Go source file with typed Where*/With* methods
// for a given table, using scope templates parsed from the cooked scopes file.
func GenerateQueryScopes(table *schema.Table, blocks []tickle.ScopeBlock, packageName string) ([]byte, error) {
	columns := tickle.ColumnsFromTable(table)
	structName := tableToStructName(table.Name)
	scopeBody, err := tickle.GenerateScopes(blocks, columns, structName)
	if err != nil {
		return nil, fmt.Errorf("generating scopes for %s: %w", structName, err)
	}

	// Collect imports needed by the generated scopes
	imports := collectScopeImports(table, blocks)

	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		b.WriteString(")\n\n")
	}

	// Generate the model-specific query wrapper type
	queryType := structName + "Query"
	b.WriteString(fmt.Sprintf("// %s provides typed query methods for %s.\n", queryType, structName))
	if table.IsImmutable {
		b.WriteString(fmt.Sprintf("type %s struct {\n\t*QueryBuilder[%s]\n\tallVersions bool\n}\n\n", queryType, structName))
	} else {
		b.WriteString(fmt.Sprintf("type %s struct {\n\t*QueryBuilder[%s]\n}\n\n", queryType, structName))
	}

	// Generate a typed Query constructor
	b.WriteString(fmt.Sprintf("// Query%s starts a new query for %s.\n", structName, structName))
	b.WriteString(fmt.Sprintf("func Query%s() *%s {\n", structName, queryType))
	if table.Connection != "" {
		b.WriteString(fmt.Sprintf("\treturn &%s{QueryBuilder: Query[%s](%q, %q)}\n", queryType, structName, table.Name, table.Connection))
	} else {
		b.WriteString(fmt.Sprintf("\treturn &%s{QueryBuilder: Query[%s](%q)}\n", queryType, structName, table.Name))
	}
	b.WriteString("}\n\n")

	// Generate eager loading methods from foreign keys
	for _, col := range table.Columns {
		if col.ForeignKeyTable != "" {
			relName := tableToStructName(col.ForeignKeyTable)
			b.WriteString(fmt.Sprintf("func (q *%s) With%s() *%s {\n", queryType, relName, queryType))
			b.WriteString(fmt.Sprintf("\tq.EagerLoad(%q)\n", col.ForeignKeyTable))
			b.WriteString(fmt.Sprintf("\treturn q\n"))
			b.WriteString("}\n\n")
		}
	}

	// Generate ownership scope if table has an owner column
	for _, col := range table.Columns {
		if col.IsOwnerColumn {
			goType := columnGoType(col)
			paramName := "ownerID"
			b.WriteString(fmt.Sprintf("// WhereOwnedBy filters records by the ownership column.\n"))
			b.WriteString(fmt.Sprintf("func (q *%s) WhereOwnedBy(%s %s) *%s {\n", queryType, paramName, goType, queryType))
			b.WriteString(fmt.Sprintf("\tq.where(%q, %s)\n", col.Name, paramName))
			b.WriteString(fmt.Sprintf("\treturn q\n"))
			b.WriteString("}\n\n")
			break
		}
	}

	// Generate chainable wrappers for base QueryBuilder methods so they
	// return the typed query wrapper instead of *QueryBuilder[T].
	for _, m := range []struct{ name, sig, call string }{
		{"AnyOwner", "", "AnyOwner()"},
		{"Limit", "n int", "Limit(n)"},
		{"Offset", "n int", "Offset(n)"},
		{"OrderBy", "column, direction string", "OrderBy(column, direction)"},
	} {
		b.WriteString(fmt.Sprintf("func (q *%s) %s(%s) *%s {\n", queryType, m.name, m.sig, queryType))
		b.WriteString(fmt.Sprintf("\tq.QueryBuilder.%s\n", m.call))
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}

	// Generate per-column Select methods
	for _, col := range table.Columns {
		pascal := snakeToPascal(col.Name)
		b.WriteString(fmt.Sprintf("func (q *%s) Select%s() *%s {\n", queryType, pascal, queryType))
		b.WriteString(fmt.Sprintf("\tq.addSelect(%q)\n", col.Name))
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}

	// Generate visibility scope methods (SelectPublic, SelectOwner, SelectAll)
	hasVisibility := false
	var publicCols, ownerCols []string
	for _, col := range table.Columns {
		if col.IsPublic {
			publicCols = append(publicCols, col.Name)
			ownerCols = append(ownerCols, col.Name)
			hasVisibility = true
		} else if col.IsOwnerSees {
			ownerCols = append(ownerCols, col.Name)
			hasVisibility = true
		}
	}

	if hasVisibility {
		// SelectPublic
		b.WriteString(fmt.Sprintf("// SelectPublic selects only columns marked Public().\n"))
		b.WriteString(fmt.Sprintf("func (q *%s) SelectPublic() *%s {\n", queryType, queryType))
		b.WriteString(fmt.Sprintf("\tq.selectedCols = []string{"))
		for i, c := range publicCols {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", c))
		}
		b.WriteString("}\n")
		b.WriteString("\tq.setVisibility(visibilityPublic)\n")
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")

		// SelectOwner
		b.WriteString(fmt.Sprintf("// SelectOwner selects columns visible to the resource owner.\n"))
		b.WriteString(fmt.Sprintf("func (q *%s) SelectOwner() *%s {\n", queryType, queryType))
		b.WriteString(fmt.Sprintf("\tq.selectedCols = []string{"))
		for i, c := range ownerCols {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", c))
		}
		b.WriteString("}\n")
		b.WriteString("\tq.setVisibility(visibilityOwner)\n")
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}

	// SelectAll — always generated
	b.WriteString(fmt.Sprintf("// SelectAll selects all columns. Use for internal/admin queries.\n"))
	b.WriteString(fmt.Sprintf("func (q *%s) SelectAll() *%s {\n", queryType, queryType))
	b.WriteString("\tq.setVisibility(visibilityAll)\n")
	b.WriteString(fmt.Sprintf("\treturn q\n"))
	b.WriteString("}\n\n")

	// Generate table-level scopes (FetchResource / FetchResources)
	tableScopeBody := tickle.GenerateTableScopes(blocks, structName, HasOwnership(table))
	b.WriteString(tableScopeBody)

	b.WriteString(scopeBody)

	// Generate Search methods
	generateSearchMethods(&b, table, queryType, structName)

	// Generate immutable table methods
	if table.IsImmutable {
		generateImmutableMethods(&b, table, queryType, structName)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("go format: %w\n%s", err, b.String())
	}

	return formatted, nil
}

// generateImmutableMethods emits Create, Update, Delete (if SoftDeletes), All,
// First, Count, and AllVersions overrides for an immutable table's query type.
func generateImmutableMethods(b *bytes.Buffer, table *schema.Table, queryType, structName string) {
	// Collect all db column names in order
	var cols []string
	for _, col := range table.Columns {
		cols = append(cols, fmt.Sprintf("%q", col.Name))
	}
	colsLiteral := "[]string{" + strings.Join(cols, ", ") + "}"
	softDeletes := table.HasSoftDelete

	// AllVersions — bypass deduplication
	b.WriteString(fmt.Sprintf("// AllVersions bypasses deduplication and returns the full version history.\n"))
	b.WriteString(fmt.Sprintf("func (q *%s) AllVersions() *%s {\n\tq.allVersions = true\n\treturn q\n}\n\n", queryType, queryType))

	// All override
	b.WriteString(fmt.Sprintf("func (q *%s) All() ([]%s, error) {\n", queryType, structName))
	b.WriteString(fmt.Sprintf("\treturn q.immutableAll(%s, %v, q.allVersions)\n}\n\n", colsLiteral, softDeletes))

	// First override
	b.WriteString(fmt.Sprintf("func (q *%s) First() (*%s, error) {\n", queryType, structName))
	b.WriteString(fmt.Sprintf("\treturn q.immutableFirst(%s, %v, q.allVersions)\n}\n\n", colsLiteral, softDeletes))

	// Count override
	b.WriteString(fmt.Sprintf("func (q *%s) Count() (int64, error) {\n", queryType))
	b.WriteString(fmt.Sprintf("\treturn q.immutableCount(%v)\n}\n\n", softDeletes))

	// Create override — generates id and version_id
	b.WriteString(fmt.Sprintf("func (q *%s) Create(model *%s) error {\n", queryType, structName))
	b.WriteString("\tif model.ID == (uuid.UUID{}) {\n\t\tmodel.ID = uuid.New()\n\t}\n")
	b.WriteString("\tmodel.VersionID = uuid.New()\n")
	b.WriteString("\treturn q.QueryBuilder.Create(model)\n}\n\n")

	// Update override — inserts new version with same id
	b.WriteString(fmt.Sprintf("func (q *%s) Update(model *%s) error {\n", queryType, structName))
	b.WriteString("\tmodel.VersionID = uuid.New()\n")
	b.WriteString("\treturn q.QueryBuilder.Create(model)\n}\n\n")

	// Delete override — only if SoftDeletes
	if softDeletes {
		b.WriteString(fmt.Sprintf("func (q *%s) Delete(model *%s) error {\n", queryType, structName))
		b.WriteString("\tnow := time.Now()\n\tmodel.DeletedAt = &now\n")
		b.WriteString("\tmodel.VersionID = uuid.New()\n")
		b.WriteString("\treturn q.QueryBuilder.Create(model)\n}\n\n")
	}
}

// GenerateViewQueryScopes produces a Go source file with typed Where* methods
// for a view. The query wrapper is read-only — no Create/Update/Delete.
func GenerateViewQueryScopes(view *schema.View, blocks []tickle.ScopeBlock, packageName string) ([]byte, error) {
	// Build columns from view columns
	var columns []tickle.ColumnDef
	for _, vc := range view.Columns {
		col := &vc.Column
		col.Name = vc.OutputName()
		columns = append(columns, tickle.ColumnDef{
			PascalName: snakeToPascal(col.Name),
			SnakeName:  col.Name,
			GoType:     columnGoType(col),
			Scope:      tickle.ScopeForType(col.Type),
		})
	}

	structName := tableToStructName(view.Name)
	scopeBody, err := tickle.GenerateScopes(blocks, columns, structName)
	if err != nil {
		return nil, fmt.Errorf("generating scopes for view %s: %w", structName, err)
	}

	imports := collectViewScopeImports(view, blocks)

	var b bytes.Buffer
	b.WriteString("// Code generated by Pickle. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		b.WriteString(")\n\n")
	}

	queryType := structName + "Query"
	b.WriteString(fmt.Sprintf("// %s provides read-only typed query methods for the %s view.\n", queryType, view.Name))
	b.WriteString(fmt.Sprintf("type %s struct {\n\t*QueryBuilder[%s]\n}\n\n", queryType, structName))

	b.WriteString(fmt.Sprintf("// Query%s starts a new read-only query for %s.\n", structName, structName))
	b.WriteString(fmt.Sprintf("func Query%s() *%s {\n", structName, queryType))
	b.WriteString(fmt.Sprintf("\treturn &%s{QueryBuilder: Query[%s](%q)}\n", queryType, structName, view.Name))
	b.WriteString("}\n\n")

	// Generate chainable wrappers for base QueryBuilder methods.
	for _, m := range []struct{ name, sig, call string }{
		{"Limit", "n int", "Limit(n)"},
		{"Offset", "n int", "Offset(n)"},
		{"OrderBy", "column, direction string", "OrderBy(column, direction)"},
	} {
		b.WriteString(fmt.Sprintf("func (q *%s) %s(%s) *%s {\n", queryType, m.name, m.sig, queryType))
		b.WriteString(fmt.Sprintf("\tq.QueryBuilder.%s\n", m.call))
		b.WriteString(fmt.Sprintf("\treturn q\n"))
		b.WriteString("}\n\n")
	}

	b.WriteString(scopeBody)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("go format: %w\n%s", err, b.String())
	}

	return formatted, nil
}

func collectViewScopeImports(view *schema.View, blocks []tickle.ScopeBlock) []string {
	imports := map[string]bool{}

	hasTimestamp := false
	hasUUID := false
	hasDecimal := false
	hasJSONB := false

	for _, vc := range view.Columns {
		switch vc.Type {
		case schema.Timestamp, schema.Date:
			hasTimestamp = true
		case schema.UUID:
			hasUUID = true
		case schema.Decimal:
			hasDecimal = true
		case schema.JSONB:
			hasJSONB = true
		}
	}

	for _, block := range blocks {
		if block.Scope == "timestamp" && hasTimestamp {
			imports["time"] = true
		}
	}

	if hasUUID {
		imports["github.com/google/uuid"] = true
	}
	if hasDecimal {
		imports["github.com/shopspring/decimal"] = true
	}
	if hasTimestamp {
		imports["time"] = true
	}
	if hasJSONB {
		imports["encoding/json"] = true
	}

	var sorted []string
	for imp := range imports {
		sorted = append(sorted, imp)
	}

	var std, ext []string
	for _, imp := range sorted {
		if strings.Contains(imp, ".") {
			ext = append(ext, imp)
		} else {
			std = append(std, imp)
		}
	}
	return append(std, ext...)
}

func collectScopeImports(table *schema.Table, blocks []tickle.ScopeBlock) []string {
	imports := map[string]bool{}

	// Search methods always need fmt and net/http
	imports["fmt"] = true
	imports["net/http"] = true

	// Immutable tables need uuid and time for Create/Update/Delete overrides
	if table.IsImmutable {
		imports["github.com/google/uuid"] = true
		if table.HasSoftDelete {
			imports["time"] = true
		}
	}

	// Only need strconv if there are numeric or boolean columns
	for _, col := range table.Columns {
		switch col.Type {
		case schema.Integer, schema.BigInteger, schema.Boolean:
			imports["strconv"] = true
		}
	}

	// Check if any timestamp columns exist and timestamp scopes are used
	hasTimestamp := false
	hasUUID := false
	hasDecimal := false
	hasJSONB := false

	for _, col := range table.Columns {
		switch col.Type {
		case schema.Timestamp, schema.Date:
			hasTimestamp = true
		case schema.UUID:
			hasUUID = true
		case schema.Decimal:
			hasDecimal = true
		case schema.JSONB:
			hasJSONB = true
		}
	}

	// Check if blocks reference these types
	for _, block := range blocks {
		if block.Scope == "timestamp" && hasTimestamp {
			imports["time"] = true
		}
	}

	// Always need these if columns of these types exist (for Where methods)
	if hasUUID {
		imports["github.com/google/uuid"] = true
	}
	if hasDecimal {
		imports["github.com/shopspring/decimal"] = true
	}
	if hasTimestamp {
		imports["time"] = true
	}
	if hasJSONB {
		imports["encoding/json"] = true
	}

	var sorted []string
	for imp := range imports {
		sorted = append(sorted, imp)
	}

	// Stdlib first
	var std, ext []string
	for _, imp := range sorted {
		if strings.Contains(imp, ".") {
			ext = append(ext, imp)
		} else {
			std = append(std, imp)
		}
	}
	return append(std, ext...)
}
