package generator

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateSeederModelGlue lowers logical encrypted/sealed seed values to the
// physical storage columns owned by the generated model layer.
func GenerateSeederModelGlue(packageName string, tables []*schema.Table, exported bool) ([]byte, error) {
	var out bytes.Buffer
	hasEncrypted := false
	for _, table := range tables {
		for _, column := range table.Columns {
			hasEncrypted = hasEncrypted || column.IsEncrypted || column.IsSealed
		}
	}
	fmt.Fprintf(&out, "// Code generated by Pickle. DO NOT EDIT.\npackage %s\n\n", packageName)
	if hasEncrypted {
		out.WriteString("import \"fmt\"\n\n")
	}
	out.WriteString("func TransformSeedValues(table string, values map[string]any) (map[string]any, error) {\n")
	out.WriteString("\tout := make(map[string]any, len(values)+2)\n\tfor key, value := range values { out[key] = value }\n")
	out.WriteString("\tswitch table {\n")
	for _, table := range tables {
		var encrypted []*schema.Column
		for _, column := range table.Columns {
			if column.IsEncrypted || column.IsSealed {
				encrypted = append(encrypted, column)
			}
		}
		if len(encrypted) == 0 {
			continue
		}
		fmt.Fprintf(&out, "\tcase %q:\n", table.Name)
		for _, column := range encrypted {
			fmt.Fprintf(&out, "\t\tif value, ok := out[%q]; ok {\n", column.Name)
			fmt.Fprintf(&out, "\t\t\tdelete(out, %q)\n", column.Name)
			out.WriteString("\t\t\tif value != nil {\n")
			if exported {
				out.WriteString("\t\t\t\tkey, err := exportedEncryptionKey(); if err != nil { return nil, err }\n")
				if column.IsEncrypted {
					out.WriteString("\t\t\t\tciphertext, err := encryptDeterministic(key, []byte(fmt.Sprint(value)))\n")
				} else {
					out.WriteString("\t\t\t\tciphertext, err := encryptRandom(key, []byte(fmt.Sprint(value)))\n")
				}
				out.WriteString("\t\t\t\tif err != nil { return nil, err }\n")
				fmt.Fprintf(&out, "\t\t\t\tout[%q] = ciphertext\n", column.Name+"_encrypted")
			} else {
				function := "encryptSIV"
				if column.IsSealed {
					function = "encryptGCM"
				}
				fmt.Fprintf(&out, "\t\t\t\tciphertext, err := %s(EncryptionKey, []byte(fmt.Sprint(value)))\n", function)
				out.WriteString("\t\t\t\tif err != nil { return nil, err }\n")
				fmt.Fprintf(&out, "\t\t\t\tout[%q] = ciphertext\n", column.Name+"_encrypted")
				out.WriteString("\t\t\t\tif len(EncryptionKeyNext) > 0 {\n")
				fmt.Fprintf(&out, "\t\t\t\t\tnext, err := %s(EncryptionKeyNext, []byte(fmt.Sprint(value))); if err != nil { return nil, err }\n", function)
				fmt.Fprintf(&out, "\t\t\t\t\tout[%q] = next\n", column.Name+"_encrypted_v2")
				out.WriteString("\t\t\t\t}\n")
			}
			out.WriteString("\t\t\t} else {\n")
			fmt.Fprintf(&out, "\t\t\t\tout[%q] = nil\n", column.Name+"_encrypted")
			out.WriteString("\t\t\t}\n\t\t}\n")
		}
	}
	out.WriteString("\t}\n\treturn out, nil\n}\n")
	out.WriteString("\nfunc TransformSeedColumn(table, column string) string {\n\tswitch table {\n")
	for _, table := range tables {
		var encrypted []*schema.Column
		for _, column := range table.Columns {
			if column.IsEncrypted || column.IsSealed {
				encrypted = append(encrypted, column)
			}
		}
		if len(encrypted) == 0 {
			continue
		}
		fmt.Fprintf(&out, "\tcase %q:\n\t\tswitch column {\n", table.Name)
		for _, column := range encrypted {
			fmt.Fprintf(&out, "\t\tcase %q: return %q\n", column.Name, column.Name+"_encrypted")
		}
		out.WriteString("\t\t}\n")
	}
	out.WriteString("\t}\n\treturn column\n}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("format seeder model glue: %w\n%s", err, out.String())
	}
	return formatted, nil
}
