package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"

	"github.com/shortontech/pickle/pkg/schema"
)

// GenerateSeederGlue produces database/seeders/pickle_gen.go. It keeps the
// compiled application independent of Pickle by referring only to the schema
// types already generated into the project's migrations package.
func GenerateSeederGlue(packageName, migrationsImport string, definitions []SeederDefinition, tables []*schema.Table) ([]byte, error) {
	var scenarios []SeederDefinition
	for _, definition := range definitions {
		if definition.Kind == "scenario" {
			scenarios = append(scenarios, definition)
		}
	}
	sort.Slice(scenarios, func(i, j int) bool { return scenarios[i].Name < scenarios[j].Name })
	tables = append([]*schema.Table(nil), tables...)
	sort.Slice(tables, func(i, j int) bool { return tables[i].Name < tables[j].Name })

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by Pickle. DO NOT EDIT.\npackage %s\n\n", packageName)
	fmt.Fprintf(&out, "import (\n\t\"fmt\"\n\t\"sort\"\n\n\tseed %q\n)\n\n", migrationsImport)
	out.WriteString("type Scenario interface { Seed(*seed.SeedGraph) }\n\n")
	out.WriteString("var scenarioFactories = map[string]func() Scenario{\n")
	for _, scenario := range scenarios {
		fmt.Fprintf(&out, "\t%q: func() Scenario { return &%s{} },\n", scenario.Name, scenario.Name)
	}
	out.WriteString("}\n\n")
	out.WriteString("func Names() []string {\n\tnames := make([]string, 0, len(scenarioFactories))\n\tfor name := range scenarioFactories { names = append(names, name) }\n\tsort.Strings(names)\n\treturn names\n}\n\n")
	out.WriteString("func Graph(name string) (*seed.SeedGraph, error) {\n\tfactory := scenarioFactories[name]\n\tif factory == nil { return nil, fmt.Errorf(\"unknown seed scenario %q\", name) }\n\tgraph := &seed.SeedGraph{}\n\tfactory().Seed(graph)\n\treturn graph, nil\n}\n\n")
	out.WriteString("func Tables() []*seed.Table {\n\treturn []*seed.Table{\n")
	for _, table := range tables {
		fmt.Fprintf(&out, "\t\t{Name: %q, Columns: []*seed.Column{\n", table.Name)
		for _, column := range table.Columns {
			fmt.Fprintf(&out, "\t\t\t{Name: %q, Type: seed.ColumnType(%d), IsNullable: %t, HasDefault: %t", column.Name, column.Type, column.IsNullable, column.HasDefault)
			if column.ForeignKeyTable != "" {
				fmt.Fprintf(&out, ", ForeignKeyTable: %q, ForeignKeyColumn: %q", column.ForeignKeyTable, column.ForeignKeyColumn)
			}
			if column.Seeder != nil {
				fmt.Fprintf(&out, ", Seeder: %s", seedSpecLiteral(column.Seeder))
			}
			out.WriteString("},\n")
		}
		out.WriteString("\t\t}, ForeignKeys: []*seed.ForeignKey{\n")
		for _, fk := range table.ForeignKeys {
			fmt.Fprintf(&out, "\t\t\t{Columns: %#v, ReferencedTable: %q, ReferencedColumns: %#v},\n", fk.Columns, fk.ReferencedTable, fk.ReferencedColumns)
		}
		out.WriteString("\t\t}},\n")
	}
	out.WriteString("\t}\n}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("format seeder glue: %w\n%s", err, out.String())
	}
	return formatted, nil
}

func seedSpecLiteral(spec *schema.SeedSpec) string {
	return fmt.Sprintf("&seed.SeedSpec{Kind: %q, Arguments: %#v, Fields: %#v, Reference: %q, NullWeight: %v}", spec.Kind, spec.Arguments, spec.Fields, spec.Reference, spec.NullWeight)
}
