package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"text/template"

	"github.com/shortontech/pickle/pkg/schema"
)

var viewModelTemplate = template.Must(template.New("viewmodel").Parse(`// Code generated by Pickle. DO NOT EDIT.
package {{ .Package }}
{{ if .Imports }}
import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
)
{{ end }}
// {{ .StructName }} is a read-only model generated from the {{ .ViewName }} database view.
type {{ .StructName }} struct {
{{- range .Fields }}
	{{ .Name }} {{ .Type }} ` + "`" + `json:"{{ .JSONTag }}" db:"{{ .DBTag }}"` + "`" + `
{{- end }}
}
`))

type viewModelData struct {
	Package    string
	StructName string
	ViewName   string
	Imports    []string
	Fields     []fieldData
}

// GenerateViewModel produces a Go source file containing the model struct for a view.
func GenerateViewModel(view *schema.View, packageName string) ([]byte, error) {
	imports := map[string]bool{}
	var fields []fieldData

	for _, vc := range view.Columns {
		colName := vc.OutputName()
		if colName == "" {
			colName = vc.Name
		}
		col := &schema.Column{
			Name:      colName,
			Type:      vc.Type,
			IsNullable: vc.IsNullable,
			Precision: vc.Precision,
			Scale:     vc.Scale,
			Length:    vc.Length,
		}
		goType := columnGoType(col)
		if imp := columnImport(col); imp != "" {
			imports[imp] = true
		}

		jsonTag := col.Name
		if col.IsNullable {
			jsonTag += ",omitempty"
		}

		fields = append(fields, fieldData{
			Name:    snakeToPascal(col.Name),
			Type:    goType,
			JSONTag: jsonTag,
			DBTag:   col.Name,
		})
	}

	var sortedImports []string
	for imp := range imports {
		sortedImports = append(sortedImports, imp)
	}
	sort.Strings(sortedImports)

	var stdImports, extImports []string
	for _, imp := range sortedImports {
		if strings.Contains(imp, ".") {
			extImports = append(extImports, imp)
		} else {
			stdImports = append(stdImports, imp)
		}
	}
	orderedImports := append(stdImports, extImports...)

	data := viewModelData{
		Package:    packageName,
		StructName: tableToStructName(view.Name),
		ViewName:   view.Name,
		Imports:    orderedImports,
		Fields:     fields,
	}

	var buf bytes.Buffer
	if err := viewModelTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("template execution: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("go format: %w", err)
	}

	return formatted, nil
}
