// Code generated by Pickle. DO NOT EDIT.
package auth

import (
	"fmt"
	"net/http"
	"os"

	pickle "github.com/shortontech/pickle/testdata/basic-crud/app/http"
	jwt "github.com/shortontech/pickle/testdata/basic-crud/app/http/auth/jwt"
	session "github.com/shortontech/pickle/testdata/basic-crud/app/http/auth/session"
	"github.com/shortontech/pickle/testdata/basic-crud/config"
)

// AuthDriver is the interface every auth driver implements.
type AuthDriver interface {
	// Authenticate validates the request and returns auth info.
	// Returns nil, err if authentication fails.
	Authenticate(r *http.Request) (*pickle.AuthInfo, error)
}

var registry = map[string]AuthDriver{}

func init() {
	registry["jwt"] = jwt.NewDriver(config.Env)
	registry["session"] = session.NewDriver(config.Env)
}

// Driver returns the named auth driver, or panics if not found.
func Driver(name string) AuthDriver {
	d, ok := registry[name]
	if !ok {
		available := make([]string, 0, len(registry))
		for k := range registry {
			available = append(available, k)
		}
		panic(fmt.Sprintf("auth: unknown driver %q (available: %v)", name, available))
	}
	return d
}

// ActiveDriver returns the driver selected by AUTH_DRIVER env var.
func ActiveDriver() AuthDriver {
	name := config.Env("AUTH_DRIVER", "")
	if name == "" {
		// Default to first available
		for k := range registry {
			name = k
			break
		}
	}
	return Driver(name)
}

// ActiveDriverName returns the name of the currently active auth driver.
func ActiveDriverName() string {
	name := config.Env("AUTH_DRIVER", "")
	if name == "" {
		for k := range registry {
			return k
		}
	}
	return name
}

// Authenticate is a convenience function that calls Authenticate on the active driver.
func Authenticate(r *http.Request) (*pickle.AuthInfo, error) {
	return ActiveDriver().Authenticate(r)
}

// DefaultAuthMiddleware validates requests using the active auth driver
// and sets auth info on the context.
func DefaultAuthMiddleware(ctx *pickle.Context, next func() pickle.Response) pickle.Response {
	info, err := Authenticate(ctx.Request())
	if err != nil {
		return ctx.Unauthorized(err.Error())
	}
	ctx.SetAuth(info)
	return next()
}

// Env reads the AUTH_DRIVER environment variable.
// Useful for logging or diagnostics.
func Env() string {
	return os.Getenv("AUTH_DRIVER")
}
