// Code generated by Pickle. DO NOT EDIT.
package auth

import (
	"database/sql"
	"fmt"
	"net/http"

	pickle "github.com/shortontech/pickle/testdata/basic-crud/app/http"
	jwt "github.com/shortontech/pickle/testdata/basic-crud/app/http/auth/jwt"
	session "github.com/shortontech/pickle/testdata/basic-crud/app/http/auth/session"
)

// AuthDriver is the interface every auth driver implements.
type AuthDriver interface {
	// Authenticate validates the request and returns auth info.
	// Returns nil, err if authentication fails.
	Authenticate(r *http.Request) (*pickle.AuthInfo, error)
}

var registry = map[string]AuthDriver{}

var envFunc func(string, string) string

// Init initializes all auth drivers with the given env lookup function and database connection.
// Must be called after config and database are initialized.
func Init(env func(string, string) string, db *sql.DB) {
	envFunc = env
	registry["jwt"] = jwt.NewDriver(env, db)
	registry["session"] = session.NewDriver(env, db)
}

// Driver returns the named auth driver, or panics if not found.
func Driver(name string) AuthDriver {
	d, ok := registry[name]
	if !ok {
		available := make([]string, 0, len(registry))
		for k := range registry {
			available = append(available, k)
		}
		panic(fmt.Sprintf("auth: unknown driver %q (available: %v)", name, available))
	}
	return d
}

// ActiveDriver returns the driver selected by AUTH_DRIVER env var.
// Defaults to "jwt" if AUTH_DRIVER is not set.
func ActiveDriver() AuthDriver {
	name := activeDriverName()
	return Driver(name)
}

func activeDriverName() string {
	if envFunc != nil {
		name := envFunc("AUTH_DRIVER", "jwt")
		if name != "" {
			return name
		}
	}
	return "jwt"
}

// ActiveDriverName returns the name of the currently active auth driver.
func ActiveDriverName() string {
	return activeDriverName()
}

// Authenticate is a convenience function that calls Authenticate on the active driver.
func Authenticate(r *http.Request) (*pickle.AuthInfo, error) {
	return ActiveDriver().Authenticate(r)
}

// DefaultAuthMiddleware validates requests using the active auth driver
// and sets auth info on the context.
func DefaultAuthMiddleware(ctx *pickle.Context, next func() pickle.Response) pickle.Response {
	info, err := Authenticate(ctx.Request())
	if err != nil {
		return ctx.Unauthorized(err.Error())
	}
	ctx.SetAuth(info)
	return next()
}

// Env reads the AUTH_DRIVER setting via the configured env function.
// Useful for logging or diagnostics.
func Env() string {
	return activeDriverName()
}
