package blade

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
	"strings"
)

// AssetSource is an authored static asset read during generation.
type AssetSource struct {
	Name string
	Body []byte
}

// CompileAssetsGo emits the content-addressed asset registry and handler. The
// returned manifest maps authored names to immutable public URLs.
func CompileAssetsGo(packageName string, sources []AssetSource) ([]byte, map[string]string, error) {
	sort.Slice(sources, func(i, j int) bool { return sources[i].Name < sources[j].Name })
	manifest := make(map[string]string, len(sources))
	publicNames := make(map[string]string, len(sources))
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by Pickle. DO NOT EDIT.\n\npackage %s\n\nimport \"net/http\"\n\ntype pickleAssetRecord struct { body []byte; contentType, etag string }\n\nvar pickleAssets = map[string]pickleAssetRecord{\n", packageName)
	for _, source := range sources {
		if source.Name == "" || strings.Contains(source.Name, "..") || strings.ContainsRune(source.Name, '\\') {
			return nil, nil, fmt.Errorf("invalid asset path %q", source.Name)
		}
		digest := sha256.Sum256(source.Body)
		hexDigest := hex.EncodeToString(digest[:])
		ext := filepath.Ext(source.Name)
		stem := strings.TrimSuffix(filepath.Base(source.Name), ext)
		publicName := stem + "." + hexDigest[:12] + ext
		publicURL := "/assets/" + publicName
		if previous := publicNames[publicName]; previous != "" && previous != source.Name {
			return nil, nil, fmt.Errorf("assets %q and %q produce the same public path", previous, source.Name)
		}
		publicNames[publicName] = source.Name
		contentType := assetContentType(ext)
		manifest[source.Name] = publicURL
		fmt.Fprintf(&b, "%q: {body: %#v, contentType: %q, etag: %q},\n", publicName, source.Body, contentType, `"sha256-`+hexDigest+`"`)
	}
	b.WriteString("}\n\n")
	b.WriteString(`// PickleAsset serves only generated, content-addressed assets.
func PickleAsset(ctx *Context) Response {
	name := ctx.Param("asset")
	asset, ok := pickleAssets[name]
	if !ok { return ctx.NotFound("asset not found") }
	headers := map[string]string{
		"Content-Type": asset.contentType,
		"Cache-Control": "public, max-age=31536000, immutable",
		"ETag": asset.etag,
		"X-Content-Type-Options": "nosniff",
	}
	if ctx.Request().Header.Get("If-None-Match") == asset.etag {
		return Response{StatusCode: http.StatusNotModified, Headers: headers}
	}
	return renderedAssetResponse(asset.body, headers)
}
`)
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, nil, fmt.Errorf("formatting generated assets: %w\n%s", err, b.String())
	}
	return formatted, manifest, nil
}

func assetContentType(ext string) string {
	switch strings.ToLower(ext) {
	case ".css":
		return "text/css; charset=utf-8"
	case ".js", ".mjs":
		return "text/javascript; charset=utf-8"
	case ".json", ".map":
		return "application/json"
	case ".svg":
		return "image/svg+xml"
	case ".png":
		return "image/png"
	case ".jpg", ".jpeg":
		return "image/jpeg"
	case ".gif":
		return "image/gif"
	case ".webp":
		return "image/webp"
	case ".ico":
		return "image/x-icon"
	case ".woff":
		return "font/woff"
	case ".woff2":
		return "font/woff2"
	case ".ttf":
		return "font/ttf"
	case ".txt":
		return "text/plain; charset=utf-8"
	default:
		return "application/octet-stream"
	}
}
