// Code generated by Pickle. DO NOT EDIT.
package requests

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/go-playground/validator/v10"
)

var validate = validator.New()

// ValidationError represents a single field validation failure.
type ValidationError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// BindingError represents a request binding or validation failure.
type BindingError struct {
	Status int               `json:"-"`
	Errors []ValidationError `json:"errors"`
}

func (e *BindingError) Error() string {
	msgs := make([]string, len(e.Errors))
	for i, ve := range e.Errors {
		msgs[i] = ve.Field + ": " + ve.Message
	}
	return strings.Join(msgs, "; ")
}

func formatValidationErrors(err error) *BindingError {
	ve, ok := err.(validator.ValidationErrors)
	if !ok {
		return &BindingError{
			Status: 422,
			Errors: []ValidationError{{Field: "_body", Message: err.Error()}},
		}
	}

	errors := make([]ValidationError, len(ve))
	for i, fe := range ve {
		errors[i] = ValidationError{
			Field:   toSnakeCase(fe.Field()),
			Message: formatFieldError(fe),
		}
	}

	return &BindingError{Status: 422, Errors: errors}
}

func formatFieldError(fe validator.FieldError) string {
	switch fe.Tag() {
	case "required":
		return "is required"
	case "email":
		return "must be a valid email address"
	case "min":
		return fmt.Sprintf("must be at least %s", fe.Param())
	case "max":
		return fmt.Sprintf("must be at most %s", fe.Param())
	case "oneof":
		return fmt.Sprintf("must be one of: %s", fe.Param())
	case "uuid":
		return "must be a valid UUID"
	case "required_if":
		return fmt.Sprintf("is required when %s", fe.Param())
	default:
		return fmt.Sprintf("failed %s validation", fe.Tag())
	}
}

func toSnakeCase(s string) string {
	var result []byte
	for i, c := range s {
		if c >= 'A' && c <= 'Z' {
			if i > 0 {
				result = append(result, '_')
			}
			result = append(result, byte(c+32))
		} else {
			result = append(result, byte(c))
		}
	}
	return string(result)
}

// BindCreatePostRequest deserializes and validates a CreatePostRequest from the HTTP request body.
func BindCreatePostRequest(r *http.Request) (CreatePostRequest, *BindingError) {
	var req CreatePostRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		return req, &BindingError{
			Status: 400,
			Errors: []ValidationError{{Field: "_body", Message: "invalid request body"}},
		}
	}
	if err := validate.Struct(req); err != nil {
		return req, formatValidationErrors(err)
	}
	return req, nil
}

// BindCreateUserRequest deserializes and validates a CreateUserRequest from the HTTP request body.
func BindCreateUserRequest(r *http.Request) (CreateUserRequest, *BindingError) {
	var req CreateUserRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		return req, &BindingError{
			Status: 400,
			Errors: []ValidationError{{Field: "_body", Message: "invalid request body"}},
		}
	}
	if err := validate.Struct(req); err != nil {
		return req, formatValidationErrors(err)
	}
	return req, nil
}

// BindLoginRequest deserializes and validates a LoginRequest from the HTTP request body.
func BindLoginRequest(r *http.Request) (LoginRequest, *BindingError) {
	var req LoginRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		return req, &BindingError{
			Status: 400,
			Errors: []ValidationError{{Field: "_body", Message: "invalid request body"}},
		}
	}
	if err := validate.Struct(req); err != nil {
		return req, formatValidationErrors(err)
	}
	return req, nil
}

// BindUpdatePostRequest deserializes and validates a UpdatePostRequest from the HTTP request body.
func BindUpdatePostRequest(r *http.Request) (UpdatePostRequest, *BindingError) {
	var req UpdatePostRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		return req, &BindingError{
			Status: 400,
			Errors: []ValidationError{{Field: "_body", Message: "invalid request body"}},
		}
	}
	if err := validate.Struct(req); err != nil {
		return req, formatValidationErrors(err)
	}
	return req, nil
}

// BindUpdateUserRequest deserializes and validates a UpdateUserRequest from the HTTP request body.
func BindUpdateUserRequest(r *http.Request) (UpdateUserRequest, *BindingError) {
	var req UpdateUserRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		return req, &BindingError{
			Status: 400,
			Errors: []ValidationError{{Field: "_body", Message: "invalid request body"}},
		}
	}
	if err := validate.Struct(req); err != nil {
		return req, formatValidationErrors(err)
	}
	return req, nil
}
